window.__freshliTranslations = window.__freshliTranslations || {};
window.__freshliTranslations.en = {
  nav: {
    features: "Features",
    impact: "Impact",
    support: "Support",
    downloadFree: "Download Free",
    backHome: "← Back to home",
    language: "Language"
  },
  hero: {
    title: "Your food.<br>Your <span class=\"green\">impact.</span>",
    subtitle: "Freshli uses on-device Apple Intelligence to rescue your expiring food — private, instant, no internet needed. For the people. For the planet.",
    ctaDownload: "Download on App Store",
    ctaFeatures: "See Features ↓",
    badgeAI: "🤖 Apple Intelligence",
    badgeOnDevice: "🔒 100% On-Device",
    badgeLanguages: "🌍 10 Languages"
  },
  how: {
    label: "🚀 How It Works",
    title: "Three steps to<br>zero food waste.",
    step1Title: "Add your food",
    step1Text: "Scan a barcode, snap a receipt, or type manually. Takes 5 seconds.",
    step2Title: "Get smart alerts",
    step2Text: "Freshli warns you what's expiring soon and suggests AI recipes to use it all.",
    step3Title: "Rescue or share",
    step3Text: "Cook it, share it with neighbours, or donate it to a community fridge."
  },
  features: {
    label: "✨ Features",
    title: "Everything you need<br>to stop food waste.",
    subtitle: "Track, rescue, share, and celebrate — all in one beautiful app, made for people who care about the planet.",
    rescueChef: { title: "AI Rescue Chef", text: "One tap and Apple Intelligence writes a recipe from your pantry. On-device, private, no internet needed." },
    expiry: { title: "Smart Expiry Tracking", text: "Scan barcodes, receipts, or type by hand. Colour-coded pills show what needs to go first at a glance." },
    community: { title: "Community Sharing", text: "List surplus food for free collection by neighbours. Find community fridges. Join local circles for hyper-local sharing." },
    wrap: { title: "Weekly Wrap", text: "A cinematic recap of your food-rescue journey — items saved, CO² avoided, money saved. Share to Instagram Stories." },
    watch: { title: "Apple Watch & Widgets", text: "Glanceable expiry alerts on your wrist. Interactive widgets with one-tap consume. Live Activities on your lock screen." },
    siri: { title: "\"Hey Siri, rescue my pantry\"", text: "Voice-activated AI recipes from Siri, Shortcuts, Spotlight, or Control Centre. Zero taps required." },
    handsfree: { title: "Hands-Free Cooking", text: "Freshli reads each recipe step aloud so you never touch your phone while cooking. Eyes on the pan, not the screen." },
    wave: { title: "Live Wave", text: "See real-time global impact — how many people are rescuing food right now, total CO₂ avoided, and meals shared worldwide."
    }
  },
  testimonial: {
    quote: "I used to bin at least £15 of food a week. With Freshli I haven't thrown away anything in three weeks. The AI recipes are genuinely useful.",
    author: "— Sarah K., London"
  },
  ai: {
    label: "🧠 Apple Intelligence",
    title: "Your pantry data<br>never leaves your phone.",
    subtitle: "Freshli's Rescue Chef runs entirely on-device using iOS 26's FoundationModels framework. No servers. No API costs. No privacy compromises. Your fridge is your business."
  },
  impact: {
    label: "🌍 Global Impact",
    title: "Together, we're building<br>a waste-free world.",
    subtitle: "Every item you rescue joins a global wave of people fighting food waste.",
    itemsRescued: "Items rescued",
    foodSaved: "Food saved",
    familiesFed: "Families fed",
    savedPerHousehold: "Saved per household per year"
  },
  faq: {
    label: "❓ FAQ",
    title: "Frequently asked questions.",
    q1: "Is Freshli really free?",
    a1: "Yes. Core features — pantry tracking, expiry alerts, community sharing, and AI Rescue Chef — are completely free. Freshli Pro is an optional subscription for power users.",
    q2: "Does the AI need internet?",
    a2: "No. Rescue Chef runs entirely on your device using Apple Intelligence. No server calls, no API costs, no data leaving your phone. It works completely offline.",
    q3: "Which devices are supported?",
    a3: "Freshli requires iOS 26 or later. AI Rescue Chef requires Apple Intelligence (iPhone 16 and later). Apple Watch complications require watchOS 26.",
    moreQuestions: "More questions? See Support →"
  },
  cta: {
    title: "Start rescuing<br>food today.",
    subtitle: "Free to download. No account required to start. Your pantry, your privacy, your planet.",
    button: "Download Freshli Free",
    badge1: "iOS 26+",
    badge2: "Apple Watch",
    badge3: "Siri Shortcuts",
    badge4: "Live Activities",
    badge5: "Dark Mode"
  },
  footer: {
    tagline: "For the people. For the planet.",
    ourStory: "Our Story",
    partners: "Partners",
    social: "Social",
    privacy: "Privacy",
    terms: "Terms",
    support: "Support",
    press: "Press",
    contact: "Contact",
    home: "Home",
    rights: "© 2026 Freshli. All rights reserved."
  },
  support: {
    title: "Support",
    intro: "We're here to help. Find answers below or reach out directly — we typically respond within 24 hours.",
    needHelp: "Need help? We've got you.",
    hours: "Our support team is available Monday to Friday, 9am — 6pm GMT.",
    quickHelp: "Quick Help",
    gettingStarted: "Getting Started",
    gettingStartedText: "Download Freshli from the App Store, sign in with Apple, and add your first pantry item.",
    notifications: "Notifications",
    notificationsText: "Enable expiry reminders in Settings to get alerts before your food goes off.",
    rescueChef: "Rescue Chef AI",
    rescueChefText: "Requires Apple Intelligence (iPhone 16+). Tap \"Ask Freshli\" in the Rescue Chef screen.",
    accountPrivacy: "Account & Privacy",
    accountPrivacyText: "Delete your account anytime in Settings. All data is removed within 30 days.",
    faqTitle: "Frequently Asked Questions",
    faq1q: "Is Freshli free?",
    faq1a: "Yes. Freshli is free to download and use. Freshli Pro offers optional premium features via a subscription, but the core pantry tracking, expiry alerts, and community sharing are completely free.",
    faq2q: "Does the AI need internet?",
    faq2a: "No. Rescue Chef uses Apple's on-device FoundationModels framework. Your pantry data is processed entirely on your iPhone — nothing is sent to any server. It works offline.",
    faq3q: "Which devices are supported?",
    faq3a: "Freshli requires iOS 26 or later. The AI Rescue Chef feature requires Apple Intelligence (iPhone 16 and later). Apple Watch complications require watchOS 26.",
    faq4q: "How do I delete my account?",
    faq4a: "Open Freshli → Profile → Settings → scroll to the bottom → Delete Account. All your personal data will be permanently removed from our servers within 30 days.",
    faq5q: "Is my data safe?",
    faq5a: "Yes. Your data is encrypted in transit (TLS 1.3) and at rest (AES-256). We use Row Level Security so only you can access your data. We never sell your data or use third-party trackers. See our Privacy Policy for full details.",
    faq6q: "How do I cancel my subscription?",
    faq6a: "Open your iPhone Settings → tap your name → Subscriptions → Freshli Pro → Cancel Subscription. You'll retain access until the end of the current billing period.",
    faq7q: "Can I share food with neighbours?",
    faq7a: "Yes! Go to the Community tab and tap \"New Post\" to list surplus food for free collection. You can also browse what neighbours are sharing and claim items near you.",
    stillNeedHelp: "Still need help?",
    stillNeedHelpText: "If your question isn't answered above, email us at support@freshli.app with a description of your issue. Include your device model and iOS version so we can help faster.",
    reportBug: "Report a Bug",
    reportBugText: "Found something that doesn't look right? Email support@freshli.app with the subject line \"Bug Report\" and include:",
    bugItem1: "What you were doing when the issue occurred",
    bugItem2: "What you expected to happen vs what actually happened",
    bugItem3: "A screenshot if possible",
    bugItem4: "Your iPhone model and iOS version"
  },
  about: {
    heroTitle: "For the people.<br>For the planet.",
    heroSubtitle: "The story behind Freshli — why we built it, what drives us, and where we're going.",
    problem: "The Problem",
    problemP1: "Every year, <strong>one-third of all food produced globally is wasted</strong> — 1.3 billion tonnes thrown into landfills while 828 million people go hungry. In the UK alone, the average household throws away <strong>£800 of perfectly good food</strong> every year.",
    problemP2: "Food waste isn't just a money problem. When food rots in landfill, it produces methane — a greenhouse gas <strong>80 times more potent than CO²</strong> over 20 years. If food waste were a country, it would be the third-largest greenhouse gas emitter in the world, behind the US and China.",
    problemP3: "The hardest part? Most of this waste happens at home. Not on farms. Not in supermarkets. In our fridges, our cupboards, our kitchens. We buy with good intentions, life gets in the way, and by the time we remember, it's already too late.",
    callout1: "\"The best time to rescue food from the bin was the day before it expired. The second-best time is now.\"",
    story: "Our Story",
    storyP1: "Freshli started from a simple frustration: opening the fridge on a Tuesday night, spotting a forgotten bag of spinach, and realising it had already gone off. That moment — repeated millions of times a day, in millions of kitchens — is where waste begins.",
    storyP2: "We asked: what if your phone could warn you before that moment? What if it could suggest a recipe that uses the spinach, half a pepper, and the eggs that are all expiring this week? What if it could do all of that <strong>without sending your grocery data to a server</strong>?",
    storyP3: "That's Freshli. An app built for iOS 26 that uses Apple's Foundation Models framework to turn the contents of your fridge into meals, not rubbish — entirely on-device, with zero network calls. Private by design. Instant by nature. Useful by default.",
    mission: "Our Mission",
    missionCallout: "To make fighting food waste feel natural, rewarding, and collective — so that rescuing food becomes as automatic as recycling.",
    missionP: "We believe the answer to food waste isn't guilt. It isn't another documentary about landfills. It's making the <em>right thing</em> the <em>easy thing</em>. When your phone tells you what's going off, offers you a 15-minute recipe, and shows you that 347 other people just rescued food too — suddenly, saving that spinach feels like joining a movement, not doing a chore.",
    values: "Our Values",
    value1Title: "Privacy First",
    value1Text: "Your pantry data stays on your device. Our AI runs entirely on-device using Apple Intelligence. No server sees your groceries.",
    value2Title: "Planet Over Profit",
    value2Text: "Every feature we build is measured against one question: does it prevent more food going to landfill? If not, we don't ship it.",
    value3Title: "Community Over Competition",
    value3Text: "Food surplus should go to a neighbour, not a bin. We build tools that bring people together, not isolate them.",
    value4Title: "Accessible to All",
    value4Text: "ARKit eye-tracking for hands-free navigation, voice-guided cooking, full VoiceOver support, Dynamic Type, Reduce Motion, 10 languages. Food waste is everyone's problem — the solution should be too.",
    roadmap: "Our Goals",
    roadmapIntro: "Freshli is just getting started. Here's our roadmap — not just features, but impact milestones we're aiming for:",
    stat1Label: "Items rescued by 2027",
    stat2Label: "CO² avoided",
    stat3Label: "Families using Freshli",
    stat4Label: "Countries reached",
    roadAhead: "The Road Ahead",
    q22026: "App Store Launch",
    q22026Text: "Freshli 1.0 with AI Rescue Chef, hands-free cooking, community marketplace, Live Wave, Weekly Wrap, Apple Watch companion, Liquid Glass design with Metal 4 shaders, and 10-language support.",
    q32026: "Retailer Partnerships",
    q32026Text: "Connect loyalty cards (Tesco, Sainsbury's, Waitrose) to automatically import your grocery shops. One tap and everything's in your pantry.",
    q42026: "Community Fridge Network",
    q42026Text: "Grow from 10 seeded fridges to 500+ verified locations across the UK, Ireland, and Europe. Real-time availability updates.",
    year2027: "City Impact Reports",
    year2027Text: "Aggregate anonymous waste data to give local councils actionable insights about household food waste patterns. Policy informed by data.",
    yearPlus: "Global Expansion",
    yearPlusText: "Localise the app into 20+ languages. Partner with food banks, schools, and community groups worldwide. Make fighting food waste a global norm.",
    joinUs: "Join Us",
    joinUsP1: "Freshli is free to download. No account required to start tracking your pantry. Every item rescued is one fewer in a landfill — and one more reason to believe we can change this, together.",
    joinUsP2: "<strong>For the people. For the planet.</strong>",
    downloadLink: "Download Freshli →",
    partnerLink: "Become a Partner →",
    contactLink: "Contact Us →"
  },
  partners: {
    heroTitle: "Let's fight waste<br>together.",
    heroSubtitle: "Partner with Freshli to reach thousands of eco-conscious households. Sponsor our mission. Donate to keep the app free.",
    whyTitle: "Why partner with Freshli?",
    whyText: "Freshli users are <strong>actively trying to reduce their environmental footprint</strong>. They track their food, cook with what they have, share surplus with neighbours, and measure their CO² impact every week. This is one of the most engaged, values-aligned audiences on the App Store.",
    reach: "Targeted Reach",
    reachText: "Every Freshli user cares about sustainability. Your brand reaches people who actively choose eco-conscious products.",
    impact: "Measurable Impact",
    impactText: "We track food rescued, CO² avoided, and meals shared. Your partnership comes with real, actionable impact metrics.",
    align: "Brand Alignment",
    alignText: "Associate your brand with an inspiring mission. Rescuing food is universally positive — zero controversy, only goodwill.",
    scale: "Global Reach",
    scaleText: "Freshli is available in 10 languages across the biggest App Store markets. One partnership, global visibility.",
    opportunities: "Partnership Opportunities",
    mostImpact: "HIGHEST IMPACT",
    retailer: "Retailer Integration",
    retailerPrice: "For supermarkets and food chains",
    retailerText: "Connect your loyalty programme to Freshli so your customers can auto-import their shops and track food at home.",
    retailerL1: "Loyalty card integration (Tesco, Sainsbury's, Waitrose, etc.)",
    retailerL2: "Recipe suggestions using your products",
    retailerL3: "In-app presence to millions of active users",
    retailerL4: "Shared impact reports for your CSR campaigns",
    getInTouch: "Get in Touch",
    mission: "Mission Sponsor",
    missionPrice: "For brands committed to sustainability",
    missionText: "Sponsor the free version of Freshli so more households can access waste-fighting tools with no paywall.",
    missionL1: "\"Powered by [Your Brand]\" in-app",
    missionL2: "Featured in the Weekly Wrap share card",
    missionL3: "Co-branded impact reports",
    missionL4: "Press coverage as a founding sponsor",
    missionL5: "Priority access to new features",
    becomeSponsor: "Become a Sponsor",
    community: "Community Partner",
    communityPrice: "For food banks, charities, and councils",
    communityText: "Integrate your community fridge network, collection points, or waste reduction programmes into Freshli.",
    communityL1: "In-app listings for your fridges and drop-off points",
    communityL2: "Real-time availability updates from users",
    communityL3: "Anonymous waste data to inform public policy",
    communityL4: "Free — forever — for registered charities",
    partnerWithUs: "Partner With Us",
    sponsor: "Sponsor Freshli",
    sponsorText: "Sponsorship keeps Freshli's core features free for every household. Your support directly funds:",
    sponsorL1: "The community marketplace server infrastructure",
    sponsorL2: "Expanding the community fridge network to new cities",
    sponsorL3: "Localising into more languages so more people can rescue food",
    sponsorL4: "Accessibility improvements for users with disabilities",
    sponsorL5: "School outreach — teaching the next generation about food waste",
    donate: "Donate",
    donateTitle: "Keep Freshli Free for Everyone",
    donateText: "Every donation directly funds food waste reduction — server costs, community fridge network expansion, and keeping the app free.",
    donateKofi: "Support on Ko-fi",
    donateKofiNote: "Powered by Ko-fi — <strong>0% platform fees</strong>. 100% of your donation goes to Freshli.",
    donateOneTime: "☕ One-time tip",
    donateMonthly: "💚 Monthly",
    donateBank: "🏦 Bank transfer",
    donateDisclaimer: "Freshli is not yet a registered charity. Donations are processed as project contributions via Ko-fi (Stripe/PayPal). For a 100% fee-free donation, choose bank transfer — contact us for details. We're working toward charity status.",
    advertise: "Advertise with Freshli",
    advertiseP1: "We offer limited, curated advertising opportunities for brands aligned with our mission. No pop-ups, no tracking, no data selling — just relevant products shown to people who care about sustainability.",
    advertiseAccept: "<strong>What we accept:</strong> eco-conscious food brands, sustainable kitchenware, zero-waste brands, organic grocers, plant-based food companies.",
    advertiseDecline: "<strong>What we decline:</strong> fast food chains, single-use plastic products, anything that contradicts our mission.",
    advertiseContact: "Contact support@freshli.app for our rate card and audience data.",
    ctaTitle: "Ready to make a difference?",
    ctaText: "Whether you're a supermarket, mission-driven brand, food bank, or just someone who wants to help — we'd love to chat."
  },
  press: {
    title: "Press Kit",
    intro: "Everything journalists and creators need to cover Freshli. For press enquiries, contact support@freshli.app.",
    aboutTitle: "About Freshli",
    boilerplate: "Freshli is an iOS app that helps households rescue food from the bin using on-device Apple Intelligence. Users track their pantry, get AI-generated recipes for ingredients nearing expiry (entirely on-device, zero network calls), cook hands-free with voice-guided recipe steps, share surplus food with neighbours, and watch their environmental impact grow week by week. Built with Swift 6.2, SwiftUI, SwiftData, and Metal 4 for iOS 26. For the people. For the planet.",
    keyFacts: "Key Facts",
    fact1: "Download size",
    fact2: "Languages supported",
    fact3: "On-device AI processing",
    fact4: "Third-party trackers",
    fact5: "Average food waste per household per year",
    fact6: "CO² avoided per item rescued",
    differentTitle: "What Makes Freshli Different",
    diff1: "<strong>On-device AI:</strong> Rescue Chef uses iOS 26's FoundationModels framework — recipes are generated entirely on the device. No servers, no API costs, no privacy compromises.",
    diff2: "<strong>Community-first:</strong> share surplus food with neighbours, donate to community fridges, join local circles for hyper-local sharing.",
    diff3: "<strong>Impact you can feel:</strong> the Weekly Wrap — a cinematic, shareable story of your food-rescue impact with animated MeshGradient backgrounds and a growing tree.",
    diff4: "<strong>Hands-free cooking:</strong> Freshli reads each recipe step aloud so users never touch their phone while cooking. Eyes on the pan, not the screen.",
    diff5: "<strong>Eye-tracking accessibility:</strong> ARKit face tracking enables hands-free navigation — UI elements subtly dilate toward the user's gaze. Full WCAG 2.2 AA compliance.",
    diff6: "<strong>Deep platform integration:</strong> Apple Watch, Siri Shortcuts, Control Centre widgets, interactive widgets, Live Activities, Dynamic Island, and ControlWidget quick actions.",
    techTitle: "iOS 26 Technologies Used",
    brandTitle: "Brand Assets",
    appName: "<strong>App Name:</strong> Freshli",
    tagline: "<strong>Tagline:</strong> For the people. For the planet.",
    subtitle: "<strong>Subtitle:</strong> Rescue food. Save the planet.",
    category: "<strong>Category:</strong> Food & Drink (primary), Lifestyle (secondary)",
    colors: "Brand Colors",
    screenshots: "Screenshots",
    screenshotsText: "High-resolution App Store screenshots (1320 × 2868, iPhone 17 Pro Max) are available. Contact support@freshli.app for the complete press kit with framed mockups.",
    contactTitle: "Contact",
    pressEnquiries: "<strong>Press enquiries:</strong>",
    website: "<strong>Website:</strong>",
    appStore: "<strong>App Store:</strong> Available on the App Store (iOS 26+)"
  },
  social: {
    title: "Follow the rescue wave.",
    subtitle: "Live updates, food-rescue tips, community stories, and behind-the-scenes from the Freshli team.",
    liveFrom: "Live from Freshli",
    liveFromText: "See what we're sharing across our channels — tap a platform to view the latest.",
    followInstagram: "Follow on Instagram",
    followInstagramText: "Behind-the-scenes, food-rescue tips, and Weekly Wrap highlights. Follow @freshliapp for your daily inspiration.",
    openInstagram: "Open Instagram →",
    phTitle: "Freshli on Product Hunt",
    phText: "Upvote Freshli on launch day, leave a review, and help us reach the front page. Every vote counts.",
    phLink: "View on Product Hunt →",
    newsletterTitle: "Don't miss the launch.",
    newsletterText: "Follow us on your favourite platform to be first to know when Freshli hits the App Store.",
    newsletterCta: "Follow @everwiseapps on X →"
  },
  privacy: {
    title: "Privacy Policy",
    updated: "Last updated: 12 April 2026",
    highlight: "Your pantry data is processed on your device. Freshli's AI Rescue Chef runs entirely on-device using Apple Intelligence — your food data never leaves your phone.",
    h1: "1. Who We Are",
    p1: "Freshli is operated by Freshli (\"we\", \"us\", \"our\"). This policy explains how we collect, use, and protect your personal information when you use the Freshli iOS app and freshli.app website.",
    contact: "Contact:",
    h2: "2. Information We Collect",
    h21: "2.1 Account Information",
    p21: "When you create an account, we collect:",
    p21a: "<strong>Email address</strong> — for authentication and account recovery",
    p21b: "<strong>Display name</strong> — shown in the community marketplace",
    p21c: "<strong>Apple ID metadata</strong> — if you use Sign in with Apple (name, email relay)",
    h22: "2.2 Pantry Data",
    p22: "Items you add to your pantry (names, quantities, expiry dates, categories, storage locations) are stored:",
    p22a: "<strong>Locally on your device</strong> via SwiftData — always available offline",
    p22b: "<strong>On our servers</strong> (Supabase, EU-West region) — for cross-device sync and backup, encrypted in transit and at rest",
    h23: "2.3 Community Data",
    p23: "If you list surplus food on the community marketplace, your listing details (item name, description, general area) are visible to other users. Your exact address is never shared unless you choose to include pickup details.",
    h24: "2.4 Usage Analytics",
    p24: "We collect anonymous product analytics to improve the app:",
    p24a: "Which features you use (e.g., Rescue Chef, Weekly Wrap) — never the content",
    p24b: "App version, session duration, crash-free rate",
    p24c: "No device identifiers, no advertising IDs, no third-party trackers",
    h25: "2.5 AI Processing",
    p25: "Freshli's Rescue Chef uses Apple's on-device FoundationModels framework. Your pantry contents are processed entirely on your iPhone — they are never sent to our servers, Apple's servers, or any third party for AI processing.",
    h3: "3. How We Use Your Information",
    p3a: "To provide and maintain the Freshli service",
    p3b: "To sync your pantry data across your devices",
    p3c: "To send expiry reminder notifications (with your permission)",
    p3d: "To display your listings in the community marketplace",
    p3e: "To calculate and display your environmental impact (CO2 avoided, money saved)",
    p3f: "To improve the app through anonymous, aggregated analytics",
    p3note: "We <strong>never</strong> sell your personal data to third parties. We <strong>never</strong> use your data for advertising.",
    h4: "4. Data Storage and Security",
    p4a: "Server data is hosted on <strong>Supabase</strong> (EU-West-3 region, AWS infrastructure)",
    p4b: "All data is encrypted in transit (TLS 1.3) and at rest (AES-256)",
    p4c: "Row Level Security (RLS) ensures you can only access your own data",
    p4d: "Passwords are checked against HaveIBeenPwned to prevent use of compromised credentials",
    h5: "5. Data Sharing",
    p5: "We share your data only in these limited circumstances:",
    p5a: "<strong>Community marketplace</strong> — your listing details are visible to other users (you control what you share)",
    p5b: "<strong>Legal requirements</strong> — if required by law, court order, or regulatory authority",
    p5c: "<strong>Service providers</strong> — Supabase (database hosting), Apple (authentication, push notifications) — under strict data processing agreements",
    h6: "6. Your Rights",
    p6: "You have the right to:",
    p6a: "<strong>Access</strong> your data — available in Settings within the app",
    p6b: "<strong>Delete</strong> your account and all associated data — Settings → Delete Account",
    p6c: "<strong>Export</strong> your pantry data — contact support@freshli.app",
    p6d: "<strong>Withdraw consent</strong> for notifications — via iOS Settings",
    p6e: "<strong>Opt out</strong> of analytics — via the app's Settings screen",
    h7: "7. Data Retention",
    p7: "We retain your data for as long as your account is active. If you delete your account, all personal data is permanently removed from our servers within 30 days. Anonymous, aggregated analytics data may be retained indefinitely.",
    h8: "8. Children's Privacy",
    p8: "Freshli is not directed at children under 13. We do not knowingly collect personal information from children. If you believe a child has provided us with personal data, please contact support@freshli.app and we will delete it.",
    h9: "9. Changes to This Policy",
    p9: "We may update this privacy policy from time to time. We will notify you of significant changes through the app or by email. The \"Last updated\" date at the top of this page indicates the most recent revision.",
    h10: "10. Contact Us",
    p10: "If you have questions about this privacy policy or your data, contact us at:",
    email: "<strong>Email:</strong>"
  },
  terms: {
    title: "Terms of Service",
    updated: "Last updated: 12 April 2026 · End User License Agreement (EULA)",
    h1: "1. Acceptance of Terms",
    p1: "By downloading, installing, or using the Freshli application (\"App\"), you agree to be bound by these Terms of Service (\"Terms\"). If you do not agree to these Terms, do not use the App.",
    h2: "2. License",
    p2: "Freshli grants you a limited, non-exclusive, non-transferable, revocable license to use the App on any Apple device that you own or control, subject to the Apple Media Services Terms and Conditions. This license does not allow you to:",
    p2a: "Redistribute, sublicense, or sell the App",
    p2b: "Reverse-engineer, decompile, or disassemble the App",
    p2c: "Use the App for any unlawful purpose",
    p2d: "Interfere with or disrupt the App's servers or networks",
    h3: "3. Account",
    p3: "You may create an account using email/password or Sign in with Apple. You are responsible for maintaining the confidentiality of your credentials and for all activity under your account. You must be at least 13 years old to create an account.",
    h4: "4. User Content",
    p4: "You retain ownership of all content you create in the App (pantry items, listings, reviews). By posting content to the community marketplace, you grant Freshli a non-exclusive, worldwide license to display that content to other users for the purpose of operating the marketplace.",
    p4note: "You agree not to post content that is:",
    p4a: "False, misleading, or fraudulent",
    p4b: "Harmful, abusive, harassing, or discriminatory",
    p4c: "In violation of any law or regulation",
    p4d: "Infringing on any intellectual property rights",
    h5: "5. Community Marketplace",
    p5: "The community marketplace enables users to share surplus food with neighbours. Freshli acts as a platform and is not a party to any transaction between users. Freshli does not guarantee the quality, safety, or legality of listed items. Users share and collect food at their own risk.",
    h6: "6. Subscriptions",
    p6: "Freshli offers optional premium features through auto-renewable subscriptions (\"Freshli Pro\"). Subscriptions are billed through your Apple ID account. Payment is charged at confirmation of purchase. Subscriptions automatically renew unless cancelled at least 24 hours before the end of the current period. You can manage or cancel subscriptions in your iPhone's Settings → Apple ID → Subscriptions.",
    h7: "7. AI Features",
    p7: "Freshli's Rescue Chef uses Apple's on-device FoundationModels framework to generate recipe suggestions. AI-generated content is provided for informational purposes only and should not be treated as professional dietary, nutritional, or medical advice. Always use your own judgement regarding food safety.",
    h8: "8. Food Safety Disclaimer",
    p8: "<strong>Freshli provides expiry tracking as a convenience tool. Freshli does not guarantee the safety or edibility of any food item.</strong> Expiry dates entered by users may be inaccurate. Always inspect food carefully before consumption. Freshli is not liable for any illness, injury, or loss resulting from the consumption of food tracked or shared through the App.",
    h9: "9. Intellectual Property",
    p9: "The App, including its design, code, branding, and content (excluding user content), is owned by Freshli and protected by copyright, trademark, and other intellectual property laws. The Freshli name, logo, and \"For the people. For the planet.\" tagline are trademarks of Freshli.",
    h10: "10. Limitation of Liability",
    p10: "To the maximum extent permitted by applicable law, Freshli shall not be liable for any indirect, incidental, special, consequential, or punitive damages, including loss of profits, data, or goodwill, arising from your use of the App. Freshli's total liability shall not exceed the amount you paid for the App in the 12 months preceding the claim.",
    h11: "11. Termination",
    p11: "We may suspend or terminate your account if you violate these Terms. You may delete your account at any time through the App's Settings. Upon termination, your right to use the App ceases immediately, and your data will be deleted in accordance with our Privacy Policy.",
    h12: "12. Changes to Terms",
    p12: "We may update these Terms from time to time. Continued use of the App after changes constitutes acceptance of the new Terms. We will notify you of material changes through the App.",
    h13: "13. Apple-Specific Terms",
    p13: "These Terms are between you and Freshli, not Apple. Apple has no obligation to furnish maintenance or support. In the event of any failure to conform to an applicable warranty, you may notify Apple for a refund of the purchase price (if any); Apple has no other warranty obligation. Apple is not responsible for addressing any claims relating to the App. Apple is a third-party beneficiary of these Terms.",
    h14: "14. Governing Law",
    p14: "These Terms are governed by the laws of England and Wales. Any disputes shall be resolved in the courts of England and Wales.",
    h15: "15. Contact",
    p15: "Questions about these Terms? Contact us at support@freshli.app."
  }
};
