window.__freshliTranslations = window.__freshliTranslations || {};
window.__freshliTranslations.es = {
  nav: {
    features: "Funciones",
    impact: "Impacto",
    support: "Soporte",
    downloadFree: "Descargar gratis",
    backHome: "← Volver al inicio",
    language: "Idioma"
  },
  hero: {
    title: `Tu comida.<br>Tu <span class="green">impacto.</span>`,
    subtitle: "Freshli usa Apple Intelligence en el dispositivo para rescatar los alimentos a punto de caducar: privado, instantáneo y sin necesidad de internet. Por las personas. Por el planeta.",
    ctaDownload: "Descargar en App Store",
    ctaFeatures: "Ver funciones ↓",
    badgeAI: "🤖 Apple Intelligence",
    badgeOnDevice: "🔒 100% en el dispositivo",
    badgeLanguages: "🌍 10 idiomas"
  },
  how: {
    label: "🚀 Cómo funciona",
    title: `Tres pasos para<br>cero desperdicio de alimentos.`,
    step1Title: "Añade tus alimentos",
    step1Text: "Escanea un código de barras, fotografía un ticket o escribe manualmente. En 5 segundos.",
    step2Title: "Recibe alertas inteligentes",
    step2Text: "Freshli te avisa de lo que está por caducar y te sugiere recetas con IA para aprovecharlo.",
    step3Title: "Rescata o comparte",
    step3Text: "Cocínalo, compártelo con tus vecinos o dónalo a una nevera comunitaria."
  },
  features: {
    label: "✨ Funciones",
    title: `Todo lo que necesitas para<br>dejar de desperdiciar comida.`,
    subtitle: "Registra, rescata, comparte y celebra: todo desde una app preciosa pensada para quienes cuidan el planeta.",
    rescueChef: {
      title: "Rescue Chef IA",
      text: "Pulsa un botón y Apple Intelligence crea recetas con los ingredientes exactos de tu despensa. En el dispositivo, privado, sin internet."
    },
    expiry: {
      title: "Seguimiento inteligente de caducidad",
      text: "Escanea códigos de barras, tickets o escribe manualmente. Las etiquetas de colores te muestran de un vistazo qué consumir primero."
    },
    community: {
      title: "Comunidad para compartir",
      text: "Publica alimentos sobrantes para que los recojan tus vecinos gratis. Encuentra neveras comunitarias. Únete a grupos locales para compartir a nivel hiperlocal."
    },
    wrap: {
      title: "Resumen Semanal",
      text: "Un recap cinematográfico de tu historia de rescate: productos salvados, CO₂ evitado, dinero ahorrado. Listo para compartir en Instagram Stories."
    },
    watch: {
      title: "Apple Watch y widgets",
      text: "Alertas de caducidad en tu muñeca. Widgets interactivos con consumo en un solo toque. Live Activities en la pantalla de bloqueo."
    },
    siri: {
      title: `"Oye Siri, rescata mi despensa"`,
      text: "Recetas con IA activadas por voz desde Siri, Atajos, Spotlight o Centro de Control. Cero toques necesarios."
    },
    handsfree: {
      title: "Cocina sin manos",
      text: "Freshli lee cada paso de la receta en voz alta para que nunca toques el teléfono mientras cocinas. La mirada en la sartén, no en la pantalla."
    },
    wave: {
      title: "Live Wave",
      text: "Observa el impacto global en tiempo real: cuánta gente está rescatando comida ahora mismo, el CO₂ total evitado y las comidas compartidas por todo el mundo."
    }
  },
  testimonial: {
    quote: "Tiraba al menos £15 de comida a la semana. Con Freshli, llevo tres semanas sin tirar ni un solo producto. Las recetas con IA son realmente útiles.",
    author: "— Sarah K., Londres"
  },
  ai: {
    label: "🧠 Apple Intelligence",
    title: `Los datos de tu despensa<br>nunca salen de tu teléfono.`,
    subtitle: "El Rescue Chef de Freshli funciona totalmente en el dispositivo usando el framework FoundationModels de iOS 26. Sin servidores, sin costes de API, sin compromisos con tu privacidad. Tu nevera es asunto tuyo."
  },
  impact: {
    label: "🌍 Impacto global",
    title: `Juntos estamos construyendo<br>un mundo sin desperdicio.`,
    subtitle: "Cada producto que rescatas se suma a una ola global de personas que luchan contra el desperdicio de alimentos.",
    itemsRescued: "Productos rescatados",
    foodSaved: "Comida salvada",
    familiesFed: "Familias alimentadas",
    savedPerHousehold: "Ahorrado por hogar/año"
  },
  faq: {
    label: "❓ Preguntas frecuentes",
    title: "Preguntas habituales.",
    q1: "¿Freshli es realmente gratis?",
    a1: "Sí. Las funciones esenciales — seguimiento de la despensa, alertas de caducidad, comunidad para compartir y Rescue Chef IA — son totalmente gratuitas. Freshli Pro es una suscripción opcional para usuarios avanzados.",
    q2: "¿La IA necesita internet?",
    a2: "No. Rescue Chef funciona íntegramente en tu dispositivo usando Apple Intelligence. Sin llamadas a servidores, sin costes de API, sin datos que salgan de tu teléfono. Funciona totalmente sin conexión.",
    q3: "¿Qué dispositivos son compatibles?",
    a3: "Freshli requiere iOS 26 o posterior. Rescue Chef IA necesita Apple Intelligence (iPhone 16 o superior). Las complicaciones del Apple Watch requieren watchOS 26.",
    moreQuestions: "¿Más preguntas? Visita Soporte →"
  },
  cta: {
    title: `Empieza a rescatar<br>comida hoy.`,
    subtitle: "Descarga gratis. No necesitas cuenta para empezar. Tu despensa, tu privacidad, tu planeta.",
    button: "Descargar Freshli gratis",
    badge1: "iOS 26+",
    badge2: "Apple Watch",
    badge3: "Atajos de Siri",
    badge4: "Live Activities",
    badge5: "Modo oscuro"
  },
  footer: {
    tagline: "Por las personas. Por el planeta.",
    ourStory: "Nuestra historia",
    partners: "Colaboradores",
    social: "Redes sociales",
    privacy: "Política de privacidad",
    terms: "Términos del servicio",
    support: "Soporte",
    press: "Kit de prensa",
    contact: "Contacto",
    home: "Inicio",
    rights: "© 2026 Freshli. Todos los derechos reservados."
  },
  support: {
    title: "Soporte",
    intro: "Estamos aquí para ayudarte. Encuentra respuestas abajo o contáctanos directamente: normalmente respondemos en menos de 24 horas.",
    needHelp: "¿Necesitas ayuda? Te cubrimos.",
    hours: "Nuestro equipo de soporte está disponible de lunes a viernes, de 9:00 a 18:00 GMT.",
    quickHelp: "Ayuda rápida",
    gettingStarted: "Primeros pasos",
    gettingStartedText: "Descarga Freshli desde la App Store, inicia sesión con Apple y añade tu primer producto a la despensa.",
    notifications: "Notificaciones",
    notificationsText: "Activa los recordatorios de caducidad en Ajustes para recibir alertas antes de que tu comida se estropee.",
    rescueChef: "Rescue Chef IA",
    rescueChefText: `Requiere Apple Intelligence (iPhone 16 o superior). Pulsa "Preguntar a Freshli" en la pantalla de Rescue Chef.`,
    accountPrivacy: "Cuenta y privacidad",
    accountPrivacyText: "Elimina tu cuenta cuando quieras desde Ajustes. Todos los datos se borran en un plazo de 30 días.",
    faqTitle: "Preguntas frecuentes",
    faq1q: "¿Freshli es gratis?",
    faq1a: "Sí. Freshli es gratis para descargar y usar. Freshli Pro ofrece funciones premium opcionales mediante suscripción, pero el seguimiento de despensa, las alertas de caducidad y la comunidad para compartir son totalmente gratuitos.",
    faq2q: "¿La IA necesita internet?",
    faq2a: "No. Rescue Chef usa el framework FoundationModels en el dispositivo de Apple. Los datos de tu despensa se procesan íntegramente en tu iPhone: nada se envía a ningún servidor. Funciona sin conexión.",
    faq3q: "¿Qué dispositivos son compatibles?",
    faq3a: "Freshli requiere iOS 26 o posterior. La función Rescue Chef IA requiere Apple Intelligence (iPhone 16 o posterior). Las complicaciones del Apple Watch requieren watchOS 26.",
    faq4q: "¿Cómo elimino mi cuenta?",
    faq4a: "Abre Freshli → Perfil → Ajustes → desplázate hasta el final → Eliminar cuenta. Todos tus datos personales se eliminarán permanentemente de nuestros servidores en un plazo de 30 días.",
    faq5q: "¿Están seguros mis datos?",
    faq5a: "Sí. Tus datos se cifran en tránsito (TLS 1.3) y en reposo (AES-256). Usamos Row Level Security para que solo tú puedas acceder a tus datos. Nunca vendemos tus datos ni usamos rastreadores de terceros. Consulta nuestra Política de Privacidad para todos los detalles.",
    faq6q: "¿Cómo cancelo mi suscripción?",
    faq6a: "Abre los Ajustes de tu iPhone → toca tu nombre → Suscripciones → Freshli Pro → Cancelar suscripción. Mantendrás el acceso hasta el final del periodo de facturación actual.",
    faq7q: "¿Puedo compartir comida con mis vecinos?",
    faq7a: `¡Sí! Ve a la pestaña Comunidad y pulsa "Nueva publicación" para ofrecer alimentos sobrantes de forma gratuita. También puedes ver lo que comparten tus vecinos y reservar productos cerca de ti.`,
    stillNeedHelp: "¿Aún necesitas ayuda?",
    stillNeedHelpText: "Si tu pregunta no está resuelta arriba, escríbenos a support@freshli.app describiendo tu problema. Incluye el modelo del dispositivo y la versión de iOS para ayudarte más rápido.",
    reportBug: "Reportar un error",
    reportBugText: `¿Has encontrado algo que no funciona bien? Escríbenos a support@freshli.app con el asunto "Bug Report" e incluye:`,
    bugItem1: "Qué estabas haciendo cuando ocurrió el problema",
    bugItem2: "Qué esperabas que pasara frente a lo que realmente sucedió",
    bugItem3: "Una captura de pantalla si es posible",
    bugItem4: "Tu modelo de iPhone y versión de iOS"
  },
  about: {
    heroTitle: `Por las personas.<br>Por el planeta.`,
    heroSubtitle: "La historia de por qué creamos Freshli, qué nos mueve y hacia dónde vamos.",
    problem: "El problema",
    problemP1: "Cada año se desperdicia <strong>un tercio de toda la comida producida en el mundo</strong>: 1.300 millones de toneladas que acaban en vertederos mientras 828 millones de personas pasan hambre. Solo en Reino Unido, cada hogar tira de media <strong>£700 de comida perfectamente buena</strong> al año.",
    problemP2: "El desperdicio de alimentos no es solo un problema económico. Cuando la comida se descompone en un vertedero, produce metano — un gas de efecto invernadero <strong>80 veces más potente que el CO²</strong> a lo largo de 20 años. Si el desperdicio de alimentos fuera un país, sería el tercer mayor emisor de gases de efecto invernadero del mundo, solo por detrás de EE. UU. y China.",
    problemP3: "¿Lo más difícil? La mayor parte de este desperdicio ocurre en casa. No en las granjas. Ni en los supermercados. En nuestras neveras, alacenas y cocinas. Compramos comida con buenas intenciones, la vida se complica y, cuando nos acordamos, ya es demasiado tarde.",
    callout1: `"El mejor momento para salvar un alimento del cubo es el día antes de que caduque. El segundo mejor momento es ahora mismo."`,
    story: "Nuestra historia",
    storyP1: "Freshli nació de una frustración sencilla: abrir la nevera un martes por la noche, ver una bolsa de espinacas olvidada y darte cuenta de que ya está pasada. Ese momento — repetido millones de veces al día, en millones de cocinas — es donde empieza el desperdicio alimentario.",
    storyP2: "Nos preguntamos: ¿y si tu teléfono pudiera avisarte antes de ese momento? ¿Y si pudiera sugerirte una receta que use las espinacas, medio pimiento y los huevos que caducan esta semana? ¿Y si pudiera hacer todo esto <strong>sin enviar los datos de tu compra a un servidor</strong>?",
    storyP3: "Eso es Freshli. Una app creada para iOS 26 que usa el framework Foundation Models de Apple para convertir el contenido de tu nevera en comidas, no en basura — todo en el dispositivo, con cero llamadas a la red. Privada por diseño. Instantánea por naturaleza. Útil por defecto.",
    mission: "Nuestra misión",
    missionCallout: "Hacer que evitar el desperdicio de alimentos se sienta sencillo, gratificante y comunitario — para que rescatar comida sea un hábito tan natural como reciclar.",
    missionP: "Creemos que la solución al desperdicio de alimentos no es la culpa. No es otro documental sobre vertederos. Es hacer que <em>lo correcto</em> sea <em>lo fácil</em>. Cuando tu teléfono te avisa de lo que va a caducar, te sugiere una receta de 15 minutos y te muestra que otras 347 personas acaban de rescatar comida — de repente, salvar esas espinacas se siente como unirse a un movimiento, no como una tarea.",
    values: "Nuestros valores",
    value1Title: "Privacidad ante todo",
    value1Text: "Los datos de tu despensa se procesan en tu dispositivo. Nuestra IA funciona íntegramente en el dispositivo con Apple Intelligence. Ningún servidor ve tu compra.",
    value2Title: "El planeta antes que el beneficio",
    value2Text: "Cada función que creamos se mide con una sola métrica: ¿evita que más comida llegue al vertedero? Si no, no la lanzamos.",
    value3Title: "Comunidad antes que competencia",
    value3Text: "La comida sobrante debe ir a un vecino, no al cubo. Creamos herramientas que conectan a las personas, no que las aíslan.",
    value4Title: "Accesible para todos",
    value4Text: "Seguimiento de la mirada con ARKit para navegar sin manos, cocina guiada por voz, soporte completo de VoiceOver, Dynamic Type, Reducir movimiento, 10 idiomas. El desperdicio de alimentos es problema de todos — la solución también debe serlo.",
    roadmap: "Hacia dónde vamos",
    roadmapIntro: "Freshli acaba de empezar. Esta es nuestra hoja de ruta — no solo funciones, sino los hitos de impacto que perseguimos:",
    stat1Label: "Productos rescatados para 2027",
    stat2Label: "CO² evitado",
    stat3Label: "Familias usando Freshli",
    stat4Label: "Países alcanzados",
    roadAhead: "El camino por delante",
    q22026: "Lanzamiento en la App Store",
    q22026Text: "Freshli 1.0 con Rescue Chef IA, cocina sin manos, marketplace comunitario, Live Wave, Resumen Semanal, compañero para Apple Watch, diseño Liquid Glass con shaders de Metal 4 y soporte en 10 idiomas.",
    q32026: "Alianzas con supermercados",
    q32026Text: "Conecta tarjetas de fidelidad (Tesco Clubcard, Nectar, etc.) para importar compras automáticamente. Un toque para añadir todo a tu despensa.",
    q42026: "Red de neveras comunitarias",
    q42026Text: "Ampliar de 10 neveras iniciales a más de 500 ubicaciones verificadas en Reino Unido, Irlanda y Europa. Actualizaciones de disponibilidad en tiempo real.",
    year2027: "Informes de impacto para ayuntamientos",
    year2027Text: "Agregamos datos anonimizados de desperdicio para dar a los ayuntamientos información accionable sobre patrones de desperdicio alimentario doméstico. Políticas basadas en datos.",
    yearPlus: "Expansión global",
    yearPlusText: "Localización a más de 20 idiomas. Alianzas con bancos de alimentos, escuelas y organizaciones comunitarias de todo el mundo. Convertir el rescate de alimentos en una norma global.",
    joinUs: "Únete a nosotros",
    joinUsP1: "Freshli es gratis para descargar. No necesitas una cuenta para empezar a registrar tu despensa. Cada producto que rescatas es uno menos en un vertedero — y una razón más para creer que podemos solucionar esto, juntos.",
    joinUsP2: "<strong>Por las personas. Por el planeta.</strong>",
    downloadLink: "Descargar Freshli →",
    partnerLink: "Colabora con nosotros →",
    contactLink: "Ponte en contacto →"
  },
  partners: {
    heroTitle: `Luchemos contra el desperdicio<br>juntos.`,
    heroSubtitle: "Colabora con Freshli para llegar a miles de hogares concienciados con el medio ambiente. Patrocina nuestra misión. Dona para mantener la app gratis.",
    whyTitle: "¿Por qué colaborar con Freshli?",
    whyText: "Los usuarios de Freshli <strong>buscan activamente reducir su huella ambiental</strong>. Registran su comida, cocinan con lo que tienen, comparten excedentes con sus vecinos y miden su impacto en CO² cada semana. Es una de las audiencias más comprometidas y alineadas con valores en la App Store.",
    reach: "Alcance segmentado",
    reachText: "Cada usuario de Freshli valora la sostenibilidad. Tu marca llega a personas que eligen activamente productos ecológicos.",
    impact: "Impacto medible",
    impactText: "Medimos los productos rescatados, el CO² evitado y las comidas compartidas. Tu colaboración incluye métricas de impacto reales y reportables.",
    align: "Alineación de marca",
    alignText: "Asocia tu marca con una misión con la que la gente se siente bien. El rescate de alimentos es universalmente positivo — sin polémica, pura buena voluntad.",
    scale: "Escala global",
    scaleText: "Freshli está disponible en 10 idiomas en los mayores mercados de la App Store. Una sola colaboración, visibilidad global.",
    opportunities: "Oportunidades de colaboración",
    mostImpact: "MÁXIMO IMPACTO",
    retailer: "Integración con retailers",
    retailerPrice: "Para supermercados y cadenas de alimentación",
    retailerText: "Conecta tu programa de fidelización con Freshli para que los clientes importen sus compras automáticamente y registren sus alimentos en casa.",
    retailerL1: "Integración con tarjetas de fidelidad (Clubcard, Nectar, etc.)",
    retailerL2: "Sugerencias de recetas con tus productos",
    retailerL3: "Presencia en la app para millones de usuarios activos",
    retailerL4: "Informes de impacto compartidos para campañas de RSC",
    getInTouch: "Contáctanos",
    mission: "Patrocinador de la misión",
    missionPrice: "Para marcas alineadas con la sostenibilidad",
    missionText: "Patrocina el nivel gratuito de Freshli para que más hogares accedan a herramientas de rescate alimentario sin barreras de pago.",
    missionL1: `"Patrocinado por [Tu marca]" en la app`,
    missionL2: "Destacado en la tarjeta del Resumen Semanal",
    missionL3: "Informes de impacto co-marca",
    missionL4: "Cobertura de prensa como patrocinador fundador",
    missionL5: "Acceso prioritario a nuevas funciones",
    becomeSponsor: "Conviértete en patrocinador",
    community: "Socio comunitario",
    communityPrice: "Para bancos de alimentos, ONG y ayuntamientos",
    communityText: "Integra tu red de neveras comunitarias, puntos de bancos de alimentos o programas de reducción de residuos en Freshli.",
    communityL1: "Lista tus neveras/puntos de entrega en la app",
    communityL2: "Actualizaciones de disponibilidad en tiempo real por parte de los usuarios",
    communityL3: "Datos anonimizados de desperdicio para análisis de políticas",
    communityL4: "Gratis — siempre, para organizaciones sin ánimo de lucro",
    partnerWithUs: "Colabora con nosotros",
    sponsor: "Patrocina Freshli",
    sponsorText: "El patrocinio mantiene las funciones esenciales de Freshli gratis para cada hogar. Tu apoyo financia directamente:",
    sponsorL1: "Infraestructura de servidores para el marketplace comunitario",
    sponsorL2: "Ampliación de la red de neveras comunitarias a nuevas ciudades",
    sponsorL3: "Localización a más idiomas para que más personas puedan rescatar comida",
    sponsorL4: "Mejoras de accesibilidad para usuarios con discapacidad",
    sponsorL5: "Programas educativos en escuelas — enseñando a la próxima generación sobre el desperdicio alimentario",
    donate: "Donar",
    donateTitle: "Mantén Freshli gratis para todos",
    donateText: "Cada donación va directamente a combatir el desperdicio alimentario — costes de servidores, expansión de la red de neveras y mantener la app gratis.",
    donateKofi: "Apóyanos en Ko-fi",
    donateKofiNote: "Impulsado por Ko-fi — <strong>0% de comisión</strong>. El 100% de tu donación llega a Freshli.",
    donateOneTime: "☕ Única vez",
    donateMonthly: "💚 Mensual",
    donateBank: "🏦 Transferencia bancaria",
    donateDisclaimer: "Freshli aún no es una organización benéfica registrada. Las donaciones se procesan como aportaciones al proyecto a través de Ko-fi (Stripe/PayPal). Para donaciones 100% sin comisiones, elige la transferencia bancaria — escríbenos para más detalles. Estamos trabajando para obtener el estatus benéfico.",
    advertise: "Anúnciate con Freshli",
    advertiseP1: "Ofrecemos oportunidades publicitarias limitadas y con buen gusto para marcas alineadas con nuestra misión. Sin pop-ups, sin rastreo, sin venta de datos — solo productos relevantes mostrados a personas que valoran la sostenibilidad.",
    advertiseAccept: "<strong>Lo que aceptamos:</strong> marcas de alimentación ecológica, productos de cocina sostenibles, marcas de estilo de vida zero-waste, tiendas orgánicas, empresas veganas.",
    advertiseDecline: "<strong>Lo que no:</strong> cadenas de comida rápida, productos de plástico de un solo uso, cualquier cosa que contradiga nuestra misión.",
    advertiseContact: "Escribe a support@freshli.app para nuestro rate card y datos demográficos de audiencia.",
    ctaTitle: "¿Listo para generar impacto?",
    ctaText: "Seas un supermercado, una marca sostenible, un banco de alimentos o alguien que quiera ayudar — nos encantará saber de ti."
  },
  press: {
    title: "Kit de prensa",
    intro: "Todo lo que periodistas y creadores necesitan para cubrir Freshli. Para consultas de prensa, escribe a support@freshli.app.",
    aboutTitle: "Sobre Freshli",
    boilerplate: "Freshli es una app para iOS que ayuda a los hogares a rescatar comida del cubo usando Apple Intelligence en el dispositivo. Los usuarios registran su despensa, obtienen recetas generadas por IA para ingredientes a punto de caducar (íntegramente en el dispositivo, con cero llamadas a la red), cocinan sin manos con pasos de receta guiados por voz, comparten excedentes con sus vecinos y ven crecer su impacto ambiental semana a semana. Creada con Swift 6.2, SwiftUI, SwiftData y Metal 4 para iOS 26. Por las personas. Por el planeta.",
    keyFacts: "Datos clave",
    fact1: "Tamaño de descarga",
    fact2: "Idiomas disponibles",
    fact3: "Procesamiento de IA en el dispositivo",
    fact4: "Rastreadores de terceros",
    fact5: "Desperdicio medio de comida/hogar/año",
    fact6: "CO² evitado por producto rescatado",
    differentTitle: "Qué hace diferente a Freshli",
    diff1: "<strong>IA en el dispositivo:</strong> Rescue Chef usa el framework FoundationModels de iOS 26 — las recetas se generan íntegramente en el dispositivo. Sin servidor, sin coste de API, sin comprometer la privacidad.",
    diff2: "<strong>La comunidad primero:</strong> comparte excedentes con los vecinos, dona a neveras comunitarias, únete a grupos locales para compartir a nivel hiperlocal.",
    diff3: "<strong>Impacto que se siente:</strong> Resumen Semanal — una historia cinematográfica y compartible de tu impacto en el rescate de alimentos con fondos animados MeshGradient y un árbol que crece.",
    diff4: "<strong>Cocina sin manos:</strong> Freshli lee cada paso de la receta en voz alta para que nunca toques el teléfono mientras cocinas. La mirada en la sartén, no en la pantalla.",
    diff5: "<strong>Accesibilidad con seguimiento de la mirada:</strong> el seguimiento facial con ARKit permite navegar sin manos — los elementos de la UI se inflan sutilmente hacia la mirada del usuario. Cumplimiento total WCAG 2.2 AA.",
    diff6: "<strong>Integración profunda con la plataforma:</strong> Apple Watch, Atajos de Siri, widgets del Centro de Control, Widgets Interactivos, Live Activities, Dynamic Island y acciones rápidas con ControlWidget.",
    techTitle: "Tecnologías de iOS 26 utilizadas",
    brandTitle: "Recursos de marca",
    appName: "<strong>Nombre de la app:</strong> Freshli",
    tagline: "<strong>Lema:</strong> Por las personas. Por el planeta.",
    subtitle: "<strong>Subtítulo:</strong> Rescata comida. Salva el planeta.",
    category: "<strong>Categoría:</strong> Comida y bebida (primaria), Estilo de vida (secundaria)",
    colors: "Colores de marca",
    screenshots: "Capturas de pantalla",
    screenshotsText: "Hay disponibles capturas de la App Store en alta resolución (1320 × 2868, iPhone 17 Pro Max). Escribe a support@freshli.app para el kit de prensa completo con mockups con marco de dispositivo.",
    contactTitle: "Contacto",
    pressEnquiries: "<strong>Consultas de prensa:</strong>",
    website: "<strong>Sitio web:</strong>",
    appStore: "<strong>App Store:</strong> disponible en la App Store (iOS 26+)"
  },
  social: {
    title: "Sigue la ola del rescate.",
    subtitle: "Actualizaciones en vivo, consejos de rescate alimentario, historias de la comunidad y entre bastidores del equipo de Freshli.",
    liveFrom: "En directo desde Freshli",
    liveFromText: "Mira lo que compartimos en nuestros canales — pulsa una plataforma para ver lo último.",
    followInstagram: "Síguenos en Instagram",
    followInstagramText: "Entre bastidores, consejos de rescate y lo mejor del Resumen Semanal. Sigue a @freshliapp para inspiración diaria.",
    openInstagram: "Abrir Instagram →",
    phTitle: "Freshli en Product Hunt",
    phText: "Vota Freshli cuando lancemos, deja una reseña y ayúdanos a llegar a la portada. Cada voto cuenta.",
    phLink: "Ver en Product Hunt →",
    newsletterTitle: "No te pierdas el lanzamiento.",
    newsletterText: "Síguenos en tu plataforma favorita para ser de los primeros en saber cuándo Freshli llega a la App Store.",
    newsletterCta: "Sigue a @everwiseapps en X →"
  },
  privacy: {
    title: "Política de privacidad",
    updated: "Última actualización: 12 de abril de 2026",
    highlight: "Los datos de tu despensa se procesan en tu dispositivo. El Rescue Chef IA de Freshli funciona íntegramente en el dispositivo con Apple Intelligence — los datos de tu comida nunca salen de tu teléfono.",
    h1: "1. Quiénes somos",
    p1: `Freshli está operado por Freshli ("nosotros", "nos", "nuestro"). Esta política explica cómo recopilamos, usamos y protegemos tu información personal cuando usas la app de Freshli para iOS y la web freshli.app.`,
    contact: "Contacto:",
    h2: "2. Información que recopilamos",
    h21: "2.1 Información de la cuenta",
    p21: "Cuando creas una cuenta, recopilamos:",
    p21a: "<strong>Dirección de correo electrónico</strong> — para autenticación y recuperación de cuenta",
    p21b: "<strong>Nombre visible</strong> — mostrado en el marketplace comunitario",
    p21c: "<strong>Metadatos de Apple ID</strong> — si usas Iniciar sesión con Apple (nombre, email relay)",
    h22: "2.2 Datos de la despensa",
    p22: "Los productos que añades a tu despensa (nombres, cantidades, fechas de caducidad, categorías, ubicaciones de almacenamiento) se guardan:",
    p22a: "<strong>Localmente en tu dispositivo</strong> mediante SwiftData — siempre disponibles sin conexión",
    p22b: "<strong>En nuestros servidores</strong> (Supabase, región UE-Oeste) — para sincronización entre dispositivos y copia de seguridad, cifrados en tránsito y en reposo",
    h23: "2.3 Datos de la comunidad",
    p23: "Si publicas alimentos sobrantes en el marketplace comunitario, los detalles de tu publicación (nombre del producto, descripción, zona aproximada) son visibles para otros usuarios. Tu dirección exacta nunca se comparte a menos que decidas incluir los detalles de recogida.",
    h24: "2.4 Analíticas de uso",
    p24: "Recopilamos analíticas de producto anónimas para mejorar la app:",
    p24a: "Qué funciones usas (por ejemplo, Rescue Chef, Resumen Semanal) — nunca el contenido",
    p24b: "Versión de la app, duración de la sesión, tasa sin fallos",
    p24c: "Sin identificadores de dispositivo, sin IDs de publicidad, sin rastreadores de terceros",
    h25: "2.5 Procesamiento de IA",
    p25: "El Rescue Chef de Freshli usa el framework FoundationModels en el dispositivo de Apple. El contenido de tu despensa se procesa íntegramente en tu iPhone — nunca se envía a nuestros servidores, a los servidores de Apple ni a terceros para procesamiento de IA.",
    h3: "3. Cómo usamos tu información",
    p3a: "Para proporcionar y mantener el servicio Freshli",
    p3b: "Para sincronizar los datos de tu despensa entre tus dispositivos",
    p3c: "Para enviar notificaciones de recordatorio de caducidad (con tu permiso)",
    p3d: "Para mostrar tus publicaciones en el marketplace comunitario",
    p3e: "Para calcular y mostrar tu impacto ambiental (CO2 evitado, dinero ahorrado)",
    p3f: "Para mejorar la app mediante analíticas anónimas y agregadas",
    p3note: "<strong>Nunca</strong> vendemos tus datos personales a terceros. <strong>Nunca</strong> usamos tus datos con fines publicitarios.",
    h4: "4. Almacenamiento y seguridad de los datos",
    p4a: "Los datos del servidor se alojan en <strong>Supabase</strong> (región UE-Oeste-3, infraestructura AWS)",
    p4b: "Todos los datos están cifrados en tránsito (TLS 1.3) y en reposo (AES-256)",
    p4c: "Row Level Security (RLS) asegura que solo tú puedas acceder a tus datos",
    p4d: "Las contraseñas se comprueban contra HaveIBeenPwned para evitar el uso de credenciales comprometidas",
    h5: "5. Compartición de datos",
    p5: "Solo compartimos tus datos en estas circunstancias limitadas:",
    p5a: "<strong>Marketplace comunitario</strong> — los detalles de tu publicación son visibles para otros usuarios (tú decides qué compartes)",
    p5b: "<strong>Requisitos legales</strong> — si lo exige la ley, una orden judicial o una autoridad reguladora",
    p5c: "<strong>Proveedores de servicios</strong> — Supabase (alojamiento de base de datos), Apple (autenticación, notificaciones push) — bajo estrictos acuerdos de procesamiento de datos",
    h6: "6. Tus derechos",
    p6: "Tienes derecho a:",
    p6a: "<strong>Acceder</strong> a tus datos — disponible en Ajustes dentro de la app",
    p6b: "<strong>Eliminar</strong> tu cuenta y todos los datos asociados — Ajustes → Eliminar cuenta",
    p6c: "<strong>Exportar</strong> los datos de tu despensa — escribe a support@freshli.app",
    p6d: "<strong>Retirar el consentimiento</strong> para notificaciones — desde los Ajustes de iOS",
    p6e: "<strong>No participar</strong> en analíticas — desde la pantalla de Ajustes de la app",
    h7: "7. Retención de datos",
    p7: "Conservamos tus datos mientras tu cuenta esté activa. Si eliminas tu cuenta, todos los datos personales se eliminan permanentemente de nuestros servidores en un plazo de 30 días. Los datos analíticos anónimos y agregados pueden conservarse indefinidamente.",
    h8: "8. Privacidad de los menores",
    p8: "Freshli no está dirigido a menores de 13 años. No recopilamos información personal de menores de forma consciente. Si crees que un menor nos ha facilitado datos personales, escribe a support@freshli.app y los eliminaremos.",
    h9: "9. Cambios en esta política",
    p9: `Podemos actualizar esta política de privacidad de vez en cuando. Te notificaremos cambios significativos a través de la app o por correo. La fecha de "Última actualización" al principio de esta página indica la revisión más reciente.`,
    h10: "10. Contáctanos",
    p10: "Si tienes preguntas sobre esta política de privacidad o tus datos, escríbenos a:",
    email: "<strong>Correo:</strong>"
  },
  terms: {
    title: "Términos del servicio",
    updated: "Última actualización: 12 de abril de 2026 · Contrato de licencia de usuario final (EULA)",
    h1: "1. Aceptación de los términos",
    p1: `Al descargar, instalar o utilizar la aplicación Freshli ("App"), aceptas quedar vinculado a estos Términos del servicio ("Términos"). Si no estás de acuerdo con estos Términos, no uses la App.`,
    h2: "2. Licencia",
    p2: "Freshli te concede una licencia limitada, no exclusiva, intransferible y revocable para usar la App en cualquier dispositivo Apple de tu propiedad o bajo tu control, sujeta a los Términos y condiciones de Apple Media Services. Esta licencia no te permite:",
    p2a: "Redistribuir, sublicenciar o vender la App",
    p2b: "Realizar ingeniería inversa, descompilar o desensamblar la App",
    p2c: "Usar la App con fines ilegales",
    p2d: "Interferir o interrumpir los servidores o redes de la App",
    h3: "3. Cuenta",
    p3: "Puedes crear una cuenta usando email/contraseña o Iniciar sesión con Apple. Eres responsable de mantener la confidencialidad de tus credenciales y de toda actividad en tu cuenta. Debes tener al menos 13 años para crear una cuenta.",
    h4: "4. Contenido del usuario",
    p4: "Conservas la propiedad de todo el contenido que creas en la App (productos de la despensa, publicaciones, reseñas). Al publicar contenido en el marketplace comunitario, otorgas a Freshli una licencia no exclusiva y mundial para mostrar ese contenido a otros usuarios con el fin de operar el marketplace.",
    p4note: "Te comprometes a no publicar contenido que sea:",
    p4a: "Falso, engañoso o fraudulento",
    p4b: "Dañino, abusivo, acosador o discriminatorio",
    p4c: "Que infrinja cualquier ley o reglamento",
    p4d: "Que viole cualquier derecho de propiedad intelectual",
    h5: "5. Marketplace comunitario",
    p5: "El marketplace comunitario permite a los usuarios compartir alimentos sobrantes con los vecinos. Freshli actúa como plataforma y no es parte de ninguna transacción entre usuarios. Freshli no garantiza la calidad, seguridad ni legalidad de los productos publicados. Los usuarios comparten y recogen alimentos bajo su propio riesgo.",
    h6: "6. Suscripciones",
    p6: `Freshli ofrece funciones premium opcionales mediante suscripciones con renovación automática ("Freshli Pro"). Las suscripciones se facturan a través de tu cuenta de Apple ID. El pago se carga en el momento de la confirmación de la compra. Las suscripciones se renuevan automáticamente a menos que se cancelen al menos 24 horas antes del final del periodo actual. Puedes gestionar o cancelar tus suscripciones en Ajustes de tu iPhone → Apple ID → Suscripciones.`,
    h7: "7. Funciones de IA",
    p7: "El Rescue Chef de Freshli usa el framework FoundationModels en el dispositivo de Apple para generar sugerencias de recetas. El contenido generado por IA se ofrece solo con fines informativos y no debe tratarse como asesoramiento dietético, nutricional o médico profesional. Usa siempre tu propio criterio en cuanto a la seguridad alimentaria.",
    h8: "8. Aviso sobre seguridad alimentaria",
    p8: "<strong>Freshli proporciona el seguimiento de caducidades como herramienta de conveniencia. Freshli no garantiza la seguridad ni la aptitud para el consumo de ningún alimento.</strong> Las fechas de caducidad introducidas por los usuarios pueden ser inexactas. Inspecciona siempre la comida con cuidado antes de consumirla. Freshli no se hace responsable de ninguna enfermedad, lesión o pérdida resultante del consumo de alimentos registrados o compartidos a través de la App.",
    h9: "9. Propiedad intelectual",
    p9: `La App, incluyendo su diseño, código, marca y contenido (excluyendo el contenido del usuario), es propiedad de Freshli y está protegida por las leyes de copyright, marcas y demás propiedad intelectual. El nombre Freshli, el logo y el lema "Por las personas. Por el planeta." son marcas comerciales de Freshli.`,
    h10: "10. Limitación de responsabilidad",
    p10: "En la máxima medida permitida por la ley aplicable, Freshli no será responsable de daños indirectos, incidentales, especiales, consecuentes o punitivos, incluyendo pérdida de beneficios, datos o buena voluntad, derivados del uso de la App. La responsabilidad total de Freshli no excederá el importe que hayas pagado por la App en los 12 meses anteriores a la reclamación.",
    h11: "11. Rescisión",
    p11: "Podemos suspender o cancelar tu cuenta si infringes estos Términos. Puedes eliminar tu cuenta en cualquier momento desde los Ajustes de la App. Al rescindir, tu derecho a usar la App cesa inmediatamente y tus datos se eliminarán conforme a nuestra Política de privacidad.",
    h12: "12. Cambios en los términos",
    p12: "Podemos actualizar estos Términos de vez en cuando. El uso continuado de la App tras los cambios constituye la aceptación de los nuevos Términos. Te notificaremos los cambios materiales a través de la App.",
    h13: "13. Términos específicos de Apple",
    p13: "Estos Términos son entre tú y Freshli, no Apple. Apple no tiene obligación de prestar mantenimiento ni soporte. En caso de incumplimiento de cualquier garantía aplicable, podrás notificar a Apple para obtener el reembolso del precio de compra (si lo hubiere); Apple no tiene ninguna otra obligación de garantía. Apple no es responsable de atender ninguna reclamación relacionada con la App. Apple es un tercero beneficiario de estos Términos.",
    h14: "14. Ley aplicable",
    p14: "Estos Términos se rigen por las leyes de Inglaterra y Gales. Cualquier disputa se resolverá en los tribunales de Inglaterra y Gales.",
    h15: "15. Contacto",
    p15: "¿Preguntas sobre estos Términos? Escríbenos a support@freshli.app."
  }
};
