window.__freshliTranslations = window.__freshliTranslations || {};
window.__freshliTranslations.fr = {
  nav: {
    features: "Fonctionnalités",
    impact: "Impact",
    support: "Assistance",
    downloadFree: "Télécharger gratuitement",
    backHome: "← Retour à l'accueil",
    language: "Langue"
  },
  hero: {
    title: "Vos aliments.<br>Votre <span class=\"green\">impact.</span>",
    subtitle: "Freshli s'appuie sur Apple Intelligence en local pour sauver vos aliments qui approchent de leur date limite — privé, instantané, sans connexion internet. Pour les gens. Pour la planète.",
    ctaDownload: "Télécharger sur l'App Store",
    ctaFeatures: "Voir les fonctionnalités ↓",
    badgeAI: "🤖 Apple Intelligence",
    badgeOnDevice: "🔒 100 % en local",
    badgeLanguages: "🌍 10 langues"
  },
  how: {
    label: "🚀 Comment ça marche",
    title: "Trois étapes vers<br>zéro gaspillage alimentaire.",
    step1Title: "Ajoutez vos aliments",
    step1Text: "Scannez un code-barres, photographiez un ticket de caisse, ou saisissez manuellement. En 5 secondes, c'est fait.",
    step2Title: "Recevez des alertes intelligentes",
    step2Text: "Freshli vous prévient de ce qui va bientôt périmer et vous suggère des recettes IA pour tout utiliser.",
    step3Title: "Sauvez ou partagez",
    step3Text: "Cuisinez, partagez avec vos voisins, ou donnez à un frigo solidaire."
  },
  features: {
    label: "✨ Fonctionnalités",
    title: "Tout ce qu'il vous faut pour<br>arrêter le gaspillage.",
    subtitle: "Suivez, sauvez, partagez et célébrez — le tout depuis une seule application magnifique, pensée pour ceux qui ont la planète à cœur.",
    rescueChef: {
      title: "Chef Sauveteur IA",
      text: "Appuyez sur un bouton et Apple Intelligence rédige des recettes adaptées à votre garde-manger. En local, privé, sans connexion internet."
    },
    expiry: {
      title: "Suivi intelligent des dates",
      text: "Scannez codes-barres, tickets de caisse, ou saisissez manuellement. Des pastilles colorées vous indiquent ce qu'il faut consommer en priorité, en un coup d'œil."
    },
    community: {
      title: "Partage solidaire",
      text: "Proposez vos surplus en libre collecte pour vos voisins. Trouvez des frigos solidaires. Rejoignez des cercles locaux pour un partage hyper-local."
    },
    wrap: {
      title: "Rétrospective hebdomadaire",
      text: "Un récap cinématographique de votre aventure anti-gaspi — aliments sauvés, CO₂ évité, argent économisé. À partager sur Instagram Stories."
    },
    watch: {
      title: "Apple Watch et widgets",
      text: "Alertes de péremption visibles d'un coup d'œil à votre poignet. Widgets interactifs avec consommation en un clic. Live Activities sur votre écran verrouillé."
    },
    siri: {
      title: "« Dis Siri, sauve mon garde-manger »",
      text: "Recettes IA activées à la voix depuis Siri, Raccourcis, Spotlight ou le Centre de contrôle. Zéro geste requis."
    },
    handsfree: {
      title: "Cuisine mains libres",
      text: "Freshli lit chaque étape de la recette à voix haute pour que vous ne touchiez jamais votre téléphone en cuisinant. Les yeux sur la poêle, pas sur l'écran."
    },
    wave: {
      title: "Vague en direct",
      text: "Découvrez l'impact mondial en temps réel — combien de personnes sauvent de la nourriture en ce moment, le total de CO₂ évité, et les repas partagés dans le monde entier."
    }
  },
  testimonial: {
    quote: "Je jetais au moins 15 € de nourriture par semaine. Avec Freshli, je n'ai rien mis à la poubelle en trois semaines. Les recettes IA sont vraiment utiles.",
    author: "— Sarah K., Paris"
  },
  ai: {
    label: "🧠 Apple Intelligence",
    title: "Les données de votre garde-manger<br>ne quittent jamais votre téléphone.",
    subtitle: "Le Chef Sauveteur de Freshli fonctionne entièrement en local grâce au framework FoundationModels d'iOS 26. Aucun serveur, aucun coût d'API, aucun compromis sur la vie privée. Votre frigo, c'est votre affaire."
  },
  impact: {
    label: "🌍 Impact mondial",
    title: "Ensemble, nous bâtissons<br>un monde sans gaspillage.",
    subtitle: "Chaque aliment que vous sauvez rejoint une vague mondiale de personnes qui luttent contre le gaspillage alimentaire.",
    itemsRescued: "Aliments sauvés",
    foodSaved: "Nourriture sauvée",
    familiesFed: "Familles nourries",
    savedPerHousehold: "Économisé par foyer et par an"
  },
  faq: {
    label: "❓ FAQ",
    title: "Questions fréquentes.",
    q1: "Freshli est-il vraiment gratuit ?",
    a1: "Oui. Les fonctionnalités essentielles — suivi du garde-manger, alertes de péremption, partage communautaire et Chef Sauveteur IA — sont entièrement gratuites. Freshli Pro est un abonnement optionnel pour les utilisateurs avancés.",
    q2: "L'IA a-t-elle besoin d'internet ?",
    a2: "Non. Le Chef Sauveteur fonctionne entièrement sur votre appareil grâce à Apple Intelligence. Aucun appel serveur, aucun coût d'API, aucune donnée ne quitte votre téléphone. Il fonctionne totalement hors ligne.",
    q3: "Quels appareils sont compatibles ?",
    a3: "Freshli requiert iOS 26 ou une version ultérieure. Le Chef Sauveteur IA nécessite Apple Intelligence (iPhone 16 et ultérieur). Les complications Apple Watch nécessitent watchOS 26.",
    moreQuestions: "D'autres questions ? Consultez l'Assistance →"
  },
  cta: {
    title: "Commencez à sauver<br>vos aliments dès aujourd'hui.",
    subtitle: "Téléchargement gratuit. Aucun compte requis pour commencer. Votre garde-manger, votre vie privée, votre planète.",
    button: "Télécharger Freshli gratuitement",
    badge1: "iOS 26+",
    badge2: "Apple Watch",
    badge3: "Raccourcis Siri",
    badge4: "Live Activities",
    badge5: "Mode sombre"
  },
  footer: {
    tagline: "Pour les gens. Pour la planète.",
    ourStory: "Notre histoire",
    partners: "Partenaires",
    social: "Réseaux sociaux",
    privacy: "Politique de confidentialité",
    terms: "Conditions d'utilisation",
    support: "Assistance",
    press: "Kit presse",
    contact: "Contact",
    home: "Accueil",
    rights: "© 2026 Freshli. Tous droits réservés."
  },
  support: {
    title: "Assistance",
    intro: "Nous sommes là pour vous aider. Trouvez des réponses ci-dessous ou contactez-nous directement — nous répondons généralement sous 24 heures.",
    needHelp: "Besoin d'aide ? Nous vous accompagnons.",
    hours: "Notre équipe d'assistance est disponible du lundi au vendredi, de 9 h à 18 h (heure de Paris).",
    quickHelp: "Aide rapide",
    gettingStarted: "Premiers pas",
    gettingStartedText: "Téléchargez Freshli depuis l'App Store, connectez-vous avec Apple et ajoutez votre premier aliment au garde-manger.",
    notifications: "Notifications",
    notificationsText: "Activez les rappels de péremption dans les Réglages pour recevoir des alertes avant que vos aliments ne se gâtent.",
    rescueChef: "Chef Sauveteur IA",
    rescueChefText: "Nécessite Apple Intelligence (iPhone 16 et ultérieur). Appuyez sur « Demander à Freshli » dans l'écran Chef Sauveteur.",
    accountPrivacy: "Compte et confidentialité",
    accountPrivacyText: "Supprimez votre compte à tout moment dans les Réglages. Toutes les données sont effacées sous 30 jours.",
    faqTitle: "Questions fréquentes",
    faq1q: "Freshli est-il gratuit ?",
    faq1a: "Oui. Freshli est gratuit à télécharger et à utiliser. Freshli Pro propose des fonctionnalités premium optionnelles via un abonnement, mais le suivi du garde-manger, les alertes de péremption et le partage communautaire sont entièrement gratuits.",
    faq2q: "L'IA a-t-elle besoin d'internet ?",
    faq2a: "Non. Le Chef Sauveteur utilise le framework FoundationModels d'Apple en local. Les données de votre garde-manger sont traitées entièrement sur votre iPhone — rien n'est envoyé à un serveur. Cela fonctionne hors ligne.",
    faq3q: "Quels appareils sont compatibles ?",
    faq3a: "Freshli requiert iOS 26 ou une version ultérieure. La fonctionnalité Chef Sauveteur IA nécessite Apple Intelligence (iPhone 16 et ultérieur). Les complications Apple Watch nécessitent watchOS 26.",
    faq4q: "Comment supprimer mon compte ?",
    faq4a: "Ouvrez Freshli → Profil → Réglages → faites défiler tout en bas → Supprimer le compte. Toutes vos données personnelles seront définitivement retirées de nos serveurs sous 30 jours.",
    faq5q: "Mes données sont-elles en sécurité ?",
    faq5a: "Oui. Vos données sont chiffrées en transit (TLS 1.3) et au repos (AES-256). Nous utilisons la Row Level Security afin que vous seul puissiez accéder à vos données. Nous ne vendons jamais vos données et n'utilisons aucun traceur tiers. Consultez notre Politique de confidentialité pour tous les détails.",
    faq6q: "Comment annuler mon abonnement ?",
    faq6a: "Ouvrez les Réglages de votre iPhone → appuyez sur votre nom → Abonnements → Freshli Pro → Annuler l'abonnement. Vous conservez l'accès jusqu'à la fin de la période de facturation en cours.",
    faq7q: "Puis-je partager de la nourriture avec mes voisins ?",
    faq7a: "Oui ! Rendez-vous dans l'onglet Communauté et appuyez sur « Nouvelle annonce » pour proposer vos surplus en libre collecte. Vous pouvez aussi parcourir ce que vos voisins partagent et réserver des aliments près de chez vous.",
    stillNeedHelp: "Toujours besoin d'aide ?",
    stillNeedHelpText: "Si votre question ne trouve pas de réponse ci-dessus, écrivez-nous à support@freshli.app en décrivant votre problème. Précisez le modèle de votre appareil et votre version d'iOS pour que nous puissions vous aider plus rapidement.",
    reportBug: "Signaler un bug",
    reportBugText: "Vous avez repéré quelque chose qui cloche ? Écrivez à support@freshli.app avec pour objet « Bug Report » et précisez :",
    bugItem1: "Ce que vous étiez en train de faire lorsque le problème est survenu",
    bugItem2: "Ce que vous attendiez et ce qui s'est réellement passé",
    bugItem3: "Une capture d'écran si possible",
    bugItem4: "Le modèle de votre iPhone et votre version d'iOS"
  },
  about: {
    heroTitle: "Pour les gens.<br>Pour la planète.",
    heroSubtitle: "L'histoire de Freshli : pourquoi nous l'avons créé, ce qui nous anime et où nous allons.",
    problem: "Le problème",
    problemP1: "Chaque année, <strong>un tiers de toute la nourriture produite dans le monde est gaspillée</strong> — 1,3 milliard de tonnes jetées en décharge pendant que 828 millions de personnes souffrent de la faim. Rien qu'en France, un foyer moyen jette plus de <strong>800 € de nourriture parfaitement consommable</strong> chaque année.",
    problemP2: "Le gaspillage alimentaire n'est pas qu'un problème financier. Lorsque la nourriture se décompose en décharge, elle produit du méthane — un gaz à effet de serre <strong>80 fois plus puissant que le CO²</strong> sur 20 ans. Si le gaspillage alimentaire était un pays, il serait le troisième plus grand émetteur de gaz à effet de serre au monde, derrière les États-Unis et la Chine.",
    problemP3: "Le plus difficile ? La majeure partie de ce gaspillage se produit à la maison. Pas dans les fermes. Pas dans les supermarchés. Dans nos frigos, nos placards, nos cuisines. Nous achetons avec de bonnes intentions, la vie nous rattrape, et quand nous y repensons, il est déjà trop tard.",
    callout1: "« Le meilleur moment pour sauver un aliment de la poubelle, c'est la veille de sa date de péremption. Le deuxième meilleur moment, c'est maintenant. »",
    story: "Notre histoire",
    storyP1: "Freshli est né d'une frustration simple : ouvrir son frigo un mardi soir, apercevoir un sachet d'épinards oublié, et constater qu'il est déjà passé. Ce moment — répété des millions de fois par jour, dans des millions de cuisines — c'est là que naît le gaspillage.",
    storyP2: "Nous nous sommes demandé : et si votre téléphone pouvait vous prévenir avant ce moment-là ? Et s'il pouvait vous suggérer une recette qui utilise les épinards, la moitié de poivron et les œufs qui arrivent tous à péremption cette semaine ? Et s'il pouvait faire tout cela <strong>sans envoyer vos données de courses à un serveur</strong> ?",
    storyP3: "C'est ça, Freshli. Une application conçue pour iOS 26 qui utilise le framework Foundation Models d'Apple pour transformer le contenu de votre frigo en repas, plutôt qu'en déchets — entièrement en local, avec zéro appel réseau. Privé par conception. Instantané par nature. Utile par défaut.",
    mission: "Notre mission",
    missionCallout: "Rendre la lutte contre le gaspillage alimentaire naturelle, gratifiante et collective — pour que sauver des aliments devienne une habitude aussi évidente que le recyclage.",
    missionP: "Nous pensons que la solution au gaspillage alimentaire n'est pas la culpabilité. Ce n'est pas un énième documentaire sur les décharges. C'est de faire de la <em>bonne chose</em> la <em>chose facile</em>. Lorsque votre téléphone vous annonce ce qui va se gâter, vous propose une recette en 15 minutes et vous montre que 347 autres personnes viennent aussi de sauver de la nourriture — soudain, sauver ces épinards ressemble à rejoindre un mouvement, pas à accomplir une corvée.",
    values: "Nos valeurs",
    value1Title: "La vie privée d'abord",
    value1Text: "Les données de votre garde-manger sont traitées sur votre appareil. Notre IA tourne entièrement en local grâce à Apple Intelligence. Aucun serveur ne voit vos courses.",
    value2Title: "La planète avant le profit",
    value2Text: "Chaque fonctionnalité que nous développons est mesurée à l'aune d'un seul critère : empêche-t-elle plus de nourriture de finir en décharge ? Si la réponse est non, nous ne la déployons pas.",
    value3Title: "La communauté plutôt que la compétition",
    value3Text: "Les surplus alimentaires doivent aller à un voisin, pas à la poubelle. Nous créons des outils qui rapprochent les gens, pas qui les isolent.",
    value4Title: "Accessible à tous",
    value4Text: "Suivi du regard ARKit pour une navigation mains libres, cuisine guidée à la voix, prise en charge complète de VoiceOver, Dynamic Type, Réduire les animations, 10 langues. Le gaspillage alimentaire est l'affaire de tous — la solution doit l'être aussi.",
    roadmap: "Nos objectifs",
    roadmapIntro: "Freshli ne fait que commencer. Voici notre feuille de route — pas seulement des fonctionnalités, mais les jalons d'impact que nous visons :",
    stat1Label: "Aliments sauvés d'ici 2027",
    stat2Label: "CO² évité",
    stat3Label: "Familles utilisant Freshli",
    stat4Label: "Pays atteints",
    roadAhead: "La route devant nous",
    q22026: "Lancement sur l'App Store",
    q22026Text: "Freshli 1.0 avec le Chef Sauveteur IA, la cuisine mains libres, la place de marché communautaire, la Vague en direct, la Rétrospective hebdomadaire, le compagnon Apple Watch, le design Liquid Glass avec shaders Metal 4, et la prise en charge de 10 langues.",
    q32026: "Partenariats avec les enseignes",
    q32026Text: "Connectez vos cartes de fidélité (Carrefour, Auchan, Leclerc, etc.) pour importer automatiquement vos achats. Un geste pour tout ajouter à votre garde-manger.",
    q42026: "Réseau de frigos solidaires",
    q42026Text: "Passer de 10 frigos amorcés à plus de 500 emplacements vérifiés à travers la France, l'Irlande et l'Europe. Mises à jour de disponibilité en temps réel.",
    year2027: "Rapports d'impact municipaux",
    year2027Text: "Agréger des données anonymisées sur les déchets pour offrir aux collectivités locales des informations exploitables sur les habitudes de gaspillage alimentaire des ménages. Des politiques guidées par les données.",
    yearPlus: "Expansion mondiale",
    yearPlusText: "Localiser l'application dans plus de 20 langues. Nouer des partenariats avec des banques alimentaires, des écoles et des associations communautaires à travers le monde. Faire de la lutte contre le gaspillage une norme mondiale.",
    joinUs: "Rejoignez-nous",
    joinUsP1: "Freshli est gratuit à télécharger. Aucun compte requis pour commencer à suivre votre garde-manger. Chaque aliment sauvé est un de moins à la décharge — et une raison de plus de croire que nous pouvons, ensemble, changer les choses.",
    joinUsP2: "<strong>Pour les gens. Pour la planète.</strong>",
    downloadLink: "Télécharger Freshli →",
    partnerLink: "Devenir partenaire →",
    contactLink: "Nous contacter →"
  },
  partners: {
    heroTitle: "Luttons ensemble<br>contre le gaspillage.",
    heroSubtitle: "Associez-vous à Freshli pour toucher des milliers de foyers soucieux de l'environnement. Parrainez notre mission. Faites un don pour que l'app reste gratuite.",
    whyTitle: "Pourquoi s'associer à Freshli ?",
    whyText: "Les utilisateurs de Freshli <strong>cherchent activement à réduire leur empreinte écologique</strong>. Ils suivent leurs aliments, cuisinent avec ce qu'ils ont, partagent leurs surplus avec leurs voisins et mesurent leur impact CO² chaque semaine. C'est l'une des audiences les plus engagées et les plus alignées sur les valeurs de l'App Store.",
    reach: "Une audience ciblée",
    reachText: "Chaque utilisateur de Freshli se soucie de la durabilité. Votre marque touche des personnes qui choisissent activement des produits écoresponsables.",
    impact: "Un impact mesurable",
    impactText: "Nous suivons les aliments sauvés, le CO² évité et les repas partagés. Votre partenariat s'accompagne d'indicateurs d'impact réels et exploitables.",
    align: "Alignement de marque",
    alignText: "Associez votre marque à une mission qui inspire. Sauver des aliments est universellement positif — aucune polémique, que de la bienveillance.",
    scale: "Portée mondiale",
    scaleText: "Freshli est disponible en 10 langues dans les plus grands marchés de l'App Store. Un seul partenariat, une visibilité mondiale.",
    opportunities: "Opportunités de partenariat",
    mostImpact: "IMPACT MAXIMUM",
    retailer: "Intégration enseigne",
    retailerPrice: "Pour les supermarchés et chaînes alimentaires",
    retailerText: "Connectez votre programme de fidélité à Freshli pour que vos clients puissent importer automatiquement leurs achats et suivre leurs aliments à la maison.",
    retailerL1: "Intégration des cartes de fidélité (Carrefour, Auchan, Leclerc, etc.)",
    retailerL2: "Suggestions de recettes avec vos produits",
    retailerL3: "Présence in-app auprès de millions d'utilisateurs actifs",
    retailerL4: "Rapports d'impact partagés pour vos campagnes RSE",
    getInTouch: "Nous contacter",
    mission: "Mécène de la mission",
    missionPrice: "Pour les marques engagées dans la durabilité",
    missionText: "Parrainez la version gratuite de Freshli pour que davantage de foyers accèdent à des outils anti-gaspi sans barrière payante.",
    missionL1: "« Propulsé par [Votre marque] » dans l'app",
    missionL2: "Mise en avant dans la carte à partager de la Rétrospective hebdomadaire",
    missionL3: "Rapports d'impact co-brandés",
    missionL4: "Couverture presse comme mécène fondateur",
    missionL5: "Accès prioritaire aux nouvelles fonctionnalités",
    becomeSponsor: "Devenir mécène",
    community: "Partenaire communautaire",
    communityPrice: "Pour les banques alimentaires, associations et collectivités",
    communityText: "Intégrez votre réseau de frigos solidaires, vos points de collecte ou vos programmes de réduction des déchets dans Freshli.",
    communityL1: "Référencement in-app de vos frigos et points de dépôt",
    communityL2: "Mises à jour de disponibilité en temps réel par les utilisateurs",
    communityL3: "Données anonymisées sur le gaspillage pour éclairer les politiques publiques",
    communityL4: "Gratuit — à vie, pour les associations",
    partnerWithUs: "Devenir partenaire",
    sponsor: "Parrainer Freshli",
    sponsorText: "Le mécénat permet de garder gratuites les fonctionnalités essentielles de Freshli pour tous les foyers. Votre soutien finance directement :",
    sponsorL1: "L'infrastructure serveur de la place de marché communautaire",
    sponsorL2: "L'extension du réseau de frigos solidaires à de nouvelles villes",
    sponsorL3: "La localisation dans davantage de langues pour que plus de gens puissent sauver des aliments",
    sponsorL4: "Des améliorations d'accessibilité pour les utilisateurs en situation de handicap",
    sponsorL5: "Des actions scolaires — sensibiliser la prochaine génération au gaspillage alimentaire",
    donate: "Faire un don",
    donateTitle: "Gardons Freshli gratuit pour tous",
    donateText: "Chaque don finance directement la lutte contre le gaspillage alimentaire — coûts serveur, extension du réseau de frigos et maintien de l'app gratuite.",
    donateKofi: "Soutenir sur Ko-fi",
    donateKofiNote: "Propulsé par Ko-fi — <strong>0 % de frais de plateforme</strong>. 100 % de votre don revient à Freshli.",
    donateOneTime: "☕ Don ponctuel",
    donateMonthly: "💚 Mensuel",
    donateBank: "🏦 Virement bancaire",
    donateDisclaimer: "Freshli n'est pas encore reconnue comme association caritative. Les dons sont traités comme des contributions au projet via Ko-fi (Stripe/PayPal). Pour un don 100 % sans frais, choisissez le virement bancaire — écrivez-nous pour en savoir plus. Nous travaillons à obtenir ce statut.",
    advertise: "Faire de la publicité avec Freshli",
    advertiseP1: "Nous proposons des opportunités publicitaires limitées et soignées, réservées aux marques alignées avec notre mission. Pas de pop-ups, pas de pistage, pas de vente de données — simplement des produits pertinents présentés à des personnes soucieuses de durabilité.",
    advertiseAccept: "<strong>Ce que nous acceptons :</strong> marques alimentaires écoresponsables, produits de cuisine durables, marques zéro déchet, épiceries bio, entreprises de l'alimentation végétale.",
    advertiseDecline: "<strong>Ce que nous refusons :</strong> chaînes de restauration rapide, produits en plastique à usage unique, tout ce qui contredit notre mission.",
    advertiseContact: "Contactez support@freshli.app pour notre grille tarifaire et les données d'audience.",
    ctaTitle: "Prêt à faire la différence ?",
    ctaText: "Que vous soyez un supermarché, une marque engagée, une banque alimentaire ou simplement quelqu'un qui veut aider — nous serions ravis d'échanger avec vous."
  },
  press: {
    title: "Kit presse",
    intro: "Tout ce dont journalistes et créateurs ont besoin pour parler de Freshli. Pour toute demande presse, contactez support@freshli.app.",
    aboutTitle: "À propos de Freshli",
    boilerplate: "Freshli est une application iOS qui aide les foyers à sauver leurs aliments de la poubelle grâce à Apple Intelligence en local. Les utilisateurs suivent leur garde-manger, obtiennent des recettes générées par IA pour les ingrédients qui arrivent à péremption (entièrement en local, sans aucun appel réseau), cuisinent mains libres avec des étapes de recette guidées à la voix, partagent leurs surplus avec leurs voisins et voient leur impact environnemental grandir semaine après semaine. Conçue avec Swift 6.2, SwiftUI, SwiftData et Metal 4 pour iOS 26. Pour les gens. Pour la planète.",
    keyFacts: "Chiffres clés",
    fact1: "Taille de téléchargement",
    fact2: "Langues prises en charge",
    fact3: "Traitement IA en local",
    fact4: "Traceurs tiers",
    fact5: "Gaspillage alimentaire moyen par foyer et par an",
    fact6: "CO² évité par aliment sauvé",
    differentTitle: "Ce qui rend Freshli unique",
    diff1: "<strong>IA en local :</strong> le Chef Sauveteur utilise le framework FoundationModels d'iOS 26 — les recettes sont générées entièrement sur l'appareil. Aucun serveur, aucun coût d'API, aucun compromis sur la vie privée.",
    diff2: "<strong>Communauté avant tout :</strong> partagez vos surplus avec vos voisins, donnez aux frigos solidaires, rejoignez des cercles locaux pour un partage hyper-local.",
    diff3: "<strong>Un impact que l'on ressent :</strong> la Rétrospective hebdomadaire — une histoire cinématographique et partageable de votre impact anti-gaspi, avec des arrière-plans MeshGradient animés et un arbre qui grandit.",
    diff4: "<strong>Cuisine mains libres :</strong> Freshli lit chaque étape de la recette à voix haute pour que l'utilisateur n'ait jamais à toucher son téléphone en cuisinant. Les yeux sur la poêle, pas sur l'écran.",
    diff5: "<strong>Accessibilité par suivi du regard :</strong> le face tracking ARKit permet une navigation mains libres — les éléments de l'interface se dilatent subtilement vers le regard de l'utilisateur. Conformité complète WCAG 2.2 AA.",
    diff6: "<strong>Intégration poussée de la plateforme :</strong> Apple Watch, Raccourcis Siri, widgets du Centre de contrôle, widgets interactifs, Live Activities, Dynamic Island et actions rapides ControlWidget.",
    techTitle: "Technologies iOS 26 utilisées",
    brandTitle: "Ressources de marque",
    appName: "<strong>Nom de l'app :</strong> Freshli",
    tagline: "<strong>Slogan :</strong> Pour les gens. Pour la planète.",
    subtitle: "<strong>Sous-titre :</strong> Sauvez des aliments. Sauvez la planète.",
    category: "<strong>Catégorie :</strong> Cuisine et boissons (principale), Style de vie (secondaire)",
    colors: "Couleurs de marque",
    screenshots: "Captures d'écran",
    screenshotsText: "Des captures d'écran App Store en haute résolution (1320 × 2868, iPhone 17 Pro Max) sont disponibles. Contactez support@freshli.app pour recevoir le kit presse complet avec les mockups encadrés.",
    contactTitle: "Contact",
    pressEnquiries: "<strong>Demandes presse :</strong>",
    website: "<strong>Site web :</strong>",
    appStore: "<strong>App Store :</strong> disponible sur l'App Store (iOS 26+)"
  },
  social: {
    title: "Suivez la vague du sauvetage.",
    subtitle: "Actualités en direct, astuces anti-gaspi, histoires de la communauté et coulisses de l'équipe Freshli.",
    liveFrom: "En direct de Freshli",
    liveFromText: "Découvrez ce que nous partageons sur nos différents canaux — appuyez sur une plateforme pour voir les dernières actus.",
    followInstagram: "Suivez-nous sur Instagram",
    followInstagramText: "Coulisses, astuces anti-gaspi et temps forts de la Rétrospective hebdomadaire. Suivez @freshliapp pour votre inspiration quotidienne.",
    openInstagram: "Ouvrir Instagram →",
    phTitle: "Freshli sur Product Hunt",
    phText: "Votez pour Freshli lors de notre lancement, laissez un avis et aidez-nous à atteindre la une. Chaque vote compte.",
    phLink: "Voir sur Product Hunt →",
    newsletterTitle: "Ne manquez pas le lancement.",
    newsletterText: "Suivez-nous sur votre plateforme préférée pour être le premier à savoir quand Freshli arrive sur l'App Store.",
    newsletterCta: "Suivez @everwiseapps sur X →"
  },
  privacy: {
    title: "Politique de confidentialité",
    updated: "Dernière mise à jour : 12 avril 2026",
    highlight: "Les données de votre garde-manger sont traitées sur votre appareil. Le Chef Sauveteur IA de Freshli fonctionne entièrement en local grâce à Apple Intelligence — vos données alimentaires ne quittent jamais votre téléphone.",
    h1: "1. Qui sommes-nous",
    p1: "Freshli est exploitée par Freshli (« nous », « notre », « nos »). Cette politique explique comment nous collectons, utilisons et protégeons vos informations personnelles lorsque vous utilisez l'application iOS Freshli et le site freshli.app.",
    contact: "Contact :",
    h2: "2. Informations que nous collectons",
    h21: "2.1 Informations de compte",
    p21: "Lorsque vous créez un compte, nous collectons :",
    p21a: "<strong>Adresse e-mail</strong> — pour l'authentification et la récupération de compte",
    p21b: "<strong>Nom d'utilisateur</strong> — affiché sur la place de marché communautaire",
    p21c: "<strong>Métadonnées Apple ID</strong> — si vous utilisez Se connecter avec Apple (nom, e-mail relais)",
    h22: "2.2 Données du garde-manger",
    p22: "Les aliments que vous ajoutez à votre garde-manger (noms, quantités, dates de péremption, catégories, lieux de stockage) sont stockés :",
    p22a: "<strong>Localement sur votre appareil</strong> via SwiftData — toujours disponibles hors ligne",
    p22b: "<strong>Sur nos serveurs</strong> (Supabase, région EU-West) — pour la synchronisation multi-appareils et la sauvegarde, chiffrées en transit et au repos",
    h23: "2.3 Données communautaires",
    p23: "Si vous proposez des surplus alimentaires sur la place de marché communautaire, les détails de votre annonce (nom de l'aliment, description, zone générale) sont visibles par les autres utilisateurs. Votre adresse exacte n'est jamais partagée, sauf si vous choisissez d'inclure les modalités de récupération.",
    h24: "2.4 Analytiques d'usage",
    p24: "Nous collectons des analytiques produit anonymes pour améliorer l'application :",
    p24a: "Quelles fonctionnalités vous utilisez (p. ex. Chef Sauveteur, Rétrospective hebdomadaire) — jamais le contenu",
    p24b: "Version de l'app, durée de session, taux de sessions sans plantage",
    p24c: "Aucun identifiant d'appareil, aucun identifiant publicitaire, aucun traceur tiers",
    h25: "2.5 Traitement IA",
    p25: "Le Chef Sauveteur de Freshli utilise le framework FoundationModels d'Apple en local. Le contenu de votre garde-manger est traité entièrement sur votre iPhone — il n'est jamais envoyé à nos serveurs, à ceux d'Apple ni à aucun tiers pour le traitement IA.",
    h3: "3. Comment nous utilisons vos informations",
    p3a: "Pour fournir et maintenir le service Freshli",
    p3b: "Pour synchroniser vos données de garde-manger entre vos appareils",
    p3c: "Pour envoyer des notifications de rappel de péremption (avec votre autorisation)",
    p3d: "Pour afficher vos annonces sur la place de marché communautaire",
    p3e: "Pour calculer et afficher votre impact environnemental (CO2 évité, argent économisé)",
    p3f: "Pour améliorer l'application via des analytiques anonymes et agrégées",
    p3note: "Nous ne vendons <strong>jamais</strong> vos données personnelles à des tiers. Nous n'utilisons <strong>jamais</strong> vos données à des fins publicitaires.",
    h4: "4. Stockage et sécurité des données",
    p4a: "Les données serveur sont hébergées sur <strong>Supabase</strong> (région EU-West-3, infrastructure AWS)",
    p4b: "Toutes les données sont chiffrées en transit (TLS 1.3) et au repos (AES-256)",
    p4c: "La Row Level Security (RLS) garantit que vous seul pouvez accéder à vos données",
    p4d: "Les mots de passe sont vérifiés via HaveIBeenPwned pour empêcher l'utilisation d'identifiants compromis",
    h5: "5. Partage de données",
    p5: "Nous partageons vos données uniquement dans ces cas limités :",
    p5a: "<strong>Place de marché communautaire</strong> — les détails de votre annonce sont visibles par les autres utilisateurs (vous décidez de ce que vous partagez)",
    p5b: "<strong>Obligations légales</strong> — si la loi, une décision de justice ou une autorité de régulation l'exige",
    p5c: "<strong>Prestataires</strong> — Supabase (hébergement de base de données), Apple (authentification, notifications push) — sous stricts accords de traitement des données",
    h6: "6. Vos droits",
    p6: "Vous avez le droit de :",
    p6a: "<strong>Accéder</strong> à vos données — disponibles dans les Réglages de l'app",
    p6b: "<strong>Supprimer</strong> votre compte et toutes les données associées — Réglages → Supprimer le compte",
    p6c: "<strong>Exporter</strong> les données de votre garde-manger — contactez support@freshli.app",
    p6d: "<strong>Retirer votre consentement</strong> pour les notifications — via les Réglages iOS",
    p6e: "<strong>Refuser</strong> les analytiques — depuis l'écran Réglages de l'app",
    h7: "7. Conservation des données",
    p7: "Nous conservons vos données tant que votre compte est actif. Si vous supprimez votre compte, toutes vos données personnelles sont définitivement retirées de nos serveurs sous 30 jours. Les données analytiques anonymes et agrégées peuvent être conservées indéfiniment.",
    h8: "8. Confidentialité des enfants",
    p8: "Freshli ne s'adresse pas aux enfants de moins de 13 ans. Nous ne collectons pas sciemment d'informations personnelles auprès d'enfants. Si vous pensez qu'un enfant nous a fourni des données personnelles, contactez support@freshli.app et nous les supprimerons.",
    h9: "9. Modifications de cette politique",
    p9: "Nous pouvons mettre à jour cette politique de confidentialité ponctuellement. Nous vous informerons des changements importants via l'application ou par e-mail. La date « Dernière mise à jour » en haut de cette page indique la révision la plus récente.",
    h10: "10. Nous contacter",
    p10: "Pour toute question concernant cette politique de confidentialité ou vos données, contactez-nous à :",
    email: "<strong>E-mail :</strong>"
  },
  terms: {
    title: "Conditions d'utilisation",
    updated: "Dernière mise à jour : 12 avril 2026 · Contrat de licence utilisateur final (CLUF)",
    h1: "1. Acceptation des conditions",
    p1: "En téléchargeant, installant ou utilisant l'application Freshli (« l'Application »), vous acceptez d'être lié par ces Conditions d'utilisation (« Conditions »). Si vous n'acceptez pas ces Conditions, n'utilisez pas l'Application.",
    h2: "2. Licence",
    p2: "Freshli vous accorde une licence limitée, non exclusive, non transférable et révocable pour utiliser l'Application sur tout appareil Apple que vous possédez ou contrôlez, sous réserve des Conditions générales des services Apple Media. Cette licence ne vous autorise pas à :",
    p2a: "Redistribuer, sous-licencier ou vendre l'Application",
    p2b: "Faire de l'ingénierie inverse, décompiler ou désassembler l'Application",
    p2c: "Utiliser l'Application à des fins illégales",
    p2d: "Interférer avec ou perturber les serveurs ou réseaux de l'Application",
    h3: "3. Compte",
    p3: "Vous pouvez créer un compte par e-mail/mot de passe ou via Se connecter avec Apple. Vous êtes responsable de la confidentialité de vos identifiants et de toute activité effectuée depuis votre compte. Vous devez avoir au moins 13 ans pour créer un compte.",
    h4: "4. Contenu utilisateur",
    p4: "Vous conservez la propriété de tout contenu que vous créez dans l'Application (aliments du garde-manger, annonces, avis). En publiant du contenu sur la place de marché communautaire, vous accordez à Freshli une licence non exclusive et mondiale pour afficher ce contenu auprès des autres utilisateurs, aux seules fins d'exploitation de la place de marché.",
    p4note: "Vous vous engagez à ne pas publier de contenu qui soit :",
    p4a: "Faux, trompeur ou frauduleux",
    p4b: "Nuisible, abusif, harcelant ou discriminatoire",
    p4c: "Contraire à toute loi ou réglementation",
    p4d: "Violant des droits de propriété intellectuelle",
    h5: "5. Place de marché communautaire",
    p5: "La place de marché communautaire permet aux utilisateurs de partager leurs surplus alimentaires avec leurs voisins. Freshli agit en tant que plateforme et n'est pas partie aux transactions entre utilisateurs. Freshli ne garantit ni la qualité, ni la sécurité, ni la légalité des aliments proposés. Les utilisateurs partagent et récupèrent des aliments à leurs propres risques.",
    h6: "6. Abonnements",
    p6: "Freshli propose des fonctionnalités premium optionnelles via des abonnements à renouvellement automatique (« Freshli Pro »). Les abonnements sont facturés via votre compte Apple ID. Le paiement est prélevé à la confirmation de l'achat. Les abonnements se renouvellent automatiquement, sauf annulation au moins 24 heures avant la fin de la période en cours. Vous pouvez gérer ou annuler vos abonnements dans les Réglages de votre iPhone → Apple ID → Abonnements.",
    h7: "7. Fonctionnalités IA",
    p7: "Le Chef Sauveteur de Freshli utilise le framework FoundationModels d'Apple en local pour générer des suggestions de recettes. Le contenu généré par l'IA est fourni à titre informatif uniquement et ne doit pas être considéré comme un conseil diététique, nutritionnel ou médical professionnel. Faites toujours preuve de jugement concernant la sécurité alimentaire.",
    h8: "8. Clause de sécurité alimentaire",
    p8: "<strong>Freshli propose le suivi des dates de péremption comme outil de confort. Freshli ne garantit ni la sécurité ni la comestibilité d'aucun aliment.</strong> Les dates de péremption saisies par les utilisateurs peuvent être inexactes. Inspectez toujours soigneusement les aliments avant de les consommer. Freshli ne saurait être tenue responsable de toute maladie, blessure ou perte résultant de la consommation d'aliments suivis ou partagés via l'Application.",
    h9: "9. Propriété intellectuelle",
    p9: "L'Application, y compris son design, son code, sa marque et son contenu (à l'exclusion du contenu utilisateur), est la propriété de Freshli et est protégée par le droit d'auteur, les marques et autres lois sur la propriété intellectuelle. Le nom Freshli, son logo et le slogan « Pour les gens. Pour la planète. » sont des marques de Freshli.",
    h10: "10. Limitation de responsabilité",
    p10: "Dans la mesure maximale autorisée par la loi applicable, Freshli ne saurait être tenue responsable de tout dommage indirect, accessoire, spécial, consécutif ou punitif, y compris la perte de bénéfices, de données ou de réputation, découlant de votre utilisation de l'Application. La responsabilité totale de Freshli ne saurait excéder le montant que vous avez payé pour l'Application au cours des 12 mois précédant la réclamation.",
    h11: "11. Résiliation",
    p11: "Nous pouvons suspendre ou résilier votre compte si vous enfreignez ces Conditions. Vous pouvez supprimer votre compte à tout moment depuis les Réglages de l'Application. Après résiliation, votre droit d'utiliser l'Application cesse immédiatement et vos données seront supprimées conformément à notre Politique de confidentialité.",
    h12: "12. Modifications des conditions",
    p12: "Nous pouvons mettre à jour ces Conditions ponctuellement. Une utilisation continue de l'Application après modification vaut acceptation des nouvelles Conditions. Nous vous informerons des changements importants via l'Application.",
    h13: "13. Conditions spécifiques à Apple",
    p13: "Ces Conditions lient vous-même et Freshli, non Apple. Apple n'a aucune obligation de fournir maintenance ou assistance. En cas de non-conformité à une garantie applicable, vous pouvez en informer Apple pour obtenir le remboursement du prix d'achat (le cas échéant) ; Apple n'a aucune autre obligation de garantie. Apple n'est pas responsable du traitement des réclamations relatives à l'Application. Apple est un tiers bénéficiaire de ces Conditions.",
    h14: "14. Droit applicable",
    p14: "Ces Conditions sont régies par le droit français. Tout litige sera soumis à la compétence exclusive des tribunaux français.",
    h15: "15. Contact",
    p15: "Des questions sur ces Conditions ? Contactez-nous à support@freshli.app."
  }
};
