window.__freshliTranslations = window.__freshliTranslations || {};
window.__freshliTranslations.it = {
  nav: {
    features: "Funzionalità",
    impact: "Impatto",
    support: "Assistenza",
    downloadFree: "Scarica gratis",
    backHome: "← Torna alla home",
    language: "Lingua"
  },
  hero: {
    title: "I suoi alimenti.<br>Il suo <span class=\"green\">impatto.</span>",
    subtitle: "Freshli sfrutta Apple Intelligence in locale per salvare i suoi alimenti prossimi alla scadenza — privato, istantaneo, senza connessione a internet. Per le persone. Per il pianeta.",
    ctaDownload: "Scarica sull'App Store",
    ctaFeatures: "Scopri le funzionalità ↓",
    badgeAI: "🤖 Apple Intelligence",
    badgeOnDevice: "🔒 100% in locale",
    badgeLanguages: "🌍 10 lingue"
  },
  how: {
    label: "🚀 Come funziona",
    title: "Tre passi verso<br>zero spreco alimentare.",
    step1Title: "Aggiunga i suoi alimenti",
    step1Text: "Scansioni un codice a barre, fotografi uno scontrino, o inserisca manualmente. In 5 secondi è fatto.",
    step2Title: "Riceva avvisi intelligenti",
    step2Text: "Freshli la avvisa di cosa sta per scadere e le suggerisce ricette IA per utilizzare tutto.",
    step3Title: "Salvi o condivida",
    step3Text: "Cucini, condivida con i vicini, o doni a un frigorifero solidale."
  },
  features: {
    label: "✨ Funzionalità",
    title: "Tutto ciò che le serve per<br>fermare lo spreco.",
    subtitle: "Monitori, salvi, condivida e festeggi — il tutto da un'unica splendida applicazione, pensata per chi ha a cuore il pianeta.",
    rescueChef: {
      title: "Chef Salvatore IA",
      text: "Prema un pulsante e Apple Intelligence comporrà ricette su misura per la sua dispensa. In locale, privato, senza connessione a internet."
    },
    expiry: {
      title: "Monitoraggio intelligente delle date",
      text: "Scansioni codici a barre, scontrini, o inserisca manualmente. Pastiglie colorate le indicano cosa consumare per primo, a colpo d'occhio."
    },
    community: {
      title: "Condivisione solidale",
      text: "Offra le sue eccedenze in libero ritiro ai vicini. Trovi frigoriferi solidali. Si unisca a cerchie locali per una condivisione iper-locale."
    },
    wrap: {
      title: "Retrospettiva settimanale",
      text: "Un riassunto cinematografico della sua avventura anti-spreco — alimenti salvati, CO₂ evitata, denaro risparmiato. Da condividere su Instagram Stories."
    },
    watch: {
      title: "Apple Watch e widget",
      text: "Avvisi di scadenza visibili a colpo d'occhio al polso. Widget interattivi con consumo in un tap. Live Activities sulla schermata di blocco."
    },
    siri: {
      title: "«Hey Siri, salva la mia dispensa»",
      text: "Ricette IA attivate con la voce da Siri, Comandi Rapidi, Spotlight o Centro di Controllo. Zero gesti richiesti."
    },
    handsfree: {
      title: "Cucina a mani libere",
      text: "Freshli legge ogni passaggio della ricetta ad alta voce, così non dovrà mai toccare il telefono mentre cucina. Gli occhi sulla padella, non sullo schermo."
    },
    wave: {
      title: "Onda in diretta",
      text: "Scopra l'impatto globale in tempo reale — quante persone stanno salvando cibo in questo momento, il totale di CO₂ evitata e i pasti condivisi in tutto il mondo."
    }
  },
  testimonial: {
    quote: "Buttavo almeno 15 € di cibo a settimana. Con Freshli, in tre settimane non ho buttato nulla. Le ricette IA sono davvero utili.",
    author: "— Sara K., Milano"
  },
  ai: {
    label: "🧠 Apple Intelligence",
    title: "I dati della sua dispensa<br>non lasciano mai il suo telefono.",
    subtitle: "Lo Chef Salvatore di Freshli funziona interamente in locale grazie al framework FoundationModels di iOS 26. Nessun server, nessun costo API, nessun compromesso sulla privacy. Il suo frigo è affar suo."
  },
  impact: {
    label: "🌍 Impatto globale",
    title: "Insieme, costruiamo<br>un mondo senza sprechi.",
    subtitle: "Ogni alimento che salva si unisce a un'onda globale di persone che combattono lo spreco alimentare.",
    itemsRescued: "Alimenti salvati",
    foodSaved: "Cibo salvato",
    familiesFed: "Famiglie nutrite",
    savedPerHousehold: "Risparmiato per famiglia all'anno"
  },
  faq: {
    label: "❓ FAQ",
    title: "Domande frequenti.",
    q1: "Freshli è davvero gratis?",
    a1: "Sì. Le funzionalità essenziali — monitoraggio della dispensa, avvisi di scadenza, condivisione comunitaria e Chef Salvatore IA — sono completamente gratuite. Freshli Pro è un abbonamento opzionale per gli utenti avanzati.",
    q2: "L'IA ha bisogno di internet?",
    a2: "No. Lo Chef Salvatore funziona interamente sul suo dispositivo grazie ad Apple Intelligence. Nessuna chiamata al server, nessun costo API, nessun dato lascia il suo telefono. Funziona completamente offline.",
    q3: "Quali dispositivi sono compatibili?",
    a3: "Freshli richiede iOS 26 o versione successiva. Lo Chef Salvatore IA necessita di Apple Intelligence (iPhone 16 e successivi). Le complicazioni Apple Watch richiedono watchOS 26.",
    moreQuestions: "Altre domande? Consulti l'Assistenza →"
  },
  cta: {
    title: "Inizi a salvare<br>i suoi alimenti oggi stesso.",
    subtitle: "Download gratuito. Nessun account richiesto per iniziare. La sua dispensa, la sua privacy, il suo pianeta.",
    button: "Scarica Freshli gratis",
    badge1: "iOS 26+",
    badge2: "Apple Watch",
    badge3: "Comandi Rapidi Siri",
    badge4: "Live Activities",
    badge5: "Modalità scura"
  },
  footer: {
    tagline: "Per le persone. Per il pianeta.",
    ourStory: "La nostra storia",
    partners: "Partner",
    social: "Social",
    privacy: "Informativa sulla privacy",
    terms: "Termini di servizio",
    support: "Assistenza",
    press: "Kit stampa",
    contact: "Contatti",
    home: "Home",
    rights: "© 2026 Freshli. Tutti i diritti riservati."
  },
  support: {
    title: "Assistenza",
    intro: "Siamo qui per aiutarla. Trovi risposte qui sotto o ci contatti direttamente — in genere rispondiamo entro 24 ore.",
    needHelp: "Ha bisogno di aiuto? Le siamo accanto.",
    hours: "Il nostro team di assistenza è disponibile dal lunedì al venerdì, dalle 9:00 alle 18:00 (ora italiana).",
    quickHelp: "Aiuto rapido",
    gettingStarted: "Primi passi",
    gettingStartedText: "Scarichi Freshli dall'App Store, acceda con Apple e aggiunga il suo primo alimento alla dispensa.",
    notifications: "Notifiche",
    notificationsText: "Attivi i promemoria di scadenza nelle Impostazioni per ricevere avvisi prima che i suoi alimenti si rovinino.",
    rescueChef: "Chef Salvatore IA",
    rescueChefText: "Richiede Apple Intelligence (iPhone 16 e successivi). Prema «Chiedi a Freshli» nella schermata Chef Salvatore.",
    accountPrivacy: "Account e privacy",
    accountPrivacyText: "Elimini il suo account in qualsiasi momento dalle Impostazioni. Tutti i dati vengono cancellati entro 30 giorni.",
    faqTitle: "Domande frequenti",
    faq1q: "Freshli è gratis?",
    faq1a: "Sì. Freshli è gratuito da scaricare e utilizzare. Freshli Pro offre funzionalità premium opzionali tramite abbonamento, ma il monitoraggio della dispensa, gli avvisi di scadenza e la condivisione comunitaria sono completamente gratuiti.",
    faq2q: "L'IA ha bisogno di internet?",
    faq2a: "No. Lo Chef Salvatore utilizza il framework FoundationModels di Apple in locale. I dati della sua dispensa vengono elaborati interamente sul suo iPhone — nulla viene inviato a un server. Funziona offline.",
    faq3q: "Quali dispositivi sono compatibili?",
    faq3a: "Freshli richiede iOS 26 o versione successiva. La funzionalità Chef Salvatore IA necessita di Apple Intelligence (iPhone 16 e successivi). Le complicazioni Apple Watch richiedono watchOS 26.",
    faq4q: "Come elimino il mio account?",
    faq4a: "Apra Freshli → Profilo → Impostazioni → scorra fino in fondo → Elimina account. Tutti i suoi dati personali saranno rimossi definitivamente dai nostri server entro 30 giorni.",
    faq5q: "I miei dati sono al sicuro?",
    faq5a: "Sì. I suoi dati sono cifrati in transito (TLS 1.3) e a riposo (AES-256). Utilizziamo la Row Level Security affinché solo lei possa accedere ai suoi dati. Non vendiamo mai i suoi dati e non utilizziamo alcun tracker di terze parti. Consulti la nostra Informativa sulla privacy per tutti i dettagli.",
    faq6q: "Come annullo il mio abbonamento?",
    faq6a: "Apra le Impostazioni del suo iPhone → tocchi il suo nome → Abbonamenti → Freshli Pro → Annulla abbonamento. Manterrà l'accesso fino alla fine del periodo di fatturazione in corso.",
    faq7q: "Posso condividere cibo con i miei vicini?",
    faq7a: "Sì! Vada nella scheda Comunità e prema «Nuovo annuncio» per offrire le sue eccedenze in libero ritiro. Può anche sfogliare ciò che i suoi vicini stanno condividendo e prenotare alimenti vicino a lei.",
    stillNeedHelp: "Ha ancora bisogno di aiuto?",
    stillNeedHelpText: "Se non trova risposta alla sua domanda qui sopra, ci scriva a support@freshli.app descrivendo il problema. Indichi il modello del suo dispositivo e la versione di iOS per permetterci di aiutarla più rapidamente.",
    reportBug: "Segnala un bug",
    reportBugText: "Ha notato qualcosa che non va? Scriva a support@freshli.app con oggetto «Bug Report» e indichi:",
    bugItem1: "Cosa stava facendo quando si è verificato il problema",
    bugItem2: "Cosa si aspettava e cosa è realmente successo",
    bugItem3: "Uno screenshot, se possibile",
    bugItem4: "Il modello del suo iPhone e la sua versione di iOS"
  },
  about: {
    heroTitle: "Per le persone.<br>Per il pianeta.",
    heroSubtitle: "La storia di Freshli: perché l'abbiamo creata, cosa ci muove e dove stiamo andando.",
    problem: "Il problema",
    problemP1: "Ogni anno, <strong>un terzo di tutto il cibo prodotto nel mondo viene sprecato</strong> — 1,3 miliardi di tonnellate gettate in discarica mentre 828 milioni di persone soffrono la fame. Solo in Italia, una famiglia media butta più di <strong>700 € di cibo perfettamente commestibile</strong> ogni anno.",
    problemP2: "Lo spreco alimentare non è solo un problema economico. Quando il cibo si decompone in discarica, produce metano — un gas serra <strong>80 volte più potente della CO²</strong> su un arco di 20 anni. Se lo spreco alimentare fosse una nazione, sarebbe il terzo maggiore emettitore di gas serra al mondo, dopo Stati Uniti e Cina.",
    problemP3: "La cosa più difficile? La maggior parte di questo spreco avviene in casa. Non nelle fattorie. Non nei supermercati. Nei nostri frigoriferi, nelle nostre dispense, nelle nostre cucine. Compriamo con le migliori intenzioni, la vita ci travolge, e quando ci torniamo a pensare, è già troppo tardi.",
    callout1: "«Il momento migliore per salvare un alimento dalla spazzatura è il giorno prima della sua scadenza. Il secondo momento migliore è adesso.»",
    story: "La nostra storia",
    storyP1: "Freshli è nata da una frustrazione semplice: aprire il frigo un martedì sera, intravedere un sacchetto di spinaci dimenticato, e constatare che è già andato. Quel momento — ripetuto milioni di volte al giorno, in milioni di cucine — è lì che nasce lo spreco.",
    storyP2: "Ci siamo chiesti: e se il suo telefono potesse avvisarla prima di quel momento? E se potesse suggerirle una ricetta che usa gli spinaci, mezzo peperone e le uova che stanno scadendo tutti questa settimana? E se potesse fare tutto questo <strong>senza inviare i dati della sua spesa a un server</strong>?",
    storyP3: "Ecco Freshli. Un'applicazione progettata per iOS 26 che utilizza il framework Foundation Models di Apple per trasformare il contenuto del suo frigorifero in pasti, anziché in rifiuti — interamente in locale, con zero chiamate di rete. Privato per design. Istantaneo per natura. Utile per default.",
    mission: "La nostra missione",
    missionCallout: "Rendere la lotta allo spreco alimentare naturale, gratificante e collettiva — affinché salvare cibo diventi un'abitudine ovvia quanto la raccolta differenziata.",
    missionP: "Crediamo che la soluzione allo spreco alimentare non sia il senso di colpa. Non è l'ennesimo documentario sulle discariche. È rendere la <em>cosa giusta</em> la <em>cosa facile</em>. Quando il suo telefono le dice cosa sta per scadere, le propone una ricetta da 15 minuti e le mostra che altre 347 persone hanno appena salvato cibo — all'improvviso, salvare quegli spinaci sembra unirsi a un movimento, non un compito ingrato.",
    values: "I nostri valori",
    value1Title: "Prima la privacy",
    value1Text: "I dati della sua dispensa sono elaborati sul suo dispositivo. La nostra IA gira interamente in locale grazie ad Apple Intelligence. Nessun server vede la sua spesa.",
    value2Title: "Il pianeta prima del profitto",
    value2Text: "Ogni funzionalità che sviluppiamo è misurata con un unico criterio: impedisce a più cibo di finire in discarica? Se la risposta è no, non la rilasciamo.",
    value3Title: "La comunità invece della competizione",
    value3Text: "Le eccedenze alimentari devono andare a un vicino, non nel cestino. Creiamo strumenti che avvicinano le persone, non che le isolano.",
    value4Title: "Accessibile a tutti",
    value4Text: "Tracciamento dello sguardo ARKit per una navigazione a mani libere, cucina guidata vocalmente, supporto completo VoiceOver, Dynamic Type, Riduci animazioni, 10 lingue. Lo spreco alimentare è affare di tutti — lo deve essere anche la soluzione.",
    roadmap: "I nostri obiettivi",
    roadmapIntro: "Freshli è appena all'inizio. Ecco la nostra roadmap — non solo funzionalità, ma i traguardi di impatto che puntiamo a raggiungere:",
    stat1Label: "Alimenti salvati entro il 2027",
    stat2Label: "CO² evitata",
    stat3Label: "Famiglie che usano Freshli",
    stat4Label: "Paesi raggiunti",
    roadAhead: "La strada davanti a noi",
    q22026: "Lancio sull'App Store",
    q22026Text: "Freshli 1.0 con lo Chef Salvatore IA, la cucina a mani libere, il marketplace comunitario, l'Onda in diretta, la Retrospettiva settimanale, il companion per Apple Watch, il design Liquid Glass con shader Metal 4 e il supporto per 10 lingue.",
    q32026: "Partnership con la grande distribuzione",
    q32026Text: "Colleghi le sue carte fedeltà (Esselunga, Conad, Coop, ecc.) per importare automaticamente i suoi acquisti. Un gesto per aggiungere tutto alla sua dispensa.",
    q42026: "Rete di frigoriferi solidali",
    q42026Text: "Passare da 10 frigoriferi iniziali a oltre 500 postazioni verificate in tutta Italia, Irlanda ed Europa. Aggiornamenti di disponibilità in tempo reale.",
    year2027: "Report di impatto municipali",
    year2027Text: "Aggregare dati anonimi sui rifiuti per offrire agli enti locali informazioni utili sulle abitudini di spreco alimentare delle famiglie. Politiche guidate dai dati.",
    yearPlus: "Espansione globale",
    yearPlusText: "Localizzare l'applicazione in oltre 20 lingue. Stringere partnership con banchi alimentari, scuole e associazioni comunitarie in tutto il mondo. Rendere la lotta allo spreco uno standard globale.",
    joinUs: "Si unisca a noi",
    joinUsP1: "Freshli è gratuita da scaricare. Nessun account richiesto per iniziare a monitorare la dispensa. Ogni alimento salvato è uno in meno in discarica — e una ragione in più per credere che, insieme, possiamo cambiare le cose.",
    joinUsP2: "<strong>Per le persone. Per il pianeta.</strong>",
    downloadLink: "Scarica Freshli →",
    partnerLink: "Diventa partner →",
    contactLink: "Contattaci →"
  },
  partners: {
    heroTitle: "Combattiamo insieme<br>lo spreco.",
    heroSubtitle: "Si associ a Freshli per raggiungere migliaia di famiglie attente all'ambiente. Sponsorizzi la nostra missione. Faccia una donazione per mantenere gratuita l'app.",
    whyTitle: "Perché associarsi a Freshli?",
    whyText: "Gli utenti di Freshli <strong>cercano attivamente di ridurre la propria impronta ecologica</strong>. Monitorano i loro alimenti, cucinano con ciò che hanno, condividono le eccedenze con i vicini e misurano il loro impatto CO² ogni settimana. È uno dei pubblici più impegnati e allineati ai valori dell'App Store.",
    reach: "Un pubblico mirato",
    reachText: "Ogni utente di Freshli ha a cuore la sostenibilità. Il suo marchio raggiunge persone che scelgono attivamente prodotti ecoresponsabili.",
    impact: "Un impatto misurabile",
    impactText: "Monitoriamo gli alimenti salvati, la CO² evitata e i pasti condivisi. La sua partnership include indicatori di impatto reali e utilizzabili.",
    align: "Allineamento di marca",
    alignText: "Associ il suo marchio a una missione che ispira. Salvare cibo è universalmente positivo — nessuna polemica, solo buona volontà.",
    scale: "Portata globale",
    scaleText: "Freshli è disponibile in 10 lingue nei principali mercati dell'App Store. Una sola partnership, visibilità mondiale.",
    opportunities: "Opportunità di partnership",
    mostImpact: "IMPATTO MASSIMO",
    retailer: "Integrazione retail",
    retailerPrice: "Per supermercati e catene alimentari",
    retailerText: "Colleghi il suo programma fedeltà a Freshli affinché i suoi clienti possano importare automaticamente i loro acquisti e monitorare gli alimenti a casa.",
    retailerL1: "Integrazione delle carte fedeltà (Esselunga, Conad, Coop, ecc.)",
    retailerL2: "Suggerimenti di ricette con i suoi prodotti",
    retailerL3: "Presenza in-app di fronte a milioni di utenti attivi",
    retailerL4: "Report d'impatto condivisi per le sue campagne CSR",
    getInTouch: "Ci contatti",
    mission: "Mecenate della missione",
    missionPrice: "Per i marchi impegnati nella sostenibilità",
    missionText: "Sponsorizzi la versione gratuita di Freshli affinché più famiglie accedano a strumenti anti-spreco senza barriere di pagamento.",
    missionL1: "«Offerto da [Il suo marchio]» nell'app",
    missionL2: "Presenza nella scheda condivisibile della Retrospettiva settimanale",
    missionL3: "Report d'impatto co-brandizzati",
    missionL4: "Copertura stampa come mecenate fondatore",
    missionL5: "Accesso prioritario alle nuove funzionalità",
    becomeSponsor: "Diventa mecenate",
    community: "Partner comunitario",
    communityPrice: "Per banchi alimentari, associazioni ed enti locali",
    communityText: "Integri la sua rete di frigoriferi solidali, i suoi punti di raccolta o i suoi programmi di riduzione dei rifiuti in Freshli.",
    communityL1: "Censimento in-app dei suoi frigoriferi e punti di ritiro",
    communityL2: "Aggiornamenti di disponibilità in tempo reale da parte degli utenti",
    communityL3: "Dati anonimi sullo spreco per orientare le politiche pubbliche",
    communityL4: "Gratuito — a vita, per le associazioni",
    partnerWithUs: "Diventa partner",
    sponsor: "Sponsorizza Freshli",
    sponsorText: "Il mecenatismo permette di mantenere gratuite le funzionalità essenziali di Freshli per tutte le famiglie. Il suo sostegno finanzia direttamente:",
    sponsorL1: "L'infrastruttura server del marketplace comunitario",
    sponsorL2: "L'estensione della rete di frigoriferi solidali a nuove città",
    sponsorL3: "La localizzazione in più lingue, affinché più persone possano salvare cibo",
    sponsorL4: "Miglioramenti di accessibilità per utenti con disabilità",
    sponsorL5: "Iniziative scolastiche — sensibilizzare la prossima generazione sullo spreco alimentare",
    donate: "Fai una donazione",
    donateTitle: "Manteniamo Freshli gratuito per tutti",
    donateText: "Ogni donazione finanzia direttamente la lotta allo spreco alimentare — costi server, ampliamento della rete di frigoriferi e mantenimento gratuito dell'app.",
    donateKofi: "Supporta su Ko-fi",
    donateKofiNote: "Offerto da Ko-fi — <strong>0% di commissioni di piattaforma</strong>. Il 100% della sua donazione va a Freshli.",
    donateOneTime: "☕ Donazione una tantum",
    donateMonthly: "💚 Mensile",
    donateBank: "🏦 Bonifico bancario",
    donateDisclaimer: "Freshli non è ancora riconosciuta come ente benefico. Le donazioni sono trattate come contributi al progetto tramite Ko-fi (Stripe/PayPal). Per una donazione 100% senza commissioni, scelga il bonifico bancario — ci scriva per saperne di più. Stiamo lavorando per ottenere questo riconoscimento.",
    advertise: "Fai pubblicità con Freshli",
    advertiseP1: "Offriamo opportunità pubblicitarie limitate e curate, riservate a marchi allineati alla nostra missione. Niente pop-up, niente tracciamento, niente vendita di dati — semplicemente prodotti pertinenti presentati a persone attente alla sostenibilità.",
    advertiseAccept: "<strong>Cosa accettiamo:</strong> marchi alimentari ecoresponsabili, prodotti da cucina sostenibili, marchi zero rifiuti, negozi biologici, aziende di alimentazione vegetale.",
    advertiseDecline: "<strong>Cosa rifiutiamo:</strong> catene fast food, prodotti in plastica monouso, qualsiasi cosa contraria alla nostra missione.",
    advertiseContact: "Contatti support@freshli.app per il nostro tariffario e i dati di pubblico.",
    ctaTitle: "Pronto a fare la differenza?",
    ctaText: "Che lei sia un supermercato, un marchio impegnato, un banco alimentare o semplicemente qualcuno che vuole aiutare — saremo felici di parlare con lei."
  },
  press: {
    title: "Kit stampa",
    intro: "Tutto ciò di cui giornalisti e creatori hanno bisogno per parlare di Freshli. Per richieste stampa, contatti support@freshli.app.",
    aboutTitle: "Su Freshli",
    boilerplate: "Freshli è un'applicazione iOS che aiuta le famiglie a salvare i propri alimenti dalla spazzatura grazie ad Apple Intelligence in locale. Gli utenti monitorano la dispensa, ottengono ricette generate dall'IA per gli ingredienti in scadenza (interamente in locale, senza alcuna chiamata di rete), cucinano a mani libere con passaggi guidati vocalmente, condividono le loro eccedenze con i vicini e vedono il loro impatto ambientale crescere settimana dopo settimana. Progettata con Swift 6.2, SwiftUI, SwiftData e Metal 4 per iOS 26. Per le persone. Per il pianeta.",
    keyFacts: "Numeri chiave",
    fact1: "Dimensione del download",
    fact2: "Lingue supportate",
    fact3: "Elaborazione IA in locale",
    fact4: "Tracker di terze parti",
    fact5: "Spreco alimentare medio per famiglia all'anno",
    fact6: "CO² evitata per alimento salvato",
    differentTitle: "Cosa rende Freshli unica",
    diff1: "<strong>IA in locale:</strong> lo Chef Salvatore utilizza il framework FoundationModels di iOS 26 — le ricette sono generate interamente sul dispositivo. Nessun server, nessun costo API, nessun compromesso sulla privacy.",
    diff2: "<strong>Comunità prima di tutto:</strong> condivida le eccedenze con i vicini, doni ai frigoriferi solidali, si unisca a cerchie locali per una condivisione iper-locale.",
    diff3: "<strong>Un impatto che si percepisce:</strong> la Retrospettiva settimanale — una storia cinematografica e condivisibile del suo impatto anti-spreco, con sfondi MeshGradient animati e un albero che cresce.",
    diff4: "<strong>Cucina a mani libere:</strong> Freshli legge ogni passaggio della ricetta ad alta voce, così l'utente non deve mai toccare il telefono mentre cucina. Gli occhi sulla padella, non sullo schermo.",
    diff5: "<strong>Accessibilità tramite tracciamento dello sguardo:</strong> il face tracking ARKit consente una navigazione a mani libere — gli elementi dell'interfaccia si dilatano sottilmente verso lo sguardo dell'utente. Piena conformità WCAG 2.2 AA.",
    diff6: "<strong>Integrazione profonda con la piattaforma:</strong> Apple Watch, Comandi Rapidi Siri, widget del Centro di Controllo, widget interattivi, Live Activities, Dynamic Island e azioni rapide ControlWidget.",
    techTitle: "Tecnologie iOS 26 utilizzate",
    brandTitle: "Risorse del marchio",
    appName: "<strong>Nome dell'app:</strong> Freshli",
    tagline: "<strong>Slogan:</strong> Per le persone. Per il pianeta.",
    subtitle: "<strong>Sottotitolo:</strong> Salva cibo. Salva il pianeta.",
    category: "<strong>Categoria:</strong> Cibo e bevande (principale), Lifestyle (secondaria)",
    colors: "Colori del marchio",
    screenshots: "Screenshot",
    screenshotsText: "Screenshot App Store ad alta risoluzione (1320 × 2868, iPhone 17 Pro Max) sono disponibili. Contatti support@freshli.app per ricevere il kit stampa completo con i mockup incorniciati.",
    contactTitle: "Contatti",
    pressEnquiries: "<strong>Richieste stampa:</strong>",
    website: "<strong>Sito web:</strong>",
    appStore: "<strong>App Store:</strong> disponibile sull'App Store (iOS 26+)"
  },
  social: {
    title: "Segui l'onda del salvataggio.",
    subtitle: "Novità in diretta, consigli anti-spreco, storie della comunità e retroscena del team Freshli.",
    liveFrom: "In diretta da Freshli",
    liveFromText: "Scopra cosa condividiamo sui nostri diversi canali — prema una piattaforma per vedere le ultime novità.",
    followInstagram: "Ci segua su Instagram",
    followInstagramText: "Retroscena, consigli anti-spreco e momenti salienti della Retrospettiva settimanale. Segua @freshliapp per la sua ispirazione quotidiana.",
    openInstagram: "Apri Instagram →",
    phTitle: "Freshli su Product Hunt",
    phText: "Voti per Freshli al nostro lancio, lasci una recensione e ci aiuti a raggiungere la prima pagina. Ogni voto conta.",
    phLink: "Vedi su Product Hunt →",
    newsletterTitle: "Non si perda il lancio.",
    newsletterText: "Ci segua sulla sua piattaforma preferita per essere il primo a sapere quando Freshli arriverà sull'App Store.",
    newsletterCta: "Segui @everwiseapps su X →"
  },
  privacy: {
    title: "Informativa sulla privacy",
    updated: "Ultimo aggiornamento: 12 aprile 2026",
    highlight: "I dati della sua dispensa sono elaborati sul suo dispositivo. Lo Chef Salvatore IA di Freshli funziona interamente in locale grazie ad Apple Intelligence — i suoi dati alimentari non lasciano mai il suo telefono.",
    h1: "1. Chi siamo",
    p1: "Freshli è gestita da Freshli («noi», «nostro», «nostri»). La presente informativa spiega come raccogliamo, utilizziamo e proteggiamo le sue informazioni personali quando utilizza l'applicazione iOS Freshli e il sito freshli.app.",
    contact: "Contatto:",
    h2: "2. Informazioni che raccogliamo",
    h21: "2.1 Informazioni dell'account",
    p21: "Quando crea un account, raccogliamo:",
    p21a: "<strong>Indirizzo e-mail</strong> — per l'autenticazione e il recupero dell'account",
    p21b: "<strong>Nome utente</strong> — visualizzato nel marketplace comunitario",
    p21c: "<strong>Metadati Apple ID</strong> — se utilizza Accedi con Apple (nome, e-mail relay)",
    h22: "2.2 Dati della dispensa",
    p22: "Gli alimenti che aggiunge alla sua dispensa (nomi, quantità, date di scadenza, categorie, luoghi di conservazione) sono memorizzati:",
    p22a: "<strong>Localmente sul suo dispositivo</strong> tramite SwiftData — sempre disponibili offline",
    p22b: "<strong>Sui nostri server</strong> (Supabase, regione EU-West) — per la sincronizzazione multi-dispositivo e il backup, cifrati in transito e a riposo",
    h23: "2.3 Dati comunitari",
    p23: "Se offre eccedenze alimentari nel marketplace comunitario, i dettagli del suo annuncio (nome dell'alimento, descrizione, zona generale) sono visibili agli altri utenti. Il suo indirizzo esatto non è mai condiviso, a meno che lei non scelga di includere le modalità di ritiro.",
    h24: "2.4 Analisi di utilizzo",
    p24: "Raccogliamo analisi di prodotto anonime per migliorare l'applicazione:",
    p24a: "Quali funzionalità utilizza (es. Chef Salvatore, Retrospettiva settimanale) — mai il contenuto",
    p24b: "Versione dell'app, durata della sessione, tasso di sessioni senza crash",
    p24c: "Nessun identificativo del dispositivo, nessun identificativo pubblicitario, nessun tracker di terze parti",
    h25: "2.5 Elaborazione IA",
    p25: "Lo Chef Salvatore di Freshli utilizza il framework FoundationModels di Apple in locale. Il contenuto della sua dispensa è elaborato interamente sul suo iPhone — non viene mai inviato ai nostri server, a quelli di Apple né a terzi per l'elaborazione IA.",
    h3: "3. Come utilizziamo le sue informazioni",
    p3a: "Per fornire e mantenere il servizio Freshli",
    p3b: "Per sincronizzare i dati della sua dispensa tra i suoi dispositivi",
    p3c: "Per inviare notifiche di promemoria di scadenza (con la sua autorizzazione)",
    p3d: "Per visualizzare i suoi annunci nel marketplace comunitario",
    p3e: "Per calcolare e mostrare il suo impatto ambientale (CO2 evitata, denaro risparmiato)",
    p3f: "Per migliorare l'applicazione tramite analisi anonime e aggregate",
    p3note: "Non vendiamo <strong>mai</strong> i suoi dati personali a terzi. Non utilizziamo <strong>mai</strong> i suoi dati per scopi pubblicitari.",
    h4: "4. Archiviazione e sicurezza dei dati",
    p4a: "I dati server sono ospitati su <strong>Supabase</strong> (regione EU-West-3, infrastruttura AWS)",
    p4b: "Tutti i dati sono cifrati in transito (TLS 1.3) e a riposo (AES-256)",
    p4c: "La Row Level Security (RLS) garantisce che solo lei possa accedere ai suoi dati",
    p4d: "Le password sono verificate tramite HaveIBeenPwned per impedire l'uso di credenziali compromesse",
    h5: "5. Condivisione dei dati",
    p5: "Condividiamo i suoi dati unicamente nei seguenti casi limitati:",
    p5a: "<strong>Marketplace comunitario</strong> — i dettagli del suo annuncio sono visibili agli altri utenti (lei decide cosa condividere)",
    p5b: "<strong>Obblighi di legge</strong> — se richiesto dalla legge, da un provvedimento giudiziario o da un'autorità di regolamentazione",
    p5c: "<strong>Fornitori</strong> — Supabase (hosting del database), Apple (autenticazione, notifiche push) — sotto rigorosi accordi di trattamento dei dati",
    h6: "6. I suoi diritti",
    p6: "Lei ha il diritto di:",
    p6a: "<strong>Accedere</strong> ai suoi dati — disponibili nelle Impostazioni dell'app",
    p6b: "<strong>Eliminare</strong> il suo account e tutti i dati associati — Impostazioni → Elimina account",
    p6c: "<strong>Esportare</strong> i dati della sua dispensa — contatti support@freshli.app",
    p6d: "<strong>Revocare il consenso</strong> alle notifiche — dalle Impostazioni iOS",
    p6e: "<strong>Rifiutare</strong> le analisi — dalla schermata Impostazioni dell'app",
    h7: "7. Conservazione dei dati",
    p7: "Conserviamo i suoi dati finché il suo account è attivo. Se elimina il suo account, tutti i suoi dati personali saranno rimossi definitivamente dai nostri server entro 30 giorni. I dati analitici anonimi e aggregati possono essere conservati a tempo indeterminato.",
    h8: "8. Privacy dei minori",
    p8: "Freshli non si rivolge a minori di 13 anni. Non raccogliamo consapevolmente informazioni personali da minori. Se ritiene che un minore ci abbia fornito dati personali, contatti support@freshli.app e li elimineremo.",
    h9: "9. Modifiche a questa informativa",
    p9: "Possiamo aggiornare questa informativa sulla privacy occasionalmente. La informeremo dei cambiamenti importanti tramite l'applicazione o via e-mail. La data «Ultimo aggiornamento» in cima a questa pagina indica la revisione più recente.",
    h10: "10. Contattarci",
    p10: "Per qualsiasi domanda su questa informativa sulla privacy o sui suoi dati, ci contatti a:",
    email: "<strong>E-mail:</strong>"
  },
  terms: {
    title: "Termini di servizio",
    updated: "Ultimo aggiornamento: 12 aprile 2026 · Contratto di licenza con l'utente finale (EULA)",
    h1: "1. Accettazione dei termini",
    p1: "Scaricando, installando o utilizzando l'applicazione Freshli («l'Applicazione»), lei accetta di essere vincolato da questi Termini di servizio («Termini»). Se non accetta questi Termini, non utilizzi l'Applicazione.",
    h2: "2. Licenza",
    p2: "Freshli le concede una licenza limitata, non esclusiva, non trasferibile e revocabile per utilizzare l'Applicazione su qualsiasi dispositivo Apple che lei possiede o controlla, soggetta ai Termini e condizioni dei servizi Apple Media. Questa licenza non la autorizza a:",
    p2a: "Ridistribuire, concedere in sub-licenza o vendere l'Applicazione",
    p2b: "Eseguire reverse engineering, decompilare o disassemblare l'Applicazione",
    p2c: "Utilizzare l'Applicazione per scopi illeciti",
    p2d: "Interferire o disturbare i server o le reti dell'Applicazione",
    h3: "3. Account",
    p3: "Può creare un account tramite e-mail/password o tramite Accedi con Apple. È responsabile della riservatezza delle sue credenziali e di ogni attività svolta dal suo account. Deve avere almeno 13 anni per creare un account.",
    h4: "4. Contenuti dell'utente",
    p4: "Lei mantiene la proprietà di tutti i contenuti che crea nell'Applicazione (alimenti della dispensa, annunci, recensioni). Pubblicando contenuti nel marketplace comunitario, concede a Freshli una licenza non esclusiva e mondiale per mostrare tali contenuti agli altri utenti, al solo scopo di gestire il marketplace.",
    p4note: "Si impegna a non pubblicare contenuti che siano:",
    p4a: "Falsi, fuorvianti o fraudolenti",
    p4b: "Dannosi, offensivi, molesti o discriminatori",
    p4c: "In violazione di qualsiasi legge o regolamento",
    p4d: "Lesivi di diritti di proprietà intellettuale",
    h5: "5. Marketplace comunitario",
    p5: "Il marketplace comunitario consente agli utenti di condividere le loro eccedenze alimentari con i vicini. Freshli agisce come piattaforma e non è parte delle transazioni tra utenti. Freshli non garantisce la qualità, la sicurezza o la legalità degli alimenti offerti. Gli utenti condividono e ritirano alimenti a proprio rischio.",
    h6: "6. Abbonamenti",
    p6: "Freshli offre funzionalità premium opzionali tramite abbonamenti a rinnovo automatico («Freshli Pro»). Gli abbonamenti sono fatturati tramite il suo account Apple ID. Il pagamento viene addebitato alla conferma dell'acquisto. Gli abbonamenti si rinnovano automaticamente, salvo cancellazione almeno 24 ore prima della fine del periodo in corso. Può gestire o annullare i suoi abbonamenti nelle Impostazioni del suo iPhone → Apple ID → Abbonamenti.",
    h7: "7. Funzionalità IA",
    p7: "Lo Chef Salvatore di Freshli utilizza il framework FoundationModels di Apple in locale per generare suggerimenti di ricette. I contenuti generati dall'IA sono forniti a scopo puramente informativo e non devono essere considerati consigli dietetici, nutrizionali o medici professionali. Usi sempre il proprio giudizio in materia di sicurezza alimentare.",
    h8: "8. Clausola di sicurezza alimentare",
    p8: "<strong>Freshli offre il monitoraggio delle date di scadenza come strumento di comodità. Freshli non garantisce la sicurezza né la commestibilità di alcun alimento.</strong> Le date di scadenza inserite dagli utenti possono essere inesatte. Ispezioni sempre attentamente gli alimenti prima di consumarli. Freshli non potrà essere ritenuta responsabile di alcuna malattia, lesione o perdita derivante dal consumo di alimenti monitorati o condivisi tramite l'Applicazione.",
    h9: "9. Proprietà intellettuale",
    p9: "L'Applicazione, compreso il suo design, codice, marchio e contenuti (esclusi i contenuti dell'utente), è di proprietà di Freshli ed è protetta dal diritto d'autore, dai marchi e dalle altre leggi sulla proprietà intellettuale. Il nome Freshli, il logo e lo slogan «Per le persone. Per il pianeta.» sono marchi di Freshli.",
    h10: "10. Limitazione di responsabilità",
    p10: "Nella misura massima consentita dalla legge applicabile, Freshli non potrà essere ritenuta responsabile per danni indiretti, accessori, speciali, consequenziali o punitivi, compresa la perdita di profitti, dati o reputazione, derivanti dal suo utilizzo dell'Applicazione. La responsabilità totale di Freshli non potrà superare l'importo da lei versato per l'Applicazione nei 12 mesi precedenti la richiesta di risarcimento.",
    h11: "11. Risoluzione",
    p11: "Possiamo sospendere o risolvere il suo account se viola questi Termini. Può eliminare il suo account in qualsiasi momento dalle Impostazioni dell'Applicazione. Dopo la risoluzione, il suo diritto di utilizzare l'Applicazione cessa immediatamente e i suoi dati saranno eliminati in conformità con la nostra Informativa sulla privacy.",
    h12: "12. Modifiche ai termini",
    p12: "Possiamo aggiornare questi Termini occasionalmente. L'uso continuato dell'Applicazione dopo le modifiche costituisce accettazione dei nuovi Termini. La informeremo dei cambiamenti importanti tramite l'Applicazione.",
    h13: "13. Condizioni specifiche di Apple",
    p13: "Questi Termini vincolano lei e Freshli, non Apple. Apple non ha alcun obbligo di fornire manutenzione o assistenza. In caso di non conformità a una garanzia applicabile, può informare Apple per ottenere il rimborso del prezzo d'acquisto (ove applicabile); Apple non ha alcun ulteriore obbligo di garanzia. Apple non è responsabile della gestione dei reclami relativi all'Applicazione. Apple è un terzo beneficiario di questi Termini.",
    h14: "14. Legge applicabile",
    p14: "Questi Termini sono regolati dal diritto italiano. Ogni controversia sarà soggetta alla competenza esclusiva dei tribunali italiani.",
    h15: "15. Contatti",
    p15: "Domande su questi Termini? Ci contatti a support@freshli.app."
  }
};
