window.__freshliTranslations = window.__freshliTranslations || {};
window.__freshliTranslations.pt = {
  nav: {
    features: "Funcionalidades",
    impact: "Impacto",
    support: "Suporte",
    downloadFree: "Baixar grátis",
    backHome: "← Voltar ao início",
    language: "Idioma"
  },
  hero: {
    title: "Seus alimentos.<br>Seu <span class=\"green\">impacto.</span>",
    subtitle: "O Freshli usa o Apple Intelligence no seu dispositivo para salvar os alimentos que estão perto da data de validade — privado, instantâneo e sem precisar de internet. Pelas pessoas. Pelo planeta.",
    ctaDownload: "Baixar na App Store",
    ctaFeatures: "Ver funcionalidades ↓",
    badgeAI: "🤖 Apple Intelligence",
    badgeOnDevice: "🔒 100% no dispositivo",
    badgeLanguages: "🌍 10 idiomas"
  },
  how: {
    label: "🚀 Como funciona",
    title: "Três passos para<br>zero desperdício de alimentos.",
    step1Title: "Adicione seus alimentos",
    step1Text: "Escaneie um código de barras, fotografe um cupom fiscal ou adicione manualmente. Em 5 segundos, está pronto.",
    step2Title: "Receba alertas inteligentes",
    step2Text: "O Freshli avisa o que está prestes a vencer e sugere receitas geradas por IA para aproveitar tudo.",
    step3Title: "Salve ou compartilhe",
    step3Text: "Cozinhe, compartilhe com seus vizinhos ou doe a uma geladeira solidária."
  },
  features: {
    label: "✨ Funcionalidades",
    title: "Tudo o que você precisa para<br>acabar com o desperdício.",
    subtitle: "Acompanhe, salve, compartilhe e comemore — tudo em um único aplicativo lindo, feito para quem se importa com o planeta.",
    rescueChef: {
      title: "Chef Resgate IA",
      text: "Toque em um botão e o Apple Intelligence cria receitas sob medida para a sua despensa. No dispositivo, privado e sem precisar de internet."
    },
    expiry: {
      title: "Controle inteligente de validade",
      text: "Escaneie códigos de barras, cupons fiscais ou adicione manualmente. Etiquetas coloridas mostram o que consumir primeiro, em um piscar de olhos."
    },
    community: {
      title: "Compartilhamento solidário",
      text: "Ofereça seus excedentes para retirada gratuita pelos vizinhos. Encontre geladeiras solidárias. Participe de círculos locais para um compartilhamento hiperlocal."
    },
    wrap: {
      title: "Retrospectiva semanal",
      text: "Um resumo cinematográfico da sua jornada antidesperdício — alimentos salvos, CO₂ evitado, dinheiro economizado. Perfeito para compartilhar nos Stories do Instagram."
    },
    watch: {
      title: "Apple Watch e widgets",
      text: "Alertas de validade visíveis num relance no seu pulso. Widgets interativos com consumo em um toque. Live Activities na tela de bloqueio."
    },
    siri: {
      title: "\u00abE aí, Siri, salva minha despensa\u00bb",
      text: "Receitas IA ativadas por voz pela Siri, Atalhos, Spotlight ou Central de Controle. Sem precisar tocar em nada."
    },
    handsfree: {
      title: "Cozinha mãos livres",
      text: "O Freshli lê cada passo da receita em voz alta para você não precisar tocar no celular enquanto cozinha. Olhos na panela, não na tela."
    },
    wave: {
      title: "Onda ao vivo",
      text: "Veja o impacto global em tempo real — quantas pessoas estão salvando alimentos agora, o total de CO₂ evitado e as refeições compartilhadas pelo mundo."
    }
  },
  testimonial: {
    quote: "Eu jogava fora pelo menos R$ 80 de comida por semana. Com o Freshli, não desperdicei nada em três semanas. As receitas IA são realmente úteis.",
    author: "— Sarah K., São Paulo"
  },
  ai: {
    label: "🧠 Apple Intelligence",
    title: "Os dados da sua despensa<br>nunca saem do seu celular.",
    subtitle: "O Chef Resgate do Freshli funciona totalmente no dispositivo graças ao framework FoundationModels do iOS 26. Sem servidores, sem custos de API, sem abrir mão da sua privacidade. Sua geladeira é só sua."
  },
  impact: {
    label: "🌍 Impacto global",
    title: "Juntos, estamos construindo<br>um mundo sem desperdício.",
    subtitle: "Cada alimento que você salva se junta a uma onda global de pessoas que lutam contra o desperdício.",
    itemsRescued: "Alimentos salvos",
    foodSaved: "Comida salva",
    familiesFed: "Famílias alimentadas",
    savedPerHousehold: "Economia por lar por ano"
  },
  faq: {
    label: "❓ Perguntas frequentes",
    title: "Dúvidas frequentes.",
    q1: "O Freshli é mesmo gratuito?",
    a1: "Sim. As funcionalidades essenciais — controle da despensa, alertas de validade, compartilhamento comunitário e Chef Resgate IA — são totalmente gratuitas. O Freshli Pro é uma assinatura opcional para usuários avançados.",
    q2: "A IA precisa de internet?",
    a2: "Não. O Chef Resgate funciona totalmente no seu dispositivo graças ao Apple Intelligence. Sem chamadas a servidores, sem custos de API, nenhum dado sai do seu celular. Funciona 100% offline.",
    q3: "Quais dispositivos são compatíveis?",
    a3: "O Freshli requer iOS 26 ou superior. O Chef Resgate IA exige Apple Intelligence (iPhone 16 e modelos mais recentes). As complicações para Apple Watch precisam do watchOS 26.",
    moreQuestions: "Mais dúvidas? Acesse o Suporte →"
  },
  cta: {
    title: "Comece a salvar<br>seus alimentos hoje mesmo.",
    subtitle: "Download gratuito. Sem necessidade de conta para começar. Sua despensa, sua privacidade, seu planeta.",
    button: "Baixar o Freshli grátis",
    badge1: "iOS 26+",
    badge2: "Apple Watch",
    badge3: "Atalhos da Siri",
    badge4: "Live Activities",
    badge5: "Modo escuro"
  },
  footer: {
    tagline: "Pelas pessoas. Pelo planeta.",
    ourStory: "Nossa história",
    partners: "Parceiros",
    social: "Redes sociais",
    privacy: "Política de privacidade",
    terms: "Termos de uso",
    support: "Suporte",
    press: "Kit de imprensa",
    contact: "Contato",
    home: "Início",
    rights: "© 2026 Freshli. Todos os direitos reservados."
  },
  support: {
    title: "Suporte",
    intro: "Estamos aqui para ajudar. Encontre respostas abaixo ou fale diretamente com a gente — normalmente respondemos em até 24 horas.",
    needHelp: "Precisa de ajuda? A gente te acompanha.",
    hours: "Nossa equipe de suporte atende de segunda a sexta, das 9h às 18h (horário de Brasília).",
    quickHelp: "Ajuda rápida",
    gettingStarted: "Primeiros passos",
    gettingStartedText: "Baixe o Freshli na App Store, entre com sua conta Apple e adicione o primeiro alimento à despensa.",
    notifications: "Notificações",
    notificationsText: "Ative os lembretes de validade nos Ajustes para receber alertas antes que seus alimentos estraguem.",
    rescueChef: "Chef Resgate IA",
    rescueChefText: "Requer Apple Intelligence (iPhone 16 e superior). Toque em \u00abPerguntar ao Freshli\u00bb na tela do Chef Resgate.",
    accountPrivacy: "Conta e privacidade",
    accountPrivacyText: "Exclua sua conta a qualquer momento nos Ajustes. Todos os dados são apagados em até 30 dias.",
    faqTitle: "Perguntas frequentes",
    faq1q: "O Freshli é gratuito?",
    faq1a: "Sim. O Freshli é gratuito para baixar e usar. O Freshli Pro oferece funcionalidades premium opcionais por assinatura, mas o controle da despensa, os alertas de validade e o compartilhamento comunitário são totalmente gratuitos.",
    faq2q: "A IA precisa de internet?",
    faq2a: "Não. O Chef Resgate usa o framework FoundationModels da Apple no dispositivo. Os dados da sua despensa são processados inteiramente no seu iPhone — nada é enviado a servidores. Funciona offline.",
    faq3q: "Quais dispositivos são compatíveis?",
    faq3a: "O Freshli requer iOS 26 ou superior. A funcionalidade Chef Resgate IA precisa do Apple Intelligence (iPhone 16 e modelos mais novos). As complicações do Apple Watch requerem watchOS 26.",
    faq4q: "Como excluo minha conta?",
    faq4a: "Abra o Freshli → Perfil → Ajustes → role até o final → Excluir conta. Todos os seus dados pessoais serão removidos definitivamente dos nossos servidores em até 30 dias.",
    faq5q: "Meus dados estão seguros?",
    faq5a: "Sim. Seus dados são criptografados em trânsito (TLS 1.3) e em repouso (AES-256). Usamos Row Level Security para que somente você possa acessar seus dados. Nunca vendemos seus dados nem usamos rastreadores de terceiros. Consulte nossa Política de privacidade para todos os detalhes.",
    faq6q: "Como cancelo minha assinatura?",
    faq6a: "Abra os Ajustes do iPhone → toque no seu nome → Assinaturas → Freshli Pro → Cancelar assinatura. Você mantém o acesso até o fim do período de cobrança atual.",
    faq7q: "Posso compartilhar comida com meus vizinhos?",
    faq7a: "Sim! Acesse a aba Comunidade e toque em \u00abNovo anúncio\u00bb para oferecer seus excedentes para retirada gratuita. Você também pode ver o que seus vizinhos estão compartilhando e reservar alimentos perto de você.",
    stillNeedHelp: "Ainda precisa de ajuda?",
    stillNeedHelpText: "Se sua dúvida não foi respondida acima, escreva para support@freshli.app descrevendo o problema. Informe o modelo do seu dispositivo e a versão do iOS para que possamos te ajudar mais rápido.",
    reportBug: "Relatar um bug",
    reportBugText: "Encontrou algo estranho? Escreva para support@freshli.app com o assunto \u00abBug Report\u00bb e informe:",
    bugItem1: "O que você estava fazendo quando o problema aconteceu",
    bugItem2: "O que você esperava e o que realmente aconteceu",
    bugItem3: "Um print da tela, se possível",
    bugItem4: "O modelo do seu iPhone e a versão do iOS"
  },
  about: {
    heroTitle: "Pelas pessoas.<br>Pelo planeta.",
    heroSubtitle: "A história do Freshli: por que o criamos, o que nos move e para onde vamos.",
    problem: "O problema",
    problemP1: "Todos os anos, <strong>um terço de toda a comida produzida no mundo é desperdiçada</strong> — 1,3 bilhão de toneladas jogadas em aterros enquanto 828 milhões de pessoas passam fome. Só no Brasil, uma família média joga fora mais de <strong>R$ 1.800 em comida perfeitamente consumível</strong> por ano.",
    problemP2: "O desperdício de alimentos não é só uma questão financeira. Quando a comida se decompõe em aterros, produz metano — um gás de efeito estufa <strong>80 vezes mais potente que o CO²</strong> em um período de 20 anos. Se o desperdício de alimentos fosse um país, seria o terceiro maior emissor de gases de efeito estufa do mundo, atrás de Estados Unidos e China.",
    problemP3: "O mais difícil? A maior parte desse desperdício acontece em casa. Não nas fazendas. Não nos supermercados. Nas nossas geladeiras, armários e cozinhas. Compramos com boas intenções, a vida corre e, quando percebemos, já é tarde demais.",
    callout1: "\u00abO melhor momento para salvar um alimento do lixo é a véspera da validade. O segundo melhor momento é agora.\u00bb",
    story: "Nossa história",
    storyP1: "O Freshli nasceu de uma frustração simples: abrir a geladeira numa terça à noite, ver um saquinho de espinafre esquecido e descobrir que já passou do ponto. Esse momento — repetido milhões de vezes por dia, em milhões de cozinhas — é onde nasce o desperdício.",
    storyP2: "A gente se perguntou: e se o seu celular pudesse te avisar antes desse momento? E se ele pudesse sugerir uma receita que usa o espinafre, metade do pimentão e os ovos que estão todos vencendo nesta semana? E se ele pudesse fazer isso <strong>sem enviar seus dados de compras a um servidor</strong>?",
    storyP3: "Esse é o Freshli. Um aplicativo feito para iOS 26 que usa o framework Foundation Models da Apple para transformar o conteúdo da sua geladeira em refeições, e não em lixo — totalmente no dispositivo, com zero chamadas de rede. Privado por concepção. Instantâneo por natureza. Útil por padrão.",
    mission: "Nossa missão",
    missionCallout: "Tornar o combate ao desperdício de alimentos natural, gratificante e coletivo — para que salvar comida vire um hábito tão óbvio quanto a reciclagem.",
    missionP: "Acreditamos que a solução para o desperdício de alimentos não é a culpa. Não é mais um documentário sobre aterros. É transformar a <em>coisa certa</em> na <em>coisa fácil</em>. Quando o seu celular te avisa o que vai estragar, sugere uma receita de 15 minutos e mostra que outras 347 pessoas acabaram de salvar comida também — de repente, salvar aquele espinafre parece entrar em um movimento, não cumprir uma tarefa chata.",
    values: "Nossos valores",
    value1Title: "Privacidade em primeiro lugar",
    value1Text: "Os dados da sua despensa são processados no seu dispositivo. Nossa IA roda totalmente localmente graças ao Apple Intelligence. Nenhum servidor vê suas compras.",
    value2Title: "Planeta antes do lucro",
    value2Text: "Cada funcionalidade que desenvolvemos é avaliada por um único critério: ela evita que mais comida vá parar no aterro? Se a resposta for não, não lançamos.",
    value3Title: "Comunidade em vez de competição",
    value3Text: "Os excedentes de alimentos devem ir para um vizinho, não para o lixo. Criamos ferramentas que aproximam as pessoas, não que as isolam.",
    value4Title: "Acessível para todos",
    value4Text: "Rastreamento do olhar com ARKit para navegação mãos livres, cozinha guiada por voz, suporte completo a VoiceOver, Dynamic Type, Reduzir Movimento, 10 idiomas. O desperdício de alimentos é assunto de todos — a solução também tem que ser.",
    roadmap: "Nossas metas",
    roadmapIntro: "O Freshli está só começando. Esta é a nossa roadmap — não só de funcionalidades, mas dos marcos de impacto que queremos alcançar:",
    stat1Label: "Alimentos salvos até 2027",
    stat2Label: "CO² evitado",
    stat3Label: "Famílias usando o Freshli",
    stat4Label: "Países alcançados",
    roadAhead: "O caminho à frente",
    q22026: "Lançamento na App Store",
    q22026Text: "Freshli 1.0 com o Chef Resgate IA, cozinha mãos livres, marketplace comunitário, Onda ao vivo, Retrospectiva semanal, companheiro para Apple Watch, design Liquid Glass com shaders Metal 4 e suporte a 10 idiomas.",
    q32026: "Parcerias com redes de varejo",
    q32026Text: "Conecte seus cartões de fidelidade (Pão de Açúcar, Carrefour Brasil, Extra, etc.) para importar compras automaticamente. Um toque para adicionar tudo à despensa.",
    q42026: "Rede de geladeiras solidárias",
    q42026Text: "Sair de 10 geladeiras iniciais para mais de 500 locais verificados no Brasil, na Irlanda e na Europa. Atualizações de disponibilidade em tempo real.",
    year2027: "Relatórios de impacto municipal",
    year2027Text: "Agregar dados anonimizados sobre desperdício para oferecer aos governos locais informações úteis sobre os hábitos de desperdício alimentar das famílias. Políticas guiadas por dados.",
    yearPlus: "Expansão global",
    yearPlusText: "Localizar o app para mais de 20 idiomas. Firmar parcerias com bancos de alimentos, escolas e associações comunitárias pelo mundo. Transformar a luta contra o desperdício em um padrão global.",
    joinUs: "Junte-se a nós",
    joinUsP1: "O Freshli é gratuito para baixar. Não é preciso criar conta para começar a acompanhar sua despensa. Cada alimento salvo é um a menos no aterro — e mais um motivo para acreditar que, juntos, podemos mudar as coisas.",
    joinUsP2: "<strong>Pelas pessoas. Pelo planeta.</strong>",
    downloadLink: "Baixar o Freshli →",
    partnerLink: "Tornar-se parceiro →",
    contactLink: "Fale com a gente →"
  },
  partners: {
    heroTitle: "Vamos combater juntos<br>o desperdício.",
    heroSubtitle: "Seja parceiro do Freshli para alcançar milhares de lares conscientes com o meio ambiente. Patrocine nossa missão. Doe para manter o app gratuito.",
    whyTitle: "Por que ser parceiro do Freshli?",
    whyText: "Os usuários do Freshli <strong>buscam ativamente reduzir a própria pegada ecológica</strong>. Eles acompanham seus alimentos, cozinham com o que têm, compartilham excedentes com os vizinhos e medem o impacto de CO² toda semana. É um dos públicos mais engajados e alinhados em valores da App Store.",
    reach: "Público certeiro",
    reachText: "Todo usuário do Freshli se importa com sustentabilidade. Sua marca alcança pessoas que escolhem ativamente produtos ecologicamente responsáveis.",
    impact: "Impacto mensurável",
    impactText: "Acompanhamos os alimentos salvos, o CO² evitado e as refeições compartilhadas. Sua parceria vem com indicadores de impacto reais e acionáveis.",
    align: "Alinhamento de marca",
    alignText: "Associe sua marca a uma missão que inspira. Salvar alimentos é universalmente positivo — sem polêmicas, só boas energias.",
    scale: "Alcance global",
    scaleText: "O Freshli está disponível em 10 idiomas, nos maiores mercados da App Store. Uma única parceria, visibilidade mundial.",
    opportunities: "Oportunidades de parceria",
    mostImpact: "IMPACTO MÁXIMO",
    retailer: "Integração com varejo",
    retailerPrice: "Para supermercados e redes alimentícias",
    retailerText: "Conecte seu programa de fidelidade ao Freshli para que seus clientes importem compras automaticamente e acompanhem os alimentos em casa.",
    retailerL1: "Integração com cartões de fidelidade (Pão de Açúcar, Carrefour Brasil, Extra, etc.)",
    retailerL2: "Sugestões de receitas com seus produtos",
    retailerL3: "Presença in-app para milhões de usuários ativos",
    retailerL4: "Relatórios de impacto compartilhados para suas campanhas de ESG",
    getInTouch: "Fale com a gente",
    mission: "Patrocinador da missão",
    missionPrice: "Para marcas comprometidas com a sustentabilidade",
    missionText: "Patrocine a versão gratuita do Freshli para que mais lares tenham acesso a ferramentas antidesperdício, sem barreira paga.",
    missionL1: "\u00abApresentado por [Sua marca]\u00bb dentro do app",
    missionL2: "Destaque no card compartilhável da Retrospectiva semanal",
    missionL3: "Relatórios de impacto com marca compartilhada",
    missionL4: "Cobertura de imprensa como patrocinador fundador",
    missionL5: "Acesso antecipado a novas funcionalidades",
    becomeSponsor: "Seja patrocinador",
    community: "Parceiro comunitário",
    communityPrice: "Para bancos de alimentos, ONGs e governos locais",
    communityText: "Integre sua rede de geladeiras solidárias, pontos de coleta ou programas de redução de desperdício ao Freshli.",
    communityL1: "Listagem in-app das suas geladeiras e pontos de coleta",
    communityL2: "Atualizações de disponibilidade em tempo real pelos usuários",
    communityL3: "Dados anonimizados sobre desperdício para embasar políticas públicas",
    communityL4: "Gratuito — para sempre, para ONGs",
    partnerWithUs: "Tornar-se parceiro",
    sponsor: "Patrocinar o Freshli",
    sponsorText: "O patrocínio ajuda a manter as funcionalidades essenciais do Freshli gratuitas para todos os lares. Seu apoio financia diretamente:",
    sponsorL1: "A infraestrutura de servidores do marketplace comunitário",
    sponsorL2: "A expansão da rede de geladeiras solidárias para novas cidades",
    sponsorL3: "A localização em mais idiomas para que mais pessoas possam salvar alimentos",
    sponsorL4: "Melhorias de acessibilidade para usuários com deficiência",
    sponsorL5: "Ações em escolas — conscientizando a próxima geração sobre o desperdício",
    donate: "Fazer uma doação",
    donateTitle: "Vamos manter o Freshli gratuito para todos",
    donateText: "Cada doação financia diretamente o combate ao desperdício de alimentos — custos de servidor, expansão da rede de geladeiras e manutenção do app gratuito.",
    donateKofi: "Apoie no Ko-fi",
    donateKofiNote: "Potencializado pelo Ko-fi — <strong>0% de taxa de plataforma</strong>. 100% da sua doação vai para o Freshli.",
    donateOneTime: "☕ Doação única",
    donateMonthly: "💚 Mensal",
    donateBank: "🏦 Transferência bancária",
    donateDisclaimer: "O Freshli ainda não é reconhecido como instituição beneficente. As doações são tratadas como contribuições ao projeto pelo Ko-fi (Stripe/PayPal). Para uma doação 100% sem taxas, escolha a transferência bancária — fale com a gente para saber mais. Estamos trabalhando para obter esse reconhecimento.",
    advertise: "Anuncie com o Freshli",
    advertiseP1: "Oferecemos oportunidades de publicidade limitadas e cuidadosamente selecionadas, reservadas a marcas alinhadas à nossa missão. Sem pop-ups, sem rastreamento, sem venda de dados — apenas produtos relevantes apresentados a pessoas que se importam com sustentabilidade.",
    advertiseAccept: "<strong>O que aceitamos:</strong> marcas de alimentos ecologicamente responsáveis, produtos sustentáveis para a cozinha, marcas zero waste, mercearias orgânicas, empresas da alimentação à base de plantas.",
    advertiseDecline: "<strong>O que recusamos:</strong> redes de fast-food, produtos de plástico de uso único, tudo o que contradiz a nossa missão.",
    advertiseContact: "Entre em contato com support@freshli.app para receber nossa tabela de preços e os dados de audiência.",
    ctaTitle: "Pronto para fazer a diferença?",
    ctaText: "Seja você um supermercado, uma marca engajada, um banco de alimentos ou simplesmente alguém que quer ajudar — adoraríamos conversar com você."
  },
  press: {
    title: "Kit de imprensa",
    intro: "Tudo o que jornalistas e criadores precisam para falar sobre o Freshli. Para dúvidas de imprensa, contate support@freshli.app.",
    aboutTitle: "Sobre o Freshli",
    boilerplate: "O Freshli é um aplicativo iOS que ajuda as famílias a salvar alimentos do lixo usando o Apple Intelligence no dispositivo. Os usuários acompanham a despensa, recebem receitas geradas por IA para ingredientes perto do vencimento (totalmente no dispositivo, sem chamadas de rede), cozinham mãos livres com passos de receita guiados por voz, compartilham excedentes com os vizinhos e veem seu impacto ambiental crescer semana após semana. Desenvolvido com Swift 6.2, SwiftUI, SwiftData e Metal 4 para iOS 26. Pelas pessoas. Pelo planeta.",
    keyFacts: "Dados principais",
    fact1: "Tamanho do download",
    fact2: "Idiomas suportados",
    fact3: "Processamento de IA no dispositivo",
    fact4: "Rastreadores de terceiros",
    fact5: "Desperdício médio de alimentos por lar por ano",
    fact6: "CO² evitado por alimento salvo",
    differentTitle: "O que torna o Freshli único",
    diff1: "<strong>IA no dispositivo:</strong> o Chef Resgate usa o framework FoundationModels do iOS 26 — as receitas são geradas totalmente no aparelho. Sem servidores, sem custos de API, sem abrir mão da privacidade.",
    diff2: "<strong>Comunidade em primeiro lugar:</strong> compartilhe excedentes com vizinhos, doe a geladeiras solidárias, participe de círculos locais para compartilhamento hiperlocal.",
    diff3: "<strong>Um impacto que se sente:</strong> a Retrospectiva semanal — uma história cinematográfica e compartilhável do seu impacto antidesperdício, com fundos MeshGradient animados e uma árvore que cresce.",
    diff4: "<strong>Cozinha mãos livres:</strong> o Freshli lê cada passo da receita em voz alta para que o usuário nunca precise tocar no celular enquanto cozinha. Olhos na panela, não na tela.",
    diff5: "<strong>Acessibilidade por rastreamento do olhar:</strong> o face tracking com ARKit permite navegação mãos livres — os elementos da interface se expandem sutilmente em direção ao olhar do usuário. Conformidade total com WCAG 2.2 AA.",
    diff6: "<strong>Integração profunda com a plataforma:</strong> Apple Watch, Atalhos da Siri, widgets da Central de Controle, widgets interativos, Live Activities, Dynamic Island e ações rápidas via ControlWidget.",
    techTitle: "Tecnologias iOS 26 utilizadas",
    brandTitle: "Recursos de marca",
    appName: "<strong>Nome do app:</strong> Freshli",
    tagline: "<strong>Slogan:</strong> Pelas pessoas. Pelo planeta.",
    subtitle: "<strong>Subtítulo:</strong> Salve alimentos. Salve o planeta.",
    category: "<strong>Categoria:</strong> Culinária e bebidas (principal), Estilo de vida (secundária)",
    colors: "Cores da marca",
    screenshots: "Capturas de tela",
    screenshotsText: "Capturas de tela em alta resolução para a App Store (1320 × 2868, iPhone 17 Pro Max) estão disponíveis. Escreva para support@freshli.app para receber o kit de imprensa completo, com mockups emoldurados.",
    contactTitle: "Contato",
    pressEnquiries: "<strong>Dúvidas de imprensa:</strong>",
    website: "<strong>Site:</strong>",
    appStore: "<strong>App Store:</strong> disponível na App Store (iOS 26+)"
  },
  social: {
    title: "Acompanhe a onda do resgate.",
    subtitle: "Novidades ao vivo, dicas antidesperdício, histórias da comunidade e bastidores da equipe Freshli.",
    liveFrom: "Ao vivo do Freshli",
    liveFromText: "Descubra o que compartilhamos em nossos canais — toque em uma plataforma para ver as últimas novidades.",
    followInstagram: "Siga-nos no Instagram",
    followInstagramText: "Bastidores, dicas antidesperdício e destaques da Retrospectiva semanal. Siga @freshliapp para uma dose diária de inspiração.",
    openInstagram: "Abrir Instagram →",
    phTitle: "Freshli no Product Hunt",
    phText: "Vote no Freshli no nosso lançamento, deixe um comentário e ajude a gente a chegar ao topo. Cada voto conta.",
    phLink: "Ver no Product Hunt →",
    newsletterTitle: "Não perca o lançamento.",
    newsletterText: "Siga-nos na sua plataforma favorita para ser o primeiro a saber quando o Freshli chegar à App Store.",
    newsletterCta: "Siga @everwiseapps no X →"
  },
  privacy: {
    title: "Política de privacidade",
    updated: "Última atualização: 12 de abril de 2026",
    highlight: "Os dados da sua despensa são processados no seu dispositivo. O Chef Resgate IA do Freshli funciona totalmente no dispositivo graças ao Apple Intelligence — seus dados alimentares nunca saem do celular.",
    h1: "1. Quem somos",
    p1: "O Freshli é operado por Freshli (\u00abnós\u00bb, \u00abnosso\u00bb, \u00abnossa\u00bb). Esta política explica como coletamos, usamos e protegemos suas informações pessoais quando você utiliza o aplicativo iOS Freshli e o site freshli.app.",
    contact: "Contato:",
    h2: "2. Informações que coletamos",
    h21: "2.1 Informações da conta",
    p21: "Ao criar uma conta, coletamos:",
    p21a: "<strong>Endereço de e-mail</strong> — para autenticação e recuperação de conta",
    p21b: "<strong>Nome de usuário</strong> — exibido no marketplace comunitário",
    p21c: "<strong>Metadados do Apple ID</strong> — caso você use Entrar com a Apple (nome, e-mail de relay)",
    h22: "2.2 Dados da despensa",
    p22: "Os alimentos que você adiciona à despensa (nomes, quantidades, datas de validade, categorias, locais de armazenamento) são armazenados:",
    p22a: "<strong>Localmente no seu dispositivo</strong> via SwiftData — sempre disponíveis offline",
    p22b: "<strong>Nos nossos servidores</strong> (Supabase, região EU-West) — para sincronização entre dispositivos e backup, criptografados em trânsito e em repouso",
    h23: "2.3 Dados comunitários",
    p23: "Se você ofertar excedentes alimentares no marketplace comunitário, os detalhes do seu anúncio (nome do alimento, descrição, região geral) ficam visíveis para outros usuários. Seu endereço exato nunca é compartilhado, a menos que você escolha incluir instruções de retirada.",
    h24: "2.4 Analytics de uso",
    p24: "Coletamos análises anônimas de produto para melhorar o aplicativo:",
    p24a: "Quais funcionalidades você usa (ex.: Chef Resgate, Retrospectiva semanal) — nunca o conteúdo",
    p24b: "Versão do app, duração da sessão, taxa de sessões sem falhas",
    p24c: "Nenhum identificador de dispositivo, nenhum identificador publicitário, nenhum rastreador de terceiros",
    h25: "2.5 Processamento de IA",
    p25: "O Chef Resgate do Freshli usa o framework FoundationModels da Apple no dispositivo. O conteúdo da sua despensa é processado inteiramente no seu iPhone — nunca é enviado aos nossos servidores, aos da Apple nem a terceiros para processamento de IA.",
    h3: "3. Como usamos suas informações",
    p3a: "Para fornecer e manter o serviço Freshli",
    p3b: "Para sincronizar os dados da sua despensa entre seus dispositivos",
    p3c: "Para enviar notificações de lembrete de validade (com sua autorização)",
    p3d: "Para exibir seus anúncios no marketplace comunitário",
    p3e: "Para calcular e mostrar seu impacto ambiental (CO2 evitado, dinheiro economizado)",
    p3f: "Para melhorar o aplicativo por meio de analytics anônimos e agregados",
    p3note: "<strong>Nunca</strong> vendemos seus dados pessoais a terceiros. <strong>Nunca</strong> usamos seus dados para fins publicitários.",
    h4: "4. Armazenamento e segurança dos dados",
    p4a: "Os dados dos servidores ficam hospedados no <strong>Supabase</strong> (região EU-West-3, infraestrutura AWS)",
    p4b: "Todos os dados são criptografados em trânsito (TLS 1.3) e em repouso (AES-256)",
    p4c: "A Row Level Security (RLS) garante que somente você possa acessar seus dados",
    p4d: "As senhas são verificadas pelo HaveIBeenPwned para impedir o uso de credenciais comprometidas",
    h5: "5. Compartilhamento de dados",
    p5: "Compartilhamos seus dados apenas nestes casos limitados:",
    p5a: "<strong>Marketplace comunitário</strong> — os detalhes do seu anúncio ficam visíveis para outros usuários (você decide o que compartilhar)",
    p5b: "<strong>Obrigações legais</strong> — caso a lei, uma ordem judicial ou uma autoridade regulatória exija",
    p5c: "<strong>Prestadores de serviço</strong> — Supabase (hospedagem de banco de dados), Apple (autenticação, notificações push) — sob rigorosos contratos de tratamento de dados",
    h6: "6. Seus direitos",
    p6: "Você tem o direito de:",
    p6a: "<strong>Acessar</strong> seus dados — disponíveis nos Ajustes do app",
    p6b: "<strong>Excluir</strong> sua conta e todos os dados associados — Ajustes → Excluir conta",
    p6c: "<strong>Exportar</strong> os dados da sua despensa — fale com support@freshli.app",
    p6d: "<strong>Retirar seu consentimento</strong> para notificações — pelos Ajustes do iOS",
    p6e: "<strong>Recusar</strong> os analytics — na tela de Ajustes do app",
    h7: "7. Retenção de dados",
    p7: "Mantemos seus dados enquanto a sua conta estiver ativa. Se você excluir sua conta, todos os seus dados pessoais serão removidos definitivamente dos nossos servidores em até 30 dias. Dados analíticos anônimos e agregados podem ser mantidos indefinidamente.",
    h8: "8. Privacidade de crianças",
    p8: "O Freshli não é direcionado a crianças menores de 13 anos. Não coletamos intencionalmente informações pessoais de crianças. Se você acreditar que uma criança nos forneceu dados pessoais, escreva para support@freshli.app e nós os excluiremos.",
    h9: "9. Alterações nesta política",
    p9: "Podemos atualizar esta política de privacidade periodicamente. Avisaremos sobre mudanças importantes pelo aplicativo ou por e-mail. A data \u00abÚltima atualização\u00bb no topo desta página indica a revisão mais recente.",
    h10: "10. Fale com a gente",
    p10: "Para qualquer dúvida sobre esta política de privacidade ou sobre seus dados, entre em contato:",
    email: "<strong>E-mail:</strong>"
  },
  terms: {
    title: "Termos de uso",
    updated: "Última atualização: 12 de abril de 2026 · Contrato de licença de usuário final (EULA)",
    h1: "1. Aceitação dos termos",
    p1: "Ao baixar, instalar ou usar o aplicativo Freshli (\u00abAplicativo\u00bb), você concorda em se submeter a estes Termos de uso (\u00abTermos\u00bb). Se você não concorda com estes Termos, não utilize o Aplicativo.",
    h2: "2. Licença",
    p2: "O Freshli concede a você uma licença limitada, não exclusiva, intransferível e revogável para utilizar o Aplicativo em qualquer dispositivo Apple que você possua ou controle, sujeita aos Termos e condições dos serviços Apple Media. Esta licença não autoriza você a:",
    p2a: "Redistribuir, sublicenciar ou vender o Aplicativo",
    p2b: "Fazer engenharia reversa, descompilar ou desmontar o Aplicativo",
    p2c: "Usar o Aplicativo para fins ilegais",
    p2d: "Interferir ou perturbar os servidores ou redes do Aplicativo",
    h3: "3. Conta",
    p3: "Você pode criar uma conta por e-mail/senha ou via Entrar com a Apple. Você é responsável pela confidencialidade das suas credenciais e por qualquer atividade realizada pela sua conta. É preciso ter pelo menos 13 anos para criar uma conta.",
    h4: "4. Conteúdo do usuário",
    p4: "Você mantém a propriedade de qualquer conteúdo criado no Aplicativo (alimentos da despensa, anúncios, avaliações). Ao publicar conteúdo no marketplace comunitário, você concede ao Freshli uma licença não exclusiva e mundial para exibir esse conteúdo a outros usuários, exclusivamente para fins de operação do marketplace.",
    p4note: "Você se compromete a não publicar conteúdo que seja:",
    p4a: "Falso, enganoso ou fraudulento",
    p4b: "Nocivo, abusivo, assediador ou discriminatório",
    p4c: "Contrário a qualquer lei ou regulamento",
    p4d: "Que viole direitos de propriedade intelectual",
    h5: "5. Marketplace comunitário",
    p5: "O marketplace comunitário permite que usuários compartilhem excedentes alimentares com seus vizinhos. O Freshli atua como plataforma e não é parte nas transações entre usuários. O Freshli não garante a qualidade, a segurança ou a legalidade dos alimentos ofertados. Os usuários compartilham e retiram alimentos por conta e risco próprios.",
    h6: "6. Assinaturas",
    p6: "O Freshli oferece funcionalidades premium opcionais por meio de assinaturas de renovação automática (\u00abFreshli Pro\u00bb). As assinaturas são cobradas pela sua conta Apple ID. O pagamento é debitado na confirmação da compra. As assinaturas renovam-se automaticamente, salvo cancelamento pelo menos 24 horas antes do fim do período atual. Você pode gerenciar ou cancelar suas assinaturas em Ajustes do iPhone → Apple ID → Assinaturas.",
    h7: "7. Funcionalidades de IA",
    p7: "O Chef Resgate do Freshli utiliza o framework FoundationModels da Apple no dispositivo para gerar sugestões de receitas. O conteúdo gerado pela IA é fornecido apenas a título informativo e não deve ser considerado aconselhamento dietético, nutricional ou médico profissional. Use sempre o bom senso em relação à segurança alimentar.",
    h8: "8. Cláusula de segurança alimentar",
    p8: "<strong>O Freshli oferece o controle das datas de validade como ferramenta de conveniência. O Freshli não garante a segurança nem a comestibilidade de nenhum alimento.</strong> As datas de validade inseridas pelos usuários podem ser imprecisas. Sempre inspecione cuidadosamente os alimentos antes de consumi-los. O Freshli não pode ser responsabilizado por qualquer doença, ferimento ou perda decorrente do consumo de alimentos acompanhados ou compartilhados pelo Aplicativo.",
    h9: "9. Propriedade intelectual",
    p9: "O Aplicativo, incluindo seu design, código, marca e conteúdo (excluído o conteúdo do usuário), é de propriedade do Freshli e está protegido por direitos autorais, marcas registradas e outras leis de propriedade intelectual. O nome Freshli, seu logotipo e o slogan \u00abPelas pessoas. Pelo planeta.\u00bb são marcas do Freshli.",
    h10: "10. Limitação de responsabilidade",
    p10: "Na máxima extensão permitida pela lei aplicável, o Freshli não será responsável por quaisquer danos indiretos, incidentais, especiais, consequentes ou punitivos, incluindo perda de lucros, de dados ou de reputação, decorrentes do seu uso do Aplicativo. A responsabilidade total do Freshli não excederá o valor que você pagou pelo Aplicativo nos 12 meses anteriores à reclamação.",
    h11: "11. Rescisão",
    p11: "Podemos suspender ou encerrar sua conta se você violar estes Termos. Você pode excluir sua conta a qualquer momento pelos Ajustes do Aplicativo. Após a rescisão, seu direito de uso do Aplicativo cessa imediatamente e seus dados serão removidos conforme nossa Política de privacidade.",
    h12: "12. Alterações dos termos",
    p12: "Podemos atualizar estes Termos periodicamente. O uso continuado do Aplicativo após a alteração implica aceitação dos novos Termos. Avisaremos sobre mudanças importantes pelo Aplicativo.",
    h13: "13. Termos específicos da Apple",
    p13: "Estes Termos vinculam você e o Freshli, não a Apple. A Apple não tem qualquer obrigação de prestar manutenção ou suporte. Em caso de não conformidade com alguma garantia aplicável, você pode notificar a Apple para obter o reembolso do preço de compra (quando aplicável); a Apple não terá nenhuma outra obrigação de garantia. A Apple não se responsabiliza pelo tratamento de reclamações relativas ao Aplicativo. A Apple é uma terceira beneficiária destes Termos.",
    h14: "14. Legislação aplicável",
    p14: "Estes Termos são regidos pela lei francesa. Qualquer litígio será submetido à competência exclusiva dos tribunais franceses.",
    h15: "15. Contato",
    p15: "Dúvidas sobre estes Termos? Fale com support@freshli.app."
  }
};
