window.__freshliTranslations = window.__freshliTranslations || {};
window.__freshliTranslations.zh = {
  nav: {
    features: "功能特色",
    impact: "影响力",
    support: "帮助支持",
    downloadFree: "免费下载",
    backHome: "← 返回首页",
    language: "语言"
  },
  hero: {
    title: "您的食物。<br>您的<span class=\"green\">影响力。</span>",
    subtitle: "Freshli 借助设备端的 Apple Intelligence，帮您拯救即将到期的食物——私密、即时、无需联网。为了每一个人。为了整个地球。",
    ctaDownload: "在 App Store 下载",
    ctaFeatures: "查看功能 ↓",
    badgeAI: "🤖 Apple Intelligence",
    badgeOnDevice: "🔒 100% 本地运行",
    badgeLanguages: "🌍 10 种语言"
  },
  how: {
    label: "🚀 运作方式",
    title: "三步走向<br>零食物浪费。",
    step1Title: "添加您的食物",
    step1Text: "扫描条形码、拍摄购物小票，或手动输入。5 秒即可完成。",
    step2Title: "接收智能提醒",
    step2Text: "Freshli 会提前告知您哪些食物即将过期，并通过 AI 推荐食谱帮您物尽其用。",
    step3Title: "拯救或分享",
    step3Text: "亲自下厨、与邻居分享，或捐赠至社区共享冰箱。"
  },
  features: {
    label: "✨ 功能特色",
    title: "停止浪费所需的<br>一切功能。",
    subtitle: "追踪、拯救、分享与庆祝——全在一款精美的应用中实现，专为心系地球的人而打造。",
    rescueChef: {
      title: "AI 拯救大厨",
      text: "轻按一下，Apple Intelligence 就会根据您的食材库存编写量身定制的食谱。本地运行、私密可靠、无需联网。"
    },
    expiry: {
      title: "智能保质期追踪",
      text: "扫描条形码、购物小票，或手动输入。彩色标签让您一眼看出哪些食物应当优先食用。"
    },
    community: {
      title: "邻里互助分享",
      text: "将多余的食物开放供邻居自取。寻找社区共享冰箱。加入本地圈子，实现超本地化的分享。"
    },
    wrap: {
      title: "每周回顾",
      text: "以电影级视觉回顾您的反浪费之旅——拯救的食物、减少的 CO₂、节省的金钱。可分享至 Instagram 快拍。"
    },
    watch: {
      title: "Apple Watch 与小组件",
      text: "腕上一眼可见的保质期提醒。支持一键消耗的交互式小组件。锁屏上的实时活动信息。"
    },
    siri: {
      title: "「嘿 Siri，拯救我的食材库」",
      text: "通过 Siri、快捷指令、聚焦搜索或控制中心语音激活 AI 食谱。零操作，全语音。"
    },
    handsfree: {
      title: "免手操作烹饪",
      text: "Freshli 会大声朗读每一个烹饪步骤，让您在下厨时无需触碰手机。眼睛看锅，不看屏幕。"
    },
    wave: {
      title: "实时浪潮",
      text: "实时发现全球影响力——此刻有多少人正在拯救食物、累计减少的 CO₂ 排放，以及全世界正在分享的餐食数量。"
    }
  },
  testimonial: {
    quote: "我每周至少要扔掉价值 100 元的食物。用了 Freshli 之后，我连续三周没往垃圾桶里丢过任何东西。AI 食谱真的非常实用。",
    author: "— Sarah K.，北京"
  },
  ai: {
    label: "🧠 Apple Intelligence",
    title: "您食材库的数据<br>从不离开您的手机。",
    subtitle: "Freshli 的拯救大厨借助 iOS 26 的 FoundationModels 框架，完全在本地运行。没有服务器、没有 API 费用、没有隐私妥协。您的冰箱，只属于您自己。"
  },
  impact: {
    label: "🌍 全球影响力",
    title: "携手共建<br>零浪费的世界。",
    subtitle: "您拯救的每一份食物，都汇入全球反食物浪费浪潮之中。",
    itemsRescued: "拯救食物件数",
    foodSaved: "拯救食物总量",
    familiesFed: "受益家庭数",
    savedPerHousehold: "每户家庭年均节省"
  },
  faq: {
    label: "❓ 常见问题",
    title: "常见问题解答。",
    q1: "Freshli 真的免费吗？",
    a1: "是的。核心功能——食材库追踪、保质期提醒、社区分享和 AI 拯救大厨——完全免费。Freshli Pro 是面向进阶用户的可选订阅服务。",
    q2: "AI 功能需要联网吗？",
    a2: "不需要。拯救大厨借助 Apple Intelligence 完全在您的设备上运行。没有服务器调用、没有 API 费用，您的数据不会离开手机。完全离线可用。",
    q3: "支持哪些设备？",
    a3: "Freshli 需要 iOS 26 或更新版本。AI 拯救大厨功能需要 Apple Intelligence（iPhone 16 及更新机型）。Apple Watch 复杂功能需要 watchOS 26。",
    moreQuestions: "还有疑问？前往帮助中心 →"
  },
  cta: {
    title: "即刻开始<br>拯救您的食物。",
    subtitle: "免费下载。无需注册即可上手。您的食材库、您的隐私、您的地球。",
    button: "免费下载 Freshli",
    badge1: "iOS 26+",
    badge2: "Apple Watch",
    badge3: "Siri 快捷指令",
    badge4: "实时活动",
    badge5: "深色模式"
  },
  footer: {
    tagline: "为了每一个人。为了整个地球。",
    ourStory: "我们的故事",
    partners: "合作伙伴",
    social: "社交媒体",
    privacy: "隐私政策",
    terms: "使用条款",
    support: "帮助支持",
    press: "媒体资源包",
    contact: "联系我们",
    home: "首页",
    rights: "© 2026 Freshli。保留所有权利。"
  },
  support: {
    title: "帮助支持",
    intro: "我们随时为您提供帮助。请在下方查找答案，或直接与我们联系——通常会在 24 小时内回复。",
    needHelp: "需要帮助？我们与您同行。",
    hours: "我们的支持团队周一至周五上午 9 点至下午 6 点（北京时间）为您服务。",
    quickHelp: "快速帮助",
    gettingStarted: "入门指南",
    gettingStartedText: "从 App Store 下载 Freshli，使用 Apple 账户登录，添加您的第一件食材。",
    notifications: "通知设置",
    notificationsText: "在「设置」中开启保质期提醒，即可在食物变质前收到提示。",
    rescueChef: "AI 拯救大厨",
    rescueChefText: "需要 Apple Intelligence（iPhone 16 及更新机型）。在拯救大厨界面点击「向 Freshli 提问」。",
    accountPrivacy: "账户与隐私",
    accountPrivacyText: "您可随时在「设置」中删除账户。所有数据将在 30 天内清除。",
    faqTitle: "常见问题",
    faq1q: "Freshli 免费吗？",
    faq1a: "是的。Freshli 可免费下载与使用。Freshli Pro 通过订阅提供可选的进阶功能，但食材库追踪、保质期提醒和社区分享完全免费。",
    faq2q: "AI 功能需要联网吗？",
    faq2a: "不需要。拯救大厨使用 Apple 的 FoundationModels 框架在本地运行。您的食材库数据完全在 iPhone 上处理——不会发送至任何服务器。支持离线使用。",
    faq3q: "支持哪些设备？",
    faq3a: "Freshli 需要 iOS 26 或更新版本。AI 拯救大厨功能需要 Apple Intelligence（iPhone 16 及更新机型）。Apple Watch 复杂功能需要 watchOS 26。",
    faq4q: "如何删除我的账户？",
    faq4a: "打开 Freshli → 个人资料 → 设置 → 滑至最底部 → 删除账户。您的所有个人数据将在 30 天内从我们的服务器中永久移除。",
    faq5q: "我的数据安全吗？",
    faq5a: "是的。您的数据在传输过程中（TLS 1.3）和静态存储中（AES-256）均经过加密。我们使用行级安全策略，确保只有您本人能访问自己的数据。我们绝不出售您的数据，也不使用任何第三方追踪器。详情请参阅隐私政策。",
    faq6q: "如何取消订阅？",
    faq6a: "打开 iPhone「设置」→ 点击您的姓名 → 订阅 → Freshli Pro → 取消订阅。您仍可使用至当前计费周期结束。",
    faq7q: "我可以与邻居分享食物吗？",
    faq7a: "当然可以！前往「社区」标签页，点击「发布新动态」即可开放您的多余食材供邻居自取。您也可以浏览邻居分享的内容，预订附近的食物。",
    stillNeedHelp: "仍需帮助？",
    stillNeedHelpText: "如果上方未能解答您的疑问，请发送邮件至 support@freshli.app 详述您的问题。请注明您的设备型号和 iOS 版本，以便我们更快为您提供帮助。",
    reportBug: "报告问题",
    reportBugText: "发现了某些异常？请发送邮件至 support@freshli.app，主题填写「Bug Report」，并注明：",
    bugItem1: "问题发生时您正在进行的操作",
    bugItem2: "您预期的结果和实际发生的情况",
    bugItem3: "如有可能，请附上截图",
    bugItem4: "您的 iPhone 型号和 iOS 版本"
  },
  about: {
    heroTitle: "为了每一个人。<br>为了整个地球。",
    heroSubtitle: "Freshli 的故事：我们为何创立、驱动我们前行的力量，以及未来方向。",
    problem: "问题所在",
    problemP1: "每年，<strong>全球所生产的食物有三分之一被浪费</strong>——13 亿吨被丢入垃圾填埋场，而同时 8.28 亿人正忍饥挨饿。仅在中国，一个普通家庭每年就会扔掉超过 <strong>6000 元</strong> 仍然完全可以食用的食物。",
    problemP2: "食物浪费不仅仅是经济问题。当食物在垃圾填埋场中腐烂时，会产生甲烷——一种在 20 年内温室效应是 <strong>CO² 的 80 倍</strong> 的气体。如果食物浪费是一个国家，它将是全球第三大温室气体排放国，仅次于美国和中国。",
    problemP3: "最棘手的是什么？这些浪费大多发生在家里。不是在农场。不是在超市。而是在我们的冰箱、橱柜和厨房里。我们怀着美好的意愿采购，生活让我们分神，等回过神来——为时已晚。",
    callout1: "「把食物从垃圾桶里拯救出来的最佳时机，是它到期的前一天。第二好的时机，就是现在。」",
    story: "我们的故事",
    storyP1: "Freshli 源于一个简单的挫败：在某个周二晚上打开冰箱，看到一袋被遗忘的菠菜，才发现它已经过期了。这个瞬间——每天在数百万个厨房中重复数百万次——正是浪费的源头。",
    storyP2: "我们问自己：如果您的手机能在那个瞬间到来之前提醒您呢？如果它能推荐一道食谱，同时用掉那些本周即将过期的菠菜、半只青椒和鸡蛋呢？如果它能做到这一切，<strong>却无需将您的购物数据发送到任何服务器</strong>呢？",
    storyP3: "这就是 Freshli。一款专为 iOS 26 打造的应用，借助 Apple 的 Foundation Models 框架，将您冰箱里的食材转化为餐食，而非垃圾——完全在本地完成，零网络调用。隐私由设计保障。即时为天性。实用为默认。",
    mission: "我们的使命",
    missionCallout: "让反食物浪费变得自然、有成就感且富有集体力量——让拯救食物成为像回收垃圾一样理所当然的习惯。",
    missionP: "我们认为，食物浪费的答案不是愧疚感。不是又一部垃圾填埋场的纪录片。而是让 <em>正确的事</em> 变成 <em>简单的事</em>。当您的手机告诉您哪些食物即将变质、推荐一道 15 分钟食谱、并显示另外 347 人刚刚也拯救了食物——忽然之间，拯救那袋菠菜感觉像是加入一场运动，而非完成一项苦差。",
    values: "我们的价值观",
    value1Title: "隐私至上",
    value1Text: "您的食材库数据在您的设备上处理。我们的 AI 借助 Apple Intelligence 完全本地运行。没有任何服务器看得到您的购物清单。",
    value2Title: "地球先于利润",
    value2Text: "我们开发的每一项功能都以同一标准衡量：它能减少食物进入垃圾填埋场吗？如果答案是否定的，我们就不推出。",
    value3Title: "社区而非竞争",
    value3Text: "多余的食物应当送到邻居手中，而非垃圾桶里。我们打造拉近人与人距离的工具，而非让人孤立的工具。",
    value4Title: "人人可用",
    value4Text: "ARKit 视线追踪实现免手导航、语音引导烹饪、完整的 VoiceOver 支持、动态字体、减少动态效果、10 种语言支持。食物浪费与每个人息息相关——解决方案也理应如此。",
    roadmap: "我们的目标",
    roadmapIntro: "Freshli 才刚刚起步。这是我们的路线图——不仅是功能，还有我们立志达成的影响里程碑：",
    stat1Label: "到 2027 年拯救食物件数",
    stat2Label: "减少 CO² 排放",
    stat3Label: "使用 Freshli 的家庭",
    stat4Label: "覆盖国家数",
    roadAhead: "未来之路",
    q22026: "App Store 上线",
    q22026Text: "Freshli 1.0 将带来 AI 拯救大厨、免手烹饪、社区集市、实时浪潮、每周回顾、Apple Watch 伴侣、搭载 Metal 4 着色器的 Liquid Glass 设计，以及 10 种语言支持。",
    q32026: "零售商合作",
    q32026Text: "连接您的会员卡（盒马、永辉、家乐福等），自动导入购物记录。一键将所有商品加入食材库。",
    q42026: "社区共享冰箱网络",
    q42026Text: "从最初的 10 个共享冰箱扩展至遍布中国、爱尔兰及欧洲各地 500 多个经过认证的站点。实时更新可用状态。",
    year2027: "城市影响力报告",
    year2027Text: "汇总匿名化的浪费数据，为地方政府提供关于家庭食物浪费习惯的可行洞察。以数据驱动政策。",
    yearPlus: "全球扩张",
    yearPlusText: "将应用本地化至 20 多种语言。与全球食品银行、学校和社区组织建立合作。让反食物浪费成为全球准则。",
    joinUs: "加入我们",
    joinUsP1: "Freshli 可免费下载。无需注册即可开始追踪食材库。每拯救一件食物，就少一件进入垃圾填埋场——就多一个相信我们能携手改变世界的理由。",
    joinUsP2: "<strong>为了每一个人。为了整个地球。</strong>",
    downloadLink: "下载 Freshli →",
    partnerLink: "成为合作伙伴 →",
    contactLink: "联系我们 →"
  },
  partners: {
    heroTitle: "携手共同<br>对抗浪费。",
    heroSubtitle: "与 Freshli 合作，触达成千上万注重环保的家庭。赞助我们的使命。捐赠以保持应用免费。",
    whyTitle: "为何与 Freshli 合作？",
    whyText: "Freshli 的用户 <strong>正积极寻求减少生态足迹</strong>。他们追踪食材、以现有食材烹饪、与邻居分享余量，每周衡量自己的 CO² 影响。这是 App Store 上最具参与度、最契合价值观的用户群之一。",
    reach: "精准用户群",
    reachText: "每一位 Freshli 用户都关心可持续发展。您的品牌将触达那些主动选择环保产品的人群。",
    impact: "可衡量的影响",
    impactText: "我们追踪拯救的食物、减少的 CO² 和分享的餐食数量。您的合作将附带真实、可行动的影响指标。",
    align: "品牌契合",
    alignText: "让您的品牌与一项激励人心的使命相联系。拯救食物在全球范围内都是积极正向的——没有争议，只有善意。",
    scale: "全球覆盖",
    scaleText: "Freshli 以 10 种语言在 App Store 最大的市场中上架。一次合作，全球可见。",
    opportunities: "合作机会",
    mostImpact: "影响力最大",
    retailer: "零售商集成",
    retailerPrice: "面向超市和食品连锁企业",
    retailerText: "将您的会员计划连接至 Freshli，让顾客能自动导入购物记录，并在家中追踪食材。",
    retailerL1: "会员卡集成（盒马、永辉、家乐福等）",
    retailerL2: "基于您产品的食谱推荐",
    retailerL3: "触达数百万活跃用户的应用内曝光",
    retailerL4: "为您 CSR 活动提供共享影响力报告",
    getInTouch: "联系我们",
    mission: "使命赞助人",
    missionPrice: "面向致力于可持续发展的品牌",
    missionText: "赞助 Freshli 的免费版本，让更多家庭能无障碍地获得反浪费工具。",
    missionL1: "在应用中展示「由 [您的品牌] 赞助」",
    missionL2: "在每周回顾的分享卡片中突出展示",
    missionL3: "联合品牌影响力报告",
    missionL4: "作为创始赞助人获得媒体报道",
    missionL5: "新功能优先体验权",
    becomeSponsor: "成为赞助人",
    community: "社区合作伙伴",
    communityPrice: "面向食品银行、非营利组织和地方政府",
    communityText: "将您的共享冰箱网络、收集点或减废项目集成到 Freshli 中。",
    communityL1: "应用内展示您的冰箱和捐赠点",
    communityL2: "用户实时更新可用状态",
    communityL3: "匿名浪费数据以支持公共政策",
    communityL4: "对非营利组织终身免费",
    partnerWithUs: "成为合作伙伴",
    sponsor: "赞助 Freshli",
    sponsorText: "赞助有助于让 Freshli 的核心功能为所有家庭保持免费。您的支持直接用于：",
    sponsorL1: "社区集市的服务器基础设施",
    sponsorL2: "将共享冰箱网络扩展到新的城市",
    sponsorL3: "本地化至更多语言，让更多人能拯救食物",
    sponsorL4: "为残障用户提升无障碍体验",
    sponsorL5: "校园行动——让下一代认识食物浪费",
    donate: "进行捐赠",
    donateTitle: "让 Freshli 对所有人保持免费",
    donateText: "每一笔捐款都直接用于反食物浪费——服务器成本、共享冰箱网络扩展，以及让应用保持免费。",
    donateKofi: "在 Ko-fi 上支持",
    donateKofiNote: "由 Ko-fi 提供——<strong>零平台手续费</strong>。您的捐款 100% 归于 Freshli。",
    donateOneTime: "☕ 一次性捐赠",
    donateMonthly: "💚 每月捐赠",
    donateBank: "🏦 银行转账",
    donateDisclaimer: "Freshli 目前尚未注册为慈善组织。捐款通过 Ko-fi（Stripe/PayPal）作为项目贡献处理。如需 100% 无手续费的捐赠，请选择银行转账——可联系我们了解详情。我们正在努力获得慈善资格。",
    advertise: "在 Freshli 上投放广告",
    advertiseP1: "我们提供有限且精心筛选的广告机会，仅向与我们使命相契合的品牌开放。没有弹窗、没有追踪、没有数据售卖——只是将相关的产品呈现给关心可持续发展的人群。",
    advertiseAccept: "<strong>我们接受：</strong>环保食品品牌、可持续厨房用品、零废弃品牌、有机杂货、植物性食品企业。",
    advertiseDecline: "<strong>我们拒绝：</strong>快餐连锁、一次性塑料制品、任何与我们使命相悖的内容。",
    advertiseContact: "请联系 support@freshli.app 获取价目表和受众数据。",
    ctaTitle: "准备好创造改变了吗？",
    ctaText: "无论您是超市、有责任感的品牌、食品银行，或仅仅是一位想帮忙的朋友——我们都很期待与您交流。"
  },
  press: {
    title: "媒体资源包",
    intro: "记者和创作者报道 Freshli 所需的一切资料。如有媒体咨询，请联系 support@freshli.app。",
    aboutTitle: "关于 Freshli",
    boilerplate: "Freshli 是一款 iOS 应用，借助设备端的 Apple Intelligence 帮助家庭将食物从垃圾桶中拯救出来。用户可以追踪食材库、为临期食材获取 AI 生成的食谱（完全本地运行、零网络调用）、通过语音引导步骤实现免手烹饪、与邻居分享多余食材，并看到自己的环境影响每周不断成长。采用 Swift 6.2、SwiftUI、SwiftData 和 Metal 4 为 iOS 26 打造。为了每一个人。为了整个地球。",
    keyFacts: "核心数据",
    fact1: "下载大小",
    fact2: "支持语言",
    fact3: "本地 AI 处理",
    fact4: "第三方追踪器",
    fact5: "家庭年均食物浪费",
    fact6: "每拯救一件食物减少的 CO²",
    differentTitle: "Freshli 的独特之处",
    diff1: "<strong>本地 AI：</strong>拯救大厨使用 iOS 26 的 FoundationModels 框架——食谱完全在设备端生成。没有服务器、没有 API 费用、没有隐私妥协。",
    diff2: "<strong>社区为先：</strong>与邻居分享多余食材、向社区共享冰箱捐赠、加入本地圈子实现超本地化分享。",
    diff3: "<strong>可感知的影响：</strong>每周回顾——以电影级可分享形式讲述您反浪费影响力的故事，配以动态 MeshGradient 背景和不断成长的树木。",
    diff4: "<strong>免手烹饪：</strong>Freshli 大声朗读每一个烹饪步骤，用户在下厨时无需触碰手机。眼睛看锅，不看屏幕。",
    diff5: "<strong>视线追踪无障碍：</strong>ARKit 面部追踪实现免手导航——界面元素会微妙地向用户视线方向扩展。完整符合 WCAG 2.2 AA 标准。",
    diff6: "<strong>深度平台集成：</strong>Apple Watch、Siri 快捷指令、控制中心小组件、交互式小组件、实时活动、灵动岛和 ControlWidget 快速操作。",
    techTitle: "所使用的 iOS 26 技术",
    brandTitle: "品牌资源",
    appName: "<strong>应用名称：</strong>Freshli",
    tagline: "<strong>口号：</strong>为了每一个人。为了整个地球。",
    subtitle: "<strong>副标题：</strong>拯救食物，拯救地球。",
    category: "<strong>类别：</strong>美食（主要）、生活（次要）",
    colors: "品牌色彩",
    screenshots: "应用截图",
    screenshotsText: "高分辨率 App Store 截图（1320 × 2868，iPhone 17 Pro Max）可供使用。请联系 support@freshli.app 获取完整媒体资源包，内含设备画框模型。",
    contactTitle: "联系方式",
    pressEnquiries: "<strong>媒体咨询：</strong>",
    website: "<strong>官方网站：</strong>",
    appStore: "<strong>App Store：</strong>现已上架 App Store（iOS 26+）"
  },
  social: {
    title: "加入拯救浪潮。",
    subtitle: "实时动态、反浪费小贴士、社区故事及 Freshli 团队幕后花絮。",
    liveFrom: "来自 Freshli 的实时动态",
    liveFromText: "发现我们在各个渠道上分享的内容——点击任一平台查看最新动态。",
    followInstagram: "在 Instagram 上关注我们",
    followInstagramText: "幕后花絮、反浪费小贴士以及每周回顾的精彩瞬间。关注 @freshliapp，获取每日灵感。",
    openInstagram: "打开 Instagram →",
    phTitle: "Freshli 登陆 Product Hunt",
    phText: "在我们上线时为 Freshli 投票、留下评价，助我们登上首页。每一票都很重要。",
    phLink: "前往 Product Hunt 查看 →",
    newsletterTitle: "不要错过上线时刻。",
    newsletterText: "在您最喜欢的平台上关注我们，第一时间知晓 Freshli 登陆 App Store 的消息。",
    newsletterCta: "在 X 上关注 @everwiseapps →"
  },
  privacy: {
    title: "隐私政策",
    updated: "最后更新：2026年4月12日",
    highlight: "您食材库的数据在您的设备上处理。Freshli 的 AI 拯救大厨借助 Apple Intelligence 完全在本地运行——您的食物数据从不离开您的手机。",
    h1: "1. 我们是谁",
    p1: "Freshli 由 Freshli（「我们」、「我们的」）运营。本政策说明当您使用 Freshli iOS 应用和 freshli.app 网站时，我们如何收集、使用和保护您的个人信息。",
    contact: "联系方式：",
    h2: "2. 我们收集的信息",
    h21: "2.1 账户信息",
    p21: "当您创建账户时，我们会收集：",
    p21a: "<strong>电子邮件地址</strong>——用于身份验证和账户恢复",
    p21b: "<strong>用户名</strong>——显示于社区集市",
    p21c: "<strong>Apple ID 元数据</strong>——如果您使用「通过 Apple 登录」（姓名、中转邮箱）",
    h22: "2.2 食材库数据",
    p22: "您添加到食材库的食物（名称、数量、保质期、分类、存放位置）将存储于：",
    p22a: "<strong>您设备本地</strong>——通过 SwiftData 存储，始终离线可用",
    p22b: "<strong>我们的服务器</strong>（Supabase，EU-West 区域）——用于多设备同步和备份，传输和静态存储均经加密",
    h23: "2.3 社区数据",
    p23: "如果您在社区集市发布多余食材，您动态中的详情（食物名称、描述、大致区域）将对其他用户可见。除非您选择附上取货安排，否则您的精确地址绝不会被分享。",
    h24: "2.4 使用分析",
    p24: "我们收集匿名产品分析数据以改进应用：",
    p24a: "您使用了哪些功能（例如拯救大厨、每周回顾）——绝不涉及内容",
    p24b: "应用版本、会话时长、无崩溃会话率",
    p24c: "无设备标识符、无广告标识符、无第三方追踪器",
    h25: "2.5 AI 处理",
    p25: "Freshli 的拯救大厨借助 Apple 的 FoundationModels 框架在本地运行。您食材库的内容完全在 iPhone 上处理——绝不会发送到我们的服务器、Apple 的服务器或任何第三方进行 AI 处理。",
    h3: "3. 我们如何使用您的信息",
    p3a: "提供并维护 Freshli 服务",
    p3b: "在您的各台设备间同步食材库数据",
    p3c: "发送保质期提醒通知（经您授权）",
    p3d: "在社区集市展示您的动态",
    p3e: "计算并展示您的环境影响（减少的 CO2、节省的金钱）",
    p3f: "通过匿名聚合分析数据改进应用",
    p3note: "我们<strong>绝不</strong>将您的个人数据出售给第三方。我们<strong>绝不</strong>将您的数据用于广告目的。",
    h4: "4. 数据存储与安全",
    p4a: "服务器数据托管于 <strong>Supabase</strong>（EU-West-3 区域，AWS 基础设施）",
    p4b: "所有数据在传输过程中（TLS 1.3）和静态存储中（AES-256）均经过加密",
    p4c: "行级安全策略（RLS）确保只有您本人能访问自己的数据",
    p4d: "密码通过 HaveIBeenPwned 验证，防止使用已泄露的凭据",
    h5: "5. 数据共享",
    p5: "我们仅在以下有限情况下共享您的数据：",
    p5a: "<strong>社区集市</strong>——您发布动态的详情对其他用户可见（由您决定分享内容）",
    p5b: "<strong>法律义务</strong>——在法律、法院命令或监管机构要求时",
    p5c: "<strong>服务提供商</strong>——Supabase（数据库托管）、Apple（身份验证、推送通知）——均受严格的数据处理协议约束",
    h6: "6. 您的权利",
    p6: "您有权：",
    p6a: "<strong>访问</strong>您的数据——可在应用「设置」中查看",
    p6b: "<strong>删除</strong>您的账户及所有相关数据——「设置」→ 删除账户",
    p6c: "<strong>导出</strong>您的食材库数据——请联系 support@freshli.app",
    p6d: "<strong>撤回</strong>通知同意——通过 iOS 「设置」",
    p6e: "<strong>拒绝</strong>数据分析——在应用「设置」界面",
    h7: "7. 数据保留",
    p7: "您的账户处于活跃状态期间，我们会保留您的数据。如果您删除账户，您所有的个人数据将在 30 天内从我们的服务器中永久移除。匿名聚合分析数据可能会被无限期保留。",
    h8: "8. 儿童隐私",
    p8: "Freshli 不面向 13 岁以下儿童。我们不会有意收集儿童的个人信息。如果您认为有儿童向我们提供了个人数据，请联系 support@freshli.app，我们将予以删除。",
    h9: "9. 政策变更",
    p9: "我们可能会不时更新本隐私政策。对于重大变更，我们将通过应用或电子邮件通知您。本页面顶部的「最后更新」日期显示最新修订时间。",
    h10: "10. 联系我们",
    p10: "如对本隐私政策或您的数据有任何疑问，请联系：",
    email: "<strong>电子邮件：</strong>"
  },
  terms: {
    title: "使用条款",
    updated: "最后更新：2026年4月12日 · 最终用户许可协议（EULA）",
    h1: "1. 接受条款",
    p1: "通过下载、安装或使用 Freshli 应用（「本应用」），您同意受本使用条款（「条款」）约束。如您不同意本条款，请勿使用本应用。",
    h2: "2. 许可授权",
    p2: "Freshli 授予您有限、非排他、不可转让、可撤销的许可，允许您在自己拥有或控制的任何 Apple 设备上使用本应用，受 Apple Media Services 条款与条件约束。本许可不允许您：",
    p2a: "重新分发、转授许可或出售本应用",
    p2b: "对本应用进行逆向工程、反编译或反汇编",
    p2c: "将本应用用于任何非法目的",
    p2d: "干扰或破坏本应用的服务器或网络",
    h3: "3. 账户",
    p3: "您可以通过邮箱/密码或通过 Apple 登录创建账户。您有责任保护凭据的机密性，并对通过您账户进行的所有活动负责。您必须年满 13 岁方可创建账户。",
    h4: "4. 用户内容",
    p4: "您保留在本应用中创建的任何内容（食材库中的食物、动态、评论）的所有权。在社区集市发布内容时，您授予 Freshli 一项非排他性、全球性的许可，以向其他用户展示该内容，仅用于运营社区集市。",
    p4note: "您同意不发布以下内容：",
    p4a: "虚假、误导或欺诈内容",
    p4b: "有害、辱骂、骚扰或歧视性内容",
    p4c: "违反任何法律或法规的内容",
    p4d: "侵犯知识产权的内容",
    h5: "5. 社区集市",
    p5: "社区集市允许用户与邻居分享多余食材。Freshli 作为平台方，不是用户间交易的当事人。Freshli 不对所分享食物的质量、安全性或合法性作任何保证。用户分享和取用食物的风险由其自行承担。",
    h6: "6. 订阅",
    p6: "Freshli 通过自动续订订阅（「Freshli Pro」）提供可选的进阶功能。订阅通过您的 Apple ID 账户扣费。购买确认时扣款。订阅将自动续订，除非在当前周期结束前至少 24 小时取消。您可以在 iPhone「设置」→ Apple ID → 订阅中管理或取消订阅。",
    h7: "7. AI 功能",
    p7: "Freshli 的拯救大厨借助 Apple 的 FoundationModels 框架在本地生成食谱建议。AI 生成的内容仅供参考，不应视为专业的饮食、营养或医疗建议。请始终自行判断食品安全。",
    h8: "8. 食品安全免责声明",
    p8: "<strong>Freshli 提供保质期追踪作为便利工具。Freshli 不对任何食物的安全性或可食用性作出保证。</strong>用户输入的保质期可能不准确。食用前请务必仔细检查食物。对于因食用通过本应用追踪或分享的食物而导致的任何疾病、伤害或损失，Freshli 概不负责。",
    h9: "9. 知识产权",
    p9: "本应用，包括其设计、代码、品牌和内容（不包括用户内容），均为 Freshli 所有，受版权、商标和其他知识产权法保护。Freshli 名称、标志和口号「为了每一个人。为了整个地球。」均为 Freshli 的商标。",
    h10: "10. 责任限制",
    p10: "在适用法律允许的最大范围内，Freshli 不对任何间接、附带、特殊、后果性或惩罚性损害承担责任，包括因您使用本应用而造成的利润、数据或信誉损失。Freshli 的总责任不超过您在索赔前 12 个月内为本应用支付的金额。",
    h11: "11. 终止",
    p11: "如您违反本条款，我们可能暂停或终止您的账户。您可随时在本应用「设置」中删除账户。终止后，您使用本应用的权利立即停止，您的数据将按照我们的隐私政策予以删除。",
    h12: "12. 条款变更",
    p12: "我们可能会不时更新本条款。修改后继续使用本应用即视为接受新条款。对于重大变更，我们将通过本应用通知您。",
    h13: "13. Apple 特定条款",
    p13: "本条款约束的是您和 Freshli，而非 Apple。Apple 没有提供维护或支持的义务。如有适用担保未能履行，您可告知 Apple 以获取购买价款的退款（如适用）；Apple 无任何其他担保义务。Apple 不负责处理与本应用相关的索赔。Apple 是本条款的第三方受益人。",
    h14: "14. 适用法律",
    p14: "本条款受法国法律管辖。任何争议应由法国法院专属管辖。",
    h15: "15. 联系方式",
    p15: "对本条款有疑问？请联系 support@freshli.app。"
  }
};
